(ns baredom.dev.hot-reload
  "Dev-only style hot-reload. Re-injects updated CSS into live component
   instances after shadow-cljs hot-reload so style changes are visible
   without a full page refresh."
  (:require
   [baredom.components.x-alert.x-alert                     :as x-alert-c]
   [baredom.components.x-avatar.x-avatar                   :as x-avatar-c]
   [baredom.components.x-avatar-group.x-avatar-group       :as x-avatar-group-c]
   [baredom.components.x-badge.x-badge                     :as x-badge-c]
   [baredom.components.x-breadcrumbs.x-breadcrumbs         :as x-breadcrumbs-c]
   [baredom.components.x-button.x-button                   :as x-button-c]
   [baredom.components.x-cancel-dialogue.x-cancel-dialogue :as x-cancel-dialogue-c]
   [baredom.components.x-card.x-card                       :as x-card-c]
   [baredom.components.x-chart.x-chart                     :as x-chart-c]
   [baredom.components.x-checkbox.x-checkbox               :as x-checkbox-c]
   [baredom.components.x-chip.x-chip                       :as x-chip-c]
   [baredom.components.x-collapse.x-collapse               :as x-collapse-c]
   [baredom.components.x-command-palette.x-command-palette :as x-command-palette-c]
   [baredom.components.x-container.x-container             :as x-container-c]
   [baredom.components.x-context-menu.x-context-menu       :as x-context-menu-c]
   [baredom.components.x-copy.x-copy                       :as x-copy-c]
   [baredom.components.x-currency-field.x-currency-field   :as x-currency-field-c]
   [baredom.components.x-date-picker.x-date-picker         :as x-date-picker-c]
   [baredom.components.x-divider.x-divider                 :as x-divider-c]
   [baredom.components.x-drawer.x-drawer                   :as x-drawer-c]
   [baredom.components.x-dropdown.x-dropdown               :as x-dropdown-c]
   [baredom.components.x-fieldset.x-fieldset               :as x-fieldset-c]
   [baredom.components.x-file-download.x-file-download     :as x-file-download-c]
   [baredom.components.x-form.x-form                       :as x-form-c]
   [baredom.components.x-form-field.x-form-field           :as x-form-field-c]
   [baredom.components.x-gaussian-blur.x-gaussian-blur     :as x-gaussian-blur-c]
   [baredom.components.x-grid.x-grid                       :as x-grid-c]
   [baredom.components.x-kinetic-typography.x-kinetic-typography :as x-kinetic-typography-c]
   [baredom.components.x-menu.x-menu                       :as x-menu-c]
   [baredom.components.x-menu-item.x-menu-item             :as x-menu-item-c]
   [baredom.components.x-modal.x-modal                     :as x-modal-c]
   [baredom.components.x-navbar.x-navbar                   :as x-navbar-c]
   [baredom.components.x-notification-center.x-notification-center :as x-notification-center-c]
   [baredom.components.x-organic-divider.x-organic-divider :as x-organic-divider-c]
   [baredom.components.x-organic-shape.x-organic-shape     :as x-organic-shape-c]
   [baredom.components.x-pagination.x-pagination           :as x-pagination-c]
   [baredom.components.x-popover.x-popover                 :as x-popover-c]
   [baredom.components.x-progress.x-progress               :as x-progress-c]
   [baredom.components.x-progress-circle.x-progress-circle :as x-progress-circle-c]
   [baredom.components.x-radio.x-radio                     :as x-radio-c]
   [baredom.components.x-ripple-effect.x-ripple-effect     :as x-ripple-effect-c]
   [baredom.components.x-scroll.x-scroll                   :as x-scroll-c]
   [baredom.components.x-scroll-parallax.x-scroll-parallax :as x-scroll-parallax-c]
   [baredom.components.x-scroll-story.x-scroll-story       :as x-scroll-story-c]
   [baredom.components.x-scroll-timeline.x-scroll-timeline :as x-scroll-timeline-c]
   [baredom.components.x-search-field.x-search-field       :as x-search-field-c]
   [baredom.components.x-select.x-select                   :as x-select-c]
   [baredom.components.x-sidebar.x-sidebar                 :as x-sidebar-c]
   [baredom.components.x-skeleton.x-skeleton               :as x-skeleton-c]
   [baredom.components.x-slider.x-slider                   :as x-slider-c]
   [baredom.components.x-spacer.x-spacer                   :as x-spacer-c]
   [baredom.components.x-spinner.x-spinner                 :as x-spinner-c]
   [baredom.components.x-stat.x-stat                       :as x-stat-c]
   [baredom.components.x-stepper.x-stepper                 :as x-stepper-c]
   [baredom.components.x-switch.x-switch                   :as x-switch-c]
   [baredom.components.x-tab.x-tab                         :as x-tab-c]
   [baredom.components.x-table.x-table                     :as x-table-c]
   [baredom.components.x-table-cell.x-table-cell           :as x-table-cell-c]
   [baredom.components.x-table-row.x-table-row             :as x-table-row-c]
   [baredom.components.x-tabs.x-tabs                       :as x-tabs-c]
   [baredom.components.x-text-area.x-text-area             :as x-text-area-c]
   [baredom.components.x-timeline.x-timeline               :as x-timeline-c]
   [baredom.components.x-timeline-item.x-timeline-item     :as x-timeline-item-c]
   [baredom.components.x-toast.x-toast                     :as x-toast-c]
   [baredom.components.x-toaster.x-toaster                 :as x-toaster-c]
   [baredom.components.x-typography.x-typography            :as x-typography-c]))

(defn- resolve-style
  "Returns CSS string whether v is a string (def) or zero-arg fn (defn)."
  [v]
  (if (fn? v) (v) v))

(defn- refresh-component-styles!
  "Re-inject updated CSS into every live instance's shadow DOM."
  [pairs]
  (doseq [[tag style-val] pairs]
    (let [css (resolve-style style-val)]
      (doseq [^js el (array-seq (.querySelectorAll js/document tag))]
        (when-let [^js root (.-shadowRoot el)]
          (when-let [^js s (.querySelector root "style")]
            (when (not= (.-textContent s) css)
              (set! (.-textContent s) css))))))))

(defn refresh-styles!
  "Re-inject updated CSS for all components into live instances."
  []
  (refresh-component-styles!
   [["x-alert"               x-alert-c/style-text]
    ["x-avatar"              x-avatar-c/style-text]
    ["x-avatar-group"        x-avatar-group-c/style-text]
    ["x-badge"               x-badge-c/style-text]
    ["x-breadcrumbs"         x-breadcrumbs-c/style-text]
    ["x-button"              x-button-c/style-text]
    ["x-cancel-dialogue"     x-cancel-dialogue-c/style-text]
    ["x-card"                x-card-c/style-text]
    ["x-chart"               x-chart-c/style-text]
    ["x-checkbox"            x-checkbox-c/style-text]
    ["x-chip"                x-chip-c/style-text]
    ["x-collapse"            x-collapse-c/style-text]
    ["x-command-palette"     x-command-palette-c/style-text]
    ["x-container"           x-container-c/style-text]
    ["x-context-menu"        x-context-menu-c/host-style-text]
    ["x-copy"                x-copy-c/style-text]
    ["x-currency-field"      x-currency-field-c/style-text]
    ["x-date-picker"         x-date-picker-c/style-text]
    ["x-divider"             x-divider-c/style-text]
    ["x-drawer"              x-drawer-c/style-text]
    ["x-dropdown"            x-dropdown-c/style-text]
    ["x-fieldset"            x-fieldset-c/style-text]
    ["x-file-download"       x-file-download-c/style-text]
    ["x-form"                x-form-c/style-text]
    ["x-form-field"          x-form-field-c/style-text]
    ["x-gaussian-blur"       x-gaussian-blur-c/style-text]
    ["x-grid"                x-grid-c/style-text]
    ["x-kinetic-typography"  x-kinetic-typography-c/style-text]
    ["x-menu"                x-menu-c/style-text]
    ["x-menu-item"           x-menu-item-c/style-text]
    ["x-modal"               x-modal-c/style-text]
    ["x-navbar"              x-navbar-c/style-text]
    ["x-notification-center" x-notification-center-c/style-text]
    ["x-organic-divider"     x-organic-divider-c/style-text]
    ["x-organic-shape"       x-organic-shape-c/style-text]
    ["x-pagination"          x-pagination-c/style-text]
    ["x-popover"             x-popover-c/style-text]
    ["x-progress"            x-progress-c/style-text]
    ["x-progress-circle"     x-progress-circle-c/style-text]
    ["x-radio"               x-radio-c/style-text]
    ["x-ripple-effect"       x-ripple-effect-c/style-text]
    ["x-scroll"              x-scroll-c/style-text]
    ["x-scroll-parallax"     x-scroll-parallax-c/style-text]
    ["x-scroll-story"        x-scroll-story-c/style-text]
    ["x-scroll-timeline"     x-scroll-timeline-c/style-text]
    ["x-search-field"        x-search-field-c/style-text]
    ["x-select"              x-select-c/style-text]
    ["x-sidebar"             x-sidebar-c/css-text]
    ["x-skeleton"            x-skeleton-c/style-text]
    ["x-slider"              x-slider-c/style-text]
    ["x-spacer"              x-spacer-c/style-text]
    ["x-spinner"             x-spinner-c/style-text]
    ["x-stat"                x-stat-c/css-text]
    ["x-stepper"             x-stepper-c/style-text]
    ["x-switch"              x-switch-c/style-text]
    ["x-tab"                 x-tab-c/style-text]
    ["x-table"               x-table-c/style-text]
    ["x-table-cell"          x-table-cell-c/style-text]
    ["x-table-row"           x-table-row-c/style-text]
    ["x-tabs"                x-tabs-c/style-text]
    ["x-text-area"           x-text-area-c/style-text]
    ["x-timeline"            x-timeline-c/style-text]
    ["x-timeline-item"       x-timeline-item-c/style-text]
    ["x-toast"               x-toast-c/style-text]
    ["x-toaster"             x-toaster-c/style-text]
    ["x-typography"          x-typography-c/style-text]]))
