"use client";
// x-avatar.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XAvatar as XAvatarElement } from "@vanelsas/baredom/x-avatar";
import { init } from "@vanelsas/baredom/x-avatar";

init();

export interface XAvatarProps {
  initials?: string;
  disabled?: boolean;
  variant?: string;
  alt?: string;
  name?: string;
  src?: string;
  size?: string;
  status?: string;
  shape?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XAvatar = forwardRef<XAvatarElement, XAvatarProps>(
  function XAvatar(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XAvatarElement>(null);

    const setRef = (el: XAvatarElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-avatar ref={setRef} {...rest}>{children}</x-avatar>;
  }
);
