"use client";
// x-avatar-group.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XAvatarGroup as XAvatarGroupElement } from "@vanelsas/baredom/x-avatar-group";
import { init } from "@vanelsas/baredom/x-avatar-group";

init();

export interface XAvatarGroupProps {
  size?: string;
  overlap?: string;
  max?: number;
  direction?: string;
  disabled?: boolean;
  label?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XAvatarGroup = forwardRef<XAvatarGroupElement, XAvatarGroupProps>(
  function XAvatarGroup(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XAvatarGroupElement>(null);

    const setRef = (el: XAvatarGroupElement | null) => {
      (innerRef as React.MutableRefObject<XAvatarGroupElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-avatar-group ref={setRef} {...rest}>{children}</x-avatar-group>;
  }
);
