"use client";
// x-bento-item.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XBentoItem as XBentoItemElement } from "@vanelsas/baredom/x-bento-item";
import { init } from "@vanelsas/baredom/x-bento-item";

init();

export interface XBentoItemProps {
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XBentoItem = forwardRef<XBentoItemElement, XBentoItemProps>(
  function XBentoItem(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XBentoItemElement>(null);

    const setRef = (el: XBentoItemElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-bento-item ref={setRef} {...rest}>{children}</x-bento-item>;
  }
);
