"use client";
// x-breadcrumbs.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XBreadcrumbs as XBreadcrumbsElement } from "@vanelsas/baredom/x-breadcrumbs";
import { init } from "@vanelsas/baredom/x-breadcrumbs";

init();

export interface XBreadcrumbsProps {
  separator?: string;
  size?: string;
  variant?: string;
  wrap?: boolean;
  maxItems?: number;
  itemsBefore?: number;
  itemsAfter?: number;
  disabled?: boolean;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XBreadcrumbs = forwardRef<XBreadcrumbsElement, XBreadcrumbsProps>(
  function XBreadcrumbs(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XBreadcrumbsElement>(null);

    const setRef = (el: XBreadcrumbsElement | null) => {
      (innerRef as React.MutableRefObject<XBreadcrumbsElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-breadcrumbs ref={setRef} {...rest}>{children}</x-breadcrumbs>;
  }
);
