"use client";
// x-cancel-dialogue.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCancelDialogue as XCancelDialogueElement } from "@vanelsas/baredom/x-cancel-dialogue";
import { init } from "@vanelsas/baredom/x-cancel-dialogue";

init();

export interface XCancelDialogueProps {
  open?: boolean;
  disabled?: boolean;
  headline?: string;
  message?: string;
  confirmText?: string;
  cancelText?: string;
  danger?: boolean;
  onCancelRequest?: (e: CustomEvent<{ reason: string }>) => void;
  onCancel?: (e: CustomEvent<{}>) => void;
  onConfirmRequest?: (e: CustomEvent<{}>) => void;
  onConfirm?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCancelDialogue = forwardRef<XCancelDialogueElement, XCancelDialogueProps>(
  function XCancelDialogue(props, forwardedRef) {
    const { onCancelRequest, onCancel, onConfirmRequest, onConfirm, children, ...rest } = props;
    const innerRef = useRef<XCancelDialogueElement>(null);

    const setRef = (el: XCancelDialogueElement | null) => {
      (innerRef as React.MutableRefObject<XCancelDialogueElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onCancelRequest) {
        el.addEventListener("x-cancel-dialogue-cancel-request", onCancelRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-cancel-request", onCancelRequest as EventListener));
      }
      if (onCancel) {
        el.addEventListener("x-cancel-dialogue-cancel", onCancel as EventListener);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-cancel", onCancel as EventListener));
      }
      if (onConfirmRequest) {
        el.addEventListener("x-cancel-dialogue-confirm-request", onConfirmRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-confirm-request", onConfirmRequest as EventListener));
      }
      if (onConfirm) {
        el.addEventListener("x-cancel-dialogue-confirm", onConfirm as EventListener);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-confirm", onConfirm as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onCancelRequest, onCancel, onConfirmRequest, onConfirm]);

    return <x-cancel-dialogue ref={setRef} {...rest}>{children}</x-cancel-dialogue>;
  }
);
