"use client";
// x-chart.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XChart as XChartElement } from "@vanelsas/baredom/x-chart";
import { init } from "@vanelsas/baredom/x-chart";

init();

export interface XChartProps {
  selected?: string;
  disabled?: boolean;
  axes?: boolean;
  grid?: boolean;
  cursor?: string;
  type?: string;
  loading?: boolean;
  padding?: number;
  tooltip?: boolean;
  height?: number;
  data?: any;
  onSelect?: (e: CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>) => void;
  onHover?: (e: CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XChart = forwardRef<XChartElement, XChartProps>(
  function XChart(props, forwardedRef) {
    const { onSelect, onHover, children, ...rest } = props;
    const innerRef = useRef<XChartElement>(null);

    const setRef = (el: XChartElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onSelect) {
        el.addEventListener("x-chart-select", onSelect as EventListener);
        cleanup.push(() => el.removeEventListener("x-chart-select", onSelect as EventListener));
      }
      if (onHover) {
        el.addEventListener("x-chart-hover", onHover as EventListener);
        cleanup.push(() => el.removeEventListener("x-chart-hover", onHover as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onSelect, onHover]);

    return <x-chart ref={setRef} {...rest}>{children}</x-chart>;
  }
);
