"use client";
// x-checkbox.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCheckbox as XCheckboxElement } from "@vanelsas/baredom/x-checkbox";
import { init } from "@vanelsas/baredom/x-checkbox";

init();

export interface XCheckboxProps {
  checked?: boolean;
  indeterminate?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  name?: string;
  value?: string;
  defaultChecked?: boolean;
  onChangeRequest?: (e: CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>) => void;
  onChange?: (e: CustomEvent<{ value: string; checked: boolean }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCheckbox = forwardRef<XCheckboxElement, XCheckboxProps>(
  function XCheckbox(props, forwardedRef) {
    const { checked, defaultChecked, onChangeRequest, onChange, children, ...rest } = props;
    const innerRef = useRef<XCheckboxElement>(null);

    const setRef = (el: XCheckboxElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    // Controlled mode: intercept change-request when checked is provided
    useEffect(() => {
      const el = innerRef.current;
      if (!el || checked === undefined) return;
      const handler = (e: Event) => { e.preventDefault(); };
      el.addEventListener("x-checkbox-change-request", handler);
      return () => el.removeEventListener("x-checkbox-change-request", handler);
    }, [checked]);

    // Set initial value from defaultChecked (uncontrolled mode)
    useEffect(() => {
      const el = innerRef.current;
      if (!el || checked !== undefined || defaultChecked === undefined) return;
      if (defaultChecked) el.setAttribute("checked", "");
      else el.removeAttribute("checked");
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChangeRequest) {
        el.addEventListener("x-checkbox-change-request", onChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-checkbox-change-request", onChangeRequest as EventListener));
      }
      if (onChange) {
        el.addEventListener("x-checkbox-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-checkbox-change", onChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChangeRequest, onChange]);

    return <x-checkbox ref={setRef} checked={checked} {...rest}>{children}</x-checkbox>;
  }
);
