"use client";
// x-code.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCode as XCodeElement } from "@vanelsas/baredom/x-code";
import { init } from "@vanelsas/baredom/x-code";

init();

export interface XCodeProps {
  language?: string;
  filename?: string;
  showCopy?: boolean;
  lineNumbers?: boolean;
  wrap?: boolean;
  maxLines?: number;
  expanded?: boolean;
  code?: string;
  onCopy?: (e: CustomEvent<{ code: string }>) => void;
  onToggle?: (e: CustomEvent<{ expanded: boolean }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCode = forwardRef<XCodeElement, XCodeProps>(
  function XCode(props, forwardedRef) {
    const { onCopy, onToggle, children, ...rest } = props;
    const innerRef = useRef<XCodeElement>(null);

    const setRef = (el: XCodeElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onCopy) {
        el.addEventListener("x-code-copy", onCopy as EventListener);
        cleanup.push(() => el.removeEventListener("x-code-copy", onCopy as EventListener));
      }
      if (onToggle) {
        el.addEventListener("x-code-toggle", onToggle as EventListener);
        cleanup.push(() => el.removeEventListener("x-code-toggle", onToggle as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onCopy, onToggle]);

    return <x-code ref={setRef} {...rest}>{children}</x-code>;
  }
);
