"use client";
// x-context-menu.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XContextMenu as XContextMenuElement } from "@vanelsas/baredom/x-context-menu";
import { init } from "@vanelsas/baredom/x-context-menu";

init();

export interface XContextMenuProps {
  open?: boolean;
  disabled?: boolean;
  placement?: string;
  offset?: number;
  zIndex?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XContextMenu = forwardRef<XContextMenuElement, XContextMenuProps>(
  function XContextMenu(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XContextMenuElement>(null);

    const setRef = (el: XContextMenuElement | null) => {
      (innerRef as React.MutableRefObject<XContextMenuElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-context-menu ref={setRef} {...rest}>{children}</x-context-menu>;
  }
);
