"use client";
// x-combobox.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCombobox as XComboboxElement } from "@vanelsas/baredom/x-combobox";
import { init } from "@vanelsas/baredom/x-combobox";

init();

export interface XComboboxProps {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  required?: boolean;
  open?: boolean;
  placement?: string;
  onChange?: (e: CustomEvent<{ value: string; label: string }>) => void;
  onInput?: (e: CustomEvent<{ query: string }>) => void;
  onToggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCombobox = forwardRef<XComboboxElement, XComboboxProps>(
  function XCombobox(props, forwardedRef) {
    const { onChange, onInput, onToggle, children, ...rest } = props;
    const innerRef = useRef<XComboboxElement>(null);

    const setRef = (el: XComboboxElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChange) {
        el.addEventListener("x-combobox-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-change", onChange as EventListener));
      }
      if (onInput) {
        el.addEventListener("x-combobox-input", onInput as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-input", onInput as EventListener));
      }
      if (onToggle) {
        el.addEventListener("x-combobox-toggle", onToggle as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-toggle", onToggle as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChange, onInput, onToggle]);

    return <x-combobox ref={setRef} {...rest}>{children}</x-combobox>;
  }
);
