"use client";
// x-context-menu.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XContextMenu as XContextMenuElement } from "@vanelsas/baredom/x-context-menu";
import { init } from "@vanelsas/baredom/x-context-menu";

init();

export interface XContextMenuProps {
  open?: boolean;
  disabled?: boolean;
  placement?: string;
  offset?: number;
  zIndex?: number;
  onOpenRequest?: (e: CustomEvent<{ reason: string }>) => void;
  onOpen?: (e: CustomEvent<{ reason: string }>) => void;
  onCloseRequest?: (e: CustomEvent<{ reason: string }>) => void;
  onClose?: (e: CustomEvent<{ reason: string }>) => void;
  onSelect?: (e: CustomEvent<{ item: Record<string, any> }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XContextMenu = forwardRef<XContextMenuElement, XContextMenuProps>(
  function XContextMenu(props, forwardedRef) {
    const { onOpenRequest, onOpen, onCloseRequest, onClose, onSelect, children, ...rest } = props;
    const innerRef = useRef<XContextMenuElement>(null);

    const setRef = (el: XContextMenuElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onOpenRequest) {
        el.addEventListener("x-context-menu-open-request", onOpenRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-context-menu-open-request", onOpenRequest as EventListener));
      }
      if (onOpen) {
        el.addEventListener("x-context-menu-open", onOpen as EventListener);
        cleanup.push(() => el.removeEventListener("x-context-menu-open", onOpen as EventListener));
      }
      if (onCloseRequest) {
        el.addEventListener("x-context-menu-close-request", onCloseRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-context-menu-close-request", onCloseRequest as EventListener));
      }
      if (onClose) {
        el.addEventListener("x-context-menu-close", onClose as EventListener);
        cleanup.push(() => el.removeEventListener("x-context-menu-close", onClose as EventListener));
      }
      if (onSelect) {
        el.addEventListener("x-context-menu-select", onSelect as EventListener);
        cleanup.push(() => el.removeEventListener("x-context-menu-select", onSelect as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onOpenRequest, onOpen, onCloseRequest, onClose, onSelect]);

    return <x-context-menu ref={setRef} {...rest}>{children}</x-context-menu>;
  }
);
