"use client";
// x-copy.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCopy as XCopyElement } from "@vanelsas/baredom/x-copy";
import { init } from "@vanelsas/baredom/x-copy";

init();

export interface XCopyProps {
  errorMessage?: string;
  disabled?: boolean;
  textValue?: string;
  mode?: string;
  fromAttr?: string;
  tooltipMs?: number;
  hotkey?: string;
  from?: string;
  showTooltip?: boolean;
  successMessage?: string;
  text?: string;
  onRequest?: (e: CustomEvent<{ text: string; mode: string; from: string; fromAttr: string }>) => void;
  onSuccess?: (e: CustomEvent<{ text: string }>) => void;
  onError?: (e: CustomEvent<{ error: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCopy = forwardRef<XCopyElement, XCopyProps>(
  function XCopy(props, forwardedRef) {
    const { onRequest, onSuccess, onError, children, ...rest } = props;
    const innerRef = useRef<XCopyElement>(null);

    const setRef = (el: XCopyElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onRequest) {
        el.addEventListener("x-copy-request", onRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-copy-request", onRequest as EventListener));
      }
      if (onSuccess) {
        el.addEventListener("x-copy-success", onSuccess as EventListener);
        cleanup.push(() => el.removeEventListener("x-copy-success", onSuccess as EventListener));
      }
      if (onError) {
        el.addEventListener("x-copy-error", onError as EventListener);
        cleanup.push(() => el.removeEventListener("x-copy-error", onError as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onRequest, onSuccess, onError]);

    return <x-copy ref={setRef} {...rest}>{children}</x-copy>;
  }
);
