"use client";
// x-combobox.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCombobox as XComboboxElement } from "@vanelsas/baredom/x-combobox";
import { init } from "@vanelsas/baredom/x-combobox";

init();

export interface XComboboxProps {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  required?: boolean;
  open?: boolean;
  placement?: string;
  defaultValue?: string;
  onChangeRequest?: (e: CustomEvent<{ value: string; label: string; previousValue: string }>) => void;
  onChange?: (e: CustomEvent<{ value: string; label: string }>) => void;
  onInput?: (e: CustomEvent<{ query: string }>) => void;
  onToggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCombobox = forwardRef<XComboboxElement, XComboboxProps>(
  function XCombobox(props, forwardedRef) {
    const { value, defaultValue, onChangeRequest, onChange, onInput, onToggle, children, ...rest } = props;
    const innerRef = useRef<XComboboxElement>(null);

    const setRef = (el: XComboboxElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    // Controlled mode: intercept change-request when value is provided
    useEffect(() => {
      const el = innerRef.current;
      if (!el || value === undefined) return;
      const handler = (e: Event) => { e.preventDefault(); };
      el.addEventListener("x-combobox-change-request", handler);
      return () => el.removeEventListener("x-combobox-change-request", handler);
    }, [value]);

    // Set initial value from defaultValue (uncontrolled mode)
    useEffect(() => {
      const el = innerRef.current;
      if (!el || value !== undefined || defaultValue === undefined) return;
      el.setAttribute("value", String(defaultValue));
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChangeRequest) {
        el.addEventListener("x-combobox-change-request", onChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-change-request", onChangeRequest as EventListener));
      }
      if (onChange) {
        el.addEventListener("x-combobox-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-change", onChange as EventListener));
      }
      if (onInput) {
        el.addEventListener("x-combobox-input", onInput as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-input", onInput as EventListener));
      }
      if (onToggle) {
        el.addEventListener("x-combobox-toggle", onToggle as EventListener);
        cleanup.push(() => el.removeEventListener("x-combobox-toggle", onToggle as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChangeRequest, onChange, onInput, onToggle]);

    return <x-combobox ref={setRef} value={value} {...rest}>{children}</x-combobox>;
  }
);
