"use client";
// x-currency-field.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XCurrencyField as XCurrencyFieldElement } from "@vanelsas/baredom/x-currency-field";
import { init } from "@vanelsas/baredom/x-currency-field";

init();

export interface XCurrencyFieldProps {
  min?: string;
  placeholder?: string;
  disabled?: boolean;
  locale?: string;
  name?: string;
  value?: string;
  hint?: string;
  currency?: string;
  readOnly?: boolean;
  max?: string;
  label?: string;
  error?: string;
  required?: boolean;
  defaultValue?: string;
  onChangeRequest?: (e: CustomEvent<{ name: string; value: string; previousValue: string }>) => void;
  onInput?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XCurrencyField = forwardRef<XCurrencyFieldElement, XCurrencyFieldProps>(
  function XCurrencyField(props, forwardedRef) {
    const { value, defaultValue, onChangeRequest, onInput, onChange, children, ...rest } = props;
    const innerRef = useRef<XCurrencyFieldElement>(null);

    const setRef = (el: XCurrencyFieldElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    // Controlled mode: intercept change-request when value is provided
    useEffect(() => {
      const el = innerRef.current;
      if (!el || value === undefined) return;
      const handler = (e: Event) => { e.preventDefault(); };
      el.addEventListener("x-currency-field-change-request", handler);
      return () => el.removeEventListener("x-currency-field-change-request", handler);
    }, [value]);

    // Set initial value from defaultValue (uncontrolled mode)
    useEffect(() => {
      const el = innerRef.current;
      if (!el || value !== undefined || defaultValue === undefined) return;
      el.setAttribute("value", String(defaultValue));
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChangeRequest) {
        el.addEventListener("x-currency-field-change-request", onChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-currency-field-change-request", onChangeRequest as EventListener));
      }
      if (onInput) {
        el.addEventListener("x-currency-field-input", onInput as EventListener);
        cleanup.push(() => el.removeEventListener("x-currency-field-input", onInput as EventListener));
      }
      if (onChange) {
        el.addEventListener("x-currency-field-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-currency-field-change", onChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChangeRequest, onInput, onChange]);

    return <x-currency-field ref={setRef} value={value} {...rest}>{children}</x-currency-field>;
  }
);
