"use client";
// x-date-picker.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XDatePicker as XDatePickerElement } from "@vanelsas/baredom/x-date-picker";
import { init } from "@vanelsas/baredom/x-date-picker";

init();

export interface XDatePickerProps {
  mode?: string;
  value?: string;
  start?: string;
  end?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  open?: boolean;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XDatePicker = forwardRef<XDatePickerElement, XDatePickerProps>(
  function XDatePicker(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XDatePickerElement>(null);

    const setRef = (el: XDatePickerElement | null) => {
      (innerRef as React.MutableRefObject<XDatePickerElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-date-picker ref={setRef} {...rest}>{children}</x-date-picker>;
  }
);
