"use client";
// x-drag-panel.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XDragPanel as XDragPanelElement } from "@vanelsas/baredom/x-drag-panel";
import { init } from "@vanelsas/baredom/x-drag-panel";

init();

export interface XDragPanelProps {
  kind?: string;
  value?: string;
  label?: string;
  grab?: string;
  autoScroll?: string;
  disabled?: boolean;
  pending?: boolean;
  onDragStart?: (e: CustomEvent<{ kind: string; value: string }>) => void;
  onDragCancel?: (e: CustomEvent<{ kind: string; value: string; reason: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XDragPanel = forwardRef<XDragPanelElement, XDragPanelProps>(
  function XDragPanel(props, forwardedRef) {
    const { onDragStart, onDragCancel, children, ...rest } = props;
    const innerRef = useRef<XDragPanelElement>(null);

    const setRef = (el: XDragPanelElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onDragStart) {
        el.addEventListener("x-drag-panel-drag-start", onDragStart as EventListener);
        cleanup.push(() => el.removeEventListener("x-drag-panel-drag-start", onDragStart as EventListener));
      }
      if (onDragCancel) {
        el.addEventListener("x-drag-panel-drag-cancel", onDragCancel as EventListener);
        cleanup.push(() => el.removeEventListener("x-drag-panel-drag-cancel", onDragCancel as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onDragStart, onDragCancel]);

    return <x-drag-panel ref={setRef} {...rest}>{children}</x-drag-panel>;
  }
);
