"use client";
// x-fieldset.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XFieldset as XFieldsetElement } from "@vanelsas/baredom/x-fieldset";
import { init } from "@vanelsas/baredom/x-fieldset";

init();

export interface XFieldsetProps {
  legend?: string;
  disabled?: boolean;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XFieldset = forwardRef<XFieldsetElement, XFieldsetProps>(
  function XFieldset(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XFieldsetElement>(null);

    const setRef = (el: XFieldsetElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-fieldset ref={setRef} {...rest}>{children}</x-fieldset>;
  }
);
