"use client";
// x-form.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XForm as XFormElement } from "@vanelsas/baredom/x-form";
import { init } from "@vanelsas/baredom/x-form";

init();

export interface XFormProps {
  loading?: boolean;
  novalidate?: boolean;
  autocomplete?: string;
  onSubmit?: (e: CustomEvent<{ values: Record<string, any> }>) => void;
  onReset?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XForm = forwardRef<XFormElement, XFormProps>(
  function XForm(props, forwardedRef) {
    const { onSubmit, onReset, children, ...rest } = props;
    const innerRef = useRef<XFormElement>(null);

    const setRef = (el: XFormElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onSubmit) {
        el.addEventListener("x-form-submit", onSubmit as EventListener);
        cleanup.push(() => el.removeEventListener("x-form-submit", onSubmit as EventListener));
      }
      if (onReset) {
        el.addEventListener("x-form-reset", onReset as EventListener);
        cleanup.push(() => el.removeEventListener("x-form-reset", onReset as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onSubmit, onReset]);

    return <x-form ref={setRef} {...rest}>{children}</x-form>;
  }
);
