"use client";
// x-form-field.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XFormField as XFormFieldElement } from "@vanelsas/baredom/x-form-field";
import { init } from "@vanelsas/baredom/x-form-field";

init();

export interface XFormFieldProps {
  placeholder?: string;
  disabled?: boolean;
  name?: string;
  value?: string;
  type?: string;
  hint?: string;
  readOnly?: boolean;
  label?: string;
  error?: string;
  autocomplete?: string;
  required?: boolean;
  onChangeRequest?: (e: CustomEvent<{ name: string; value: string; previousValue: string }>) => void;
  onInput?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XFormField = forwardRef<XFormFieldElement, XFormFieldProps>(
  function XFormField(props, forwardedRef) {
    const { onChangeRequest, onInput, onChange, children, ...rest } = props;
    const innerRef = useRef<XFormFieldElement>(null);

    const setRef = (el: XFormFieldElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChangeRequest) {
        el.addEventListener("x-form-field-change-request", onChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-form-field-change-request", onChangeRequest as EventListener));
      }
      if (onInput) {
        el.addEventListener("x-form-field-input", onInput as EventListener);
        cleanup.push(() => el.removeEventListener("x-form-field-input", onInput as EventListener));
      }
      if (onChange) {
        el.addEventListener("x-form-field-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-form-field-change", onChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChangeRequest, onInput, onChange]);

    return <x-form-field ref={setRef} {...rest}>{children}</x-form-field>;
  }
);
