"use client";
// x-i18n.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XI18n as XI18nElement } from "@vanelsas/baredom/x-i18n";
import { init } from "@vanelsas/baredom/x-i18n";

init();

export interface XI18nProps {
  key?: string;
  params?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XI18n = forwardRef<XI18nElement, XI18nProps>(
  function XI18n(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XI18nElement>(null);

    const setRef = (el: XI18nElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-i18n ref={setRef} {...rest}>{children}</x-i18n>;
  }
);
