"use client";
// x-kbd.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XKbd as XKbdElement } from "@vanelsas/baredom/x-kbd";
import { init } from "@vanelsas/baredom/x-kbd";

init();

export interface XKbdProps {
  keys?: string;
  separator?: string;
  size?: string;
  platform?: string;
  label?: string;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XKbd = forwardRef<XKbdElement, XKbdProps>(
  function XKbd(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XKbdElement>(null);

    const setRef = (el: XKbdElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-kbd ref={setRef} {...rest}>{children}</x-kbd>;
  }
);
