"use client";
// x-kinetic-font.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XKineticFont as XKineticFontElement } from "@vanelsas/baredom/x-kinetic-font";
import { init } from "@vanelsas/baredom/x-kinetic-font";

init();

export interface XKineticFontProps {
  mass?: number;
  tension?: number;
  mode?: string;
  perChar?: boolean;
  radius?: number;
  intensity?: number;
  fontFamily?: string;
  friction?: number;
  trigger?: string;
  text?: string;
  onSpringActivate?: (e: CustomEvent<{}>) => void;
  onSpringSettle?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XKineticFont = forwardRef<XKineticFontElement, XKineticFontProps>(
  function XKineticFont(props, forwardedRef) {
    const { onSpringActivate, onSpringSettle, children, ...rest } = props;
    const innerRef = useRef<XKineticFontElement>(null);

    const setRef = (el: XKineticFontElement | null) => {
      (innerRef as React.MutableRefObject<XKineticFontElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onSpringActivate) {
        el.addEventListener("x-kinetic-font-spring-activate", onSpringActivate as EventListener);
        cleanup.push(() => el.removeEventListener("x-kinetic-font-spring-activate", onSpringActivate as EventListener));
      }
      if (onSpringSettle) {
        el.addEventListener("x-kinetic-font-spring-settle", onSpringSettle as EventListener);
        cleanup.push(() => el.removeEventListener("x-kinetic-font-spring-settle", onSpringSettle as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onSpringActivate, onSpringSettle]);

    return <x-kinetic-font ref={setRef} {...rest}>{children}</x-kinetic-font>;
  }
);
