"use client";
// x-liquid-glass.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XLiquidGlass as XLiquidGlassElement } from "@vanelsas/baredom/x-liquid-glass";
import { init } from "@vanelsas/baredom/x-liquid-glass";

init();

export interface XLiquidGlassProps {
  frost?: number;
  goo?: number;
  amplitude?: number;
  specularSize?: number;
  disabled?: boolean;
  speed?: number;
  mode?: string;
  specular?: boolean;
  tint?: string;
  color2?: string;
  blur?: number;
  blobs?: number;
  color1?: string;
  specularIntensity?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XLiquidGlass = forwardRef<XLiquidGlassElement, XLiquidGlassProps>(
  function XLiquidGlass(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XLiquidGlassElement>(null);

    const setRef = (el: XLiquidGlassElement | null) => {
      (innerRef as React.MutableRefObject<XLiquidGlassElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-liquid-glass ref={setRef} {...rest}>{children}</x-liquid-glass>;
  }
);
