"use client";
// x-metaball-cursor.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XMetaballCursor as XMetaballCursorElement } from "@vanelsas/baredom/x-metaball-cursor";
import { init } from "@vanelsas/baredom/x-metaball-cursor";

init();

export interface XMetaballCursorProps {
  color?: string;
  blobSize?: number;
  noiseIntensity?: number;
  palette?: string;
  noiseScale?: number;
  noise?: boolean;
  threshold?: string;
  blur?: number;
  noiseSpeed?: number;
  blobCount?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XMetaballCursor = forwardRef<XMetaballCursorElement, XMetaballCursorProps>(
  function XMetaballCursor(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XMetaballCursorElement>(null);

    const setRef = (el: XMetaballCursorElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-metaball-cursor ref={setRef} {...rest}>{children}</x-metaball-cursor>;
  }
);
