"use client";
// x-menu.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XMenu as XMenuElement } from "@vanelsas/baredom/x-menu";
import { init } from "@vanelsas/baredom/x-menu";

init();

export interface XMenuProps {
  open?: boolean;
  placement?: string;
  label?: string;
  onOpen?: (e: CustomEvent<{}>) => void;
  onClose?: (e: CustomEvent<{}>) => void;
  onSelect?: (e: CustomEvent<{ value: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XMenu = forwardRef<XMenuElement, XMenuProps>(
  function XMenu(props, forwardedRef) {
    const { onOpen, onClose, onSelect, children, ...rest } = props;
    const innerRef = useRef<XMenuElement>(null);

    const setRef = (el: XMenuElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onOpen) {
        el.addEventListener("x-menu-open", onOpen as EventListener);
        cleanup.push(() => el.removeEventListener("x-menu-open", onOpen as EventListener));
      }
      if (onClose) {
        el.addEventListener("x-menu-close", onClose as EventListener);
        cleanup.push(() => el.removeEventListener("x-menu-close", onClose as EventListener));
      }
      if (onSelect) {
        el.addEventListener("x-menu-select", onSelect as EventListener);
        cleanup.push(() => el.removeEventListener("x-menu-select", onSelect as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onOpen, onClose, onSelect]);

    return <x-menu ref={setRef} {...rest}>{children}</x-menu>;
  }
);
