"use client";
// x-modal.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XModal as XModalElement } from "@vanelsas/baredom/x-modal";
import { init } from "@vanelsas/baredom/x-modal";

init();

export interface XModalProps {
  open?: boolean;
  size?: string;
  label?: string;
  onToggle?: (e: CustomEvent<{ open: boolean }>) => void;
  onDismiss?: (e: CustomEvent<{ reason: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XModal = forwardRef<XModalElement, XModalProps>(
  function XModal(props, forwardedRef) {
    const { onToggle, onDismiss, children, ...rest } = props;
    const innerRef = useRef<XModalElement>(null);

    const setRef = (el: XModalElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onToggle) {
        el.addEventListener("x-modal-toggle", onToggle as EventListener);
        cleanup.push(() => el.removeEventListener("x-modal-toggle", onToggle as EventListener));
      }
      if (onDismiss) {
        el.addEventListener("x-modal-dismiss", onDismiss as EventListener);
        cleanup.push(() => el.removeEventListener("x-modal-dismiss", onDismiss as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onToggle, onDismiss]);

    return <x-modal ref={setRef} {...rest}>{children}</x-modal>;
  }
);
