"use client";
// x-multi-combobox.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XMultiCombobox as XMultiComboboxElement } from "@vanelsas/baredom/x-multi-combobox";
import { init } from "@vanelsas/baredom/x-multi-combobox";

init();

export interface XMultiComboboxProps {
  open?: boolean;
  placeholder?: string;
  disabled?: boolean;
  name?: string;
  value?: string;
  max?: number;
  error?: string;
  placement?: string;
  required?: boolean;
  onChangeRequest?: (e: CustomEvent<{ value: any; action: string; item: string }>) => void;
  onChange?: (e: CustomEvent<{ value: any }>) => void;
  onInput?: (e: CustomEvent<{ query: string }>) => void;
  onToggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XMultiCombobox = forwardRef<XMultiComboboxElement, XMultiComboboxProps>(
  function XMultiCombobox(props, forwardedRef) {
    const { onChangeRequest, onChange, onInput, onToggle, children, ...rest } = props;
    const innerRef = useRef<XMultiComboboxElement>(null);

    const setRef = (el: XMultiComboboxElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChangeRequest) {
        el.addEventListener("x-multi-combobox-change-request", onChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("x-multi-combobox-change-request", onChangeRequest as EventListener));
      }
      if (onChange) {
        el.addEventListener("x-multi-combobox-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-multi-combobox-change", onChange as EventListener));
      }
      if (onInput) {
        el.addEventListener("x-multi-combobox-input", onInput as EventListener);
        cleanup.push(() => el.removeEventListener("x-multi-combobox-input", onInput as EventListener));
      }
      if (onToggle) {
        el.addEventListener("x-multi-combobox-toggle", onToggle as EventListener);
        cleanup.push(() => el.removeEventListener("x-multi-combobox-toggle", onToggle as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChangeRequest, onChange, onInput, onToggle]);

    return <x-multi-combobox ref={setRef} {...rest}>{children}</x-multi-combobox>;
  }
);
