"use client";
// x-neural-glow.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XNeuralGlow as XNeuralGlowElement } from "@vanelsas/baredom/x-neural-glow";
import { init } from "@vanelsas/baredom/x-neural-glow";

init();

export interface XNeuralGlowProps {
  colorBackground?: string;
  interactive?: boolean;
  orbCount?: number;
  restRate?: number;
  colorPrimary?: string;
  orbSize?: number;
  opacity?: number;
  colorSecondary?: string;
  pulseSpeed?: number;
  connectionDistance?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XNeuralGlow = forwardRef<XNeuralGlowElement, XNeuralGlowProps>(
  function XNeuralGlow(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XNeuralGlowElement>(null);

    const setRef = (el: XNeuralGlowElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-neural-glow ref={setRef} {...rest}>{children}</x-neural-glow>;
  }
);
