"use client";
// x-notification-center.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XNotificationCenter as XNotificationCenterElement } from "@vanelsas/baredom/x-notification-center";
import { init } from "@vanelsas/baredom/x-notification-center";

init();

export interface XNotificationCenterProps {
  position?: string;
  max?: number;
  onPush?: (e: CustomEvent<{ id: string; count: number }>) => void;
  onDismiss?: (e: CustomEvent<{ id: string; type: string; reason: string; text: string; count: number }>) => void;
  onEmpty?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XNotificationCenter = forwardRef<XNotificationCenterElement, XNotificationCenterProps>(
  function XNotificationCenter(props, forwardedRef) {
    const { onPush, onDismiss, onEmpty, children, ...rest } = props;
    const innerRef = useRef<XNotificationCenterElement>(null);

    const setRef = (el: XNotificationCenterElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onPush) {
        el.addEventListener("x-notification-center-push", onPush as EventListener);
        cleanup.push(() => el.removeEventListener("x-notification-center-push", onPush as EventListener));
      }
      if (onDismiss) {
        el.addEventListener("x-notification-center-dismiss", onDismiss as EventListener);
        cleanup.push(() => el.removeEventListener("x-notification-center-dismiss", onDismiss as EventListener));
      }
      if (onEmpty) {
        el.addEventListener("x-notification-center-empty", onEmpty as EventListener);
        cleanup.push(() => el.removeEventListener("x-notification-center-empty", onEmpty as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onPush, onDismiss, onEmpty]);

    return <x-notification-center ref={setRef} {...rest}>{children}</x-notification-center>;
  }
);
