"use client";
// x-pagination.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XPagination as XPaginationElement } from "@vanelsas/baredom/x-pagination";
import { init } from "@vanelsas/baredom/x-pagination";

init();

export interface XPaginationProps {
  page?: number;
  totalPages?: number;
  siblingCount?: number;
  boundaryCount?: number;
  size?: string;
  disabled?: boolean;
  label?: string;
  onPageChange?: (e: CustomEvent<{ page: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XPagination = forwardRef<XPaginationElement, XPaginationProps>(
  function XPagination(props, forwardedRef) {
    const { onPageChange, children, ...rest } = props;
    const innerRef = useRef<XPaginationElement>(null);

    const setRef = (el: XPaginationElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onPageChange) {
        el.addEventListener("page-change", onPageChange as EventListener);
        cleanup.push(() => el.removeEventListener("page-change", onPageChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onPageChange]);

    return <x-pagination ref={setRef} {...rest}>{children}</x-pagination>;
  }
);
