"use client";
// x-particle-button.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XParticleButton as XParticleButtonElement } from "@vanelsas/baredom/x-particle-button";
import { init } from "@vanelsas/baredom/x-particle-button";

init();

export interface XParticleButtonProps {
  disabled?: boolean;
  loading?: boolean;
  pressed?: boolean;
  onPress?: (e: CustomEvent<{ source: string }>) => void;
  onPressStart?: (e: CustomEvent<{ source: string }>) => void;
  onPressEnd?: (e: CustomEvent<{ source: string }>) => void;
  onHoverStart?: (e: CustomEvent<{}>) => void;
  onHoverEnd?: (e: CustomEvent<{}>) => void;
  onFocusVisible?: (e: CustomEvent<{}>) => void;
  onBurst?: (e: CustomEvent<{ mode: string; pressX: number; pressY: number }>) => void;
  onReform?: (e: CustomEvent<{ mode: string; duration: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XParticleButton = forwardRef<XParticleButtonElement, XParticleButtonProps>(
  function XParticleButton(props, forwardedRef) {
    const { onPress, onPressStart, onPressEnd, onHoverStart, onHoverEnd, onFocusVisible, onBurst, onReform, children, ...rest } = props;
    const innerRef = useRef<XParticleButtonElement>(null);

    const setRef = (el: XParticleButtonElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onPress) {
        el.addEventListener("press", onPress as EventListener);
        cleanup.push(() => el.removeEventListener("press", onPress as EventListener));
      }
      if (onPressStart) {
        el.addEventListener("press-start", onPressStart as EventListener);
        cleanup.push(() => el.removeEventListener("press-start", onPressStart as EventListener));
      }
      if (onPressEnd) {
        el.addEventListener("press-end", onPressEnd as EventListener);
        cleanup.push(() => el.removeEventListener("press-end", onPressEnd as EventListener));
      }
      if (onHoverStart) {
        el.addEventListener("hover-start", onHoverStart as EventListener);
        cleanup.push(() => el.removeEventListener("hover-start", onHoverStart as EventListener));
      }
      if (onHoverEnd) {
        el.addEventListener("hover-end", onHoverEnd as EventListener);
        cleanup.push(() => el.removeEventListener("hover-end", onHoverEnd as EventListener));
      }
      if (onFocusVisible) {
        el.addEventListener("focus-visible", onFocusVisible as EventListener);
        cleanup.push(() => el.removeEventListener("focus-visible", onFocusVisible as EventListener));
      }
      if (onBurst) {
        el.addEventListener("burst", onBurst as EventListener);
        cleanup.push(() => el.removeEventListener("burst", onBurst as EventListener));
      }
      if (onReform) {
        el.addEventListener("reform", onReform as EventListener);
        cleanup.push(() => el.removeEventListener("reform", onReform as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onPress, onPressStart, onPressEnd, onHoverStart, onHoverEnd, onFocusVisible, onBurst, onReform]);

    return <x-particle-button ref={setRef} {...rest}>{children}</x-particle-button>;
  }
);
