"use client";
// x-progress-circle.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XProgressCircle as XProgressCircleElement } from "@vanelsas/baredom/x-progress-circle";
import { init } from "@vanelsas/baredom/x-progress-circle";

init();

export interface XProgressCircleProps {
  value?: string;
  max?: string;
  indeterminate?: boolean;
  showValue?: boolean;
  onComplete?: (e: CustomEvent<{ value: number; max: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XProgressCircle = forwardRef<XProgressCircleElement, XProgressCircleProps>(
  function XProgressCircle(props, forwardedRef) {
    const { onComplete, children, ...rest } = props;
    const innerRef = useRef<XProgressCircleElement>(null);

    const setRef = (el: XProgressCircleElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onComplete) {
        el.addEventListener("x-progress-circle-complete", onComplete as EventListener);
        cleanup.push(() => el.removeEventListener("x-progress-circle-complete", onComplete as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onComplete]);

    return <x-progress-circle ref={setRef} {...rest}>{children}</x-progress-circle>;
  }
);
