"use client";
// x-proximity-list.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XProximityList as XProximityListElement } from "@vanelsas/baredom/x-proximity-list";
import { init } from "@vanelsas/baredom/x-proximity-list";

init();

export interface XProximityListProps {
  direction?: string;
  radius?: number;
  maxScale?: number;
  lift?: number;
  gap?: number;
  disabled?: boolean;
  onSelect?: (e: CustomEvent<{ index: number; item: any; source: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XProximityList = forwardRef<XProximityListElement, XProximityListProps>(
  function XProximityList(props, forwardedRef) {
    const { onSelect, children, ...rest } = props;
    const innerRef = useRef<XProximityListElement>(null);

    const setRef = (el: XProximityListElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onSelect) {
        el.addEventListener("x-proximity-list-select", onSelect as EventListener);
        cleanup.push(() => el.removeEventListener("x-proximity-list-select", onSelect as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onSelect]);

    return <x-proximity-list ref={setRef} {...rest}>{children}</x-proximity-list>;
  }
);
