"use client";
// x-scroll-stack.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XScrollStack as XScrollStackElement } from "@vanelsas/baredom/x-scroll-stack";
import { init } from "@vanelsas/baredom/x-scroll-stack";

init();

export interface XScrollStackProps {
  peek?: number;
  rotation?: number;
  scrollDistance?: number;
  align?: string;
  disabled?: boolean;
  onChange?: (e: CustomEvent<{ stackedCount: number; totalCount: number; progress: number }>) => void;
  onProgress?: (e: CustomEvent<{ progress: number; stackedCount: number; totalCount: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XScrollStack = forwardRef<XScrollStackElement, XScrollStackProps>(
  function XScrollStack(props, forwardedRef) {
    const { onChange, onProgress, children, ...rest } = props;
    const innerRef = useRef<XScrollStackElement>(null);

    const setRef = (el: XScrollStackElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChange) {
        el.addEventListener("x-scroll-stack-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-stack-change", onChange as EventListener));
      }
      if (onProgress) {
        el.addEventListener("x-scroll-stack-progress", onProgress as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-stack-progress", onProgress as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChange, onProgress]);

    return <x-scroll-stack ref={setRef} {...rest}>{children}</x-scroll-stack>;
  }
);
