"use client";
// x-scroll.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XScroll as XScrollElement } from "@vanelsas/baredom/x-scroll";
import { init } from "@vanelsas/baredom/x-scroll";

init();

export interface XScrollProps {
  disabled?: boolean;
  showIndicators?: boolean;
  snap?: string;
  activeIndex?: number;
  mode?: string;
  showControls?: boolean;
  loop?: boolean;
  label?: string;
  gap?: number;
  autoPlay?: boolean;
  interval?: number;
  onChange?: (e: CustomEvent<{ activeIndex: number; previousIndex: number }>) => void;
  onStart?: (e: CustomEvent<{ direction: string; activeIndex: number }>) => void;
  onEnd?: (e: CustomEvent<{ activeIndex: number }>) => void;
  onLoop?: (e: CustomEvent<{ direction: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XScroll = forwardRef<XScrollElement, XScrollProps>(
  function XScroll(props, forwardedRef) {
    const { onChange, onStart, onEnd, onLoop, children, ...rest } = props;
    const innerRef = useRef<XScrollElement>(null);

    const setRef = (el: XScrollElement | null) => {
      (innerRef as React.MutableRefObject<XScrollElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onChange) {
        el.addEventListener("x-scroll-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-change", onChange as EventListener));
      }
      if (onStart) {
        el.addEventListener("x-scroll-start", onStart as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-start", onStart as EventListener));
      }
      if (onEnd) {
        el.addEventListener("x-scroll-end", onEnd as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-end", onEnd as EventListener));
      }
      if (onLoop) {
        el.addEventListener("x-scroll-loop", onLoop as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-loop", onLoop as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onChange, onStart, onEnd, onLoop]);

    return <x-scroll ref={setRef} {...rest}>{children}</x-scroll>;
  }
);
