"use client";
// x-scroll-timeline.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XScrollTimeline as XScrollTimelineElement } from "@vanelsas/baredom/x-scroll-timeline";
import { init } from "@vanelsas/baredom/x-scroll-timeline";

init();

export interface XScrollTimelineProps {
  autoplayLoop?: boolean;
  autoplaySpeed?: number;
  autoplayIndicator?: boolean;
  disabled?: boolean;
  layout?: string;
  marker?: string;
  threshold?: number;
  label?: string;
  autoplay?: boolean;
  noProgress?: boolean;
  track?: string;
  onEntryChange?: (e: CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>) => void;
  onEntryEnter?: (e: CustomEvent<{ index: number; id: string; progress: number }>) => void;
  onEntryLeave?: (e: CustomEvent<{ index: number; id: string; progress: number }>) => void;
  onProgress?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  onEnter?: (e: CustomEvent<{ progress: number }>) => void;
  onLeave?: (e: CustomEvent<{ progress: number }>) => void;
  onAutoplayPause?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  onAutoplayResume?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XScrollTimeline = forwardRef<XScrollTimelineElement, XScrollTimelineProps>(
  function XScrollTimeline(props, forwardedRef) {
    const { onEntryChange, onEntryEnter, onEntryLeave, onProgress, onEnter, onLeave, onAutoplayPause, onAutoplayResume, children, ...rest } = props;
    const innerRef = useRef<XScrollTimelineElement>(null);

    const setRef = (el: XScrollTimelineElement | null) => {
      (innerRef as React.MutableRefObject<XScrollTimelineElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onEntryChange) {
        el.addEventListener("x-scroll-timeline-entry-change", onEntryChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-change", onEntryChange as EventListener));
      }
      if (onEntryEnter) {
        el.addEventListener("x-scroll-timeline-entry-enter", onEntryEnter as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-enter", onEntryEnter as EventListener));
      }
      if (onEntryLeave) {
        el.addEventListener("x-scroll-timeline-entry-leave", onEntryLeave as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-leave", onEntryLeave as EventListener));
      }
      if (onProgress) {
        el.addEventListener("x-scroll-timeline-progress", onProgress as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-progress", onProgress as EventListener));
      }
      if (onEnter) {
        el.addEventListener("x-scroll-timeline-enter", onEnter as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-enter", onEnter as EventListener));
      }
      if (onLeave) {
        el.addEventListener("x-scroll-timeline-leave", onLeave as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-leave", onLeave as EventListener));
      }
      if (onAutoplayPause) {
        el.addEventListener("x-scroll-timeline-autoplay-pause", onAutoplayPause as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-autoplay-pause", onAutoplayPause as EventListener));
      }
      if (onAutoplayResume) {
        el.addEventListener("x-scroll-timeline-autoplay-resume", onAutoplayResume as EventListener);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-autoplay-resume", onAutoplayResume as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onEntryChange, onEntryEnter, onEntryLeave, onProgress, onEnter, onLeave, onAutoplayPause, onAutoplayResume]);

    return <x-scroll-timeline ref={setRef} {...rest}>{children}</x-scroll-timeline>;
  }
);
