"use client";
// x-select.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XSelect as XSelectElement } from "@vanelsas/baredom/x-select";
import { init } from "@vanelsas/baredom/x-select";

init();

export interface XSelectProps {
  disabled?: boolean;
  required?: boolean;
  value?: string;
  defaultValue?: string;
  onChangeRequest?: (e: CustomEvent<{ value: string; label: string; previousValue: string }>) => void;
  onSelectChange?: (e: CustomEvent<{ value: string; label: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSelect = forwardRef<XSelectElement, XSelectProps>(
  function XSelect(props, forwardedRef) {
    const { value, defaultValue, onChangeRequest, onSelectChange, children, ...rest } = props;
    const innerRef = useRef<XSelectElement>(null);

    const setRef = (el: XSelectElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    // Set initial value from defaultValue (uncontrolled mode)
    useEffect(() => {
      const el = innerRef.current;
      if (!el || value !== undefined || defaultValue === undefined) return;
      el.setAttribute("value", String(defaultValue));
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      {
        const controlled = value !== undefined;
        const wrappedHandler = (e: Event) => {
          if (controlled) e.preventDefault();
          if (onChangeRequest) (onChangeRequest as EventListener)(e);
        };
        el.addEventListener("x-select-change-request", wrappedHandler);
        cleanup.push(() => el.removeEventListener("x-select-change-request", wrappedHandler));
      }
      if (onSelectChange) {
        el.addEventListener("select-change", onSelectChange as EventListener);
        cleanup.push(() => el.removeEventListener("select-change", onSelectChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [value, onChangeRequest, onSelectChange]);

    return <x-select ref={setRef} value={value} {...rest}>{children}</x-select>;
  }
);
