"use client";
// x-skeleton-group.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XSkeletonGroup as XSkeletonGroupElement } from "@vanelsas/baredom/x-skeleton-group";
import { init } from "@vanelsas/baredom/x-skeleton-group";

init();

export interface XSkeletonGroupProps {
  preset?: string;
  animation?: string;
  count?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSkeletonGroup = forwardRef<XSkeletonGroupElement, XSkeletonGroupProps>(
  function XSkeletonGroup(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XSkeletonGroupElement>(null);

    const setRef = (el: XSkeletonGroupElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-skeleton-group ref={setRef} {...rest}>{children}</x-skeleton-group>;
  }
);
