"use client";
// x-spacer.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XSpacer as XSpacerElement } from "@vanelsas/baredom/x-spacer";
import { init } from "@vanelsas/baredom/x-spacer";

init();

export interface XSpacerProps {
  size?: string;
  axis?: string;
  grow?: boolean;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSpacer = forwardRef<XSpacerElement, XSpacerProps>(
  function XSpacer(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XSpacerElement>(null);

    const setRef = (el: XSpacerElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-spacer ref={setRef} {...rest}>{children}</x-spacer>;
  }
);
