"use client";
// x-split-pane.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XSplitPane as XSplitPaneElement } from "@vanelsas/baredom/x-split-pane";
import { init } from "@vanelsas/baredom/x-split-pane";

init();

export interface XSplitPaneProps {
  orientation?: string;
  position?: number;
  minStart?: number;
  minEnd?: number;
  disabled?: boolean;
  dividerLabel?: string;
  onResize?: (e: CustomEvent<{ position: number; orientation: string }>) => void;
  onResizeEnd?: (e: CustomEvent<{ position: number; orientation: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSplitPane = forwardRef<XSplitPaneElement, XSplitPaneProps>(
  function XSplitPane(props, forwardedRef) {
    const { onResize, onResizeEnd, children, ...rest } = props;
    const innerRef = useRef<XSplitPaneElement>(null);

    const setRef = (el: XSplitPaneElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onResize) {
        el.addEventListener("x-split-pane-resize", onResize as EventListener);
        cleanup.push(() => el.removeEventListener("x-split-pane-resize", onResize as EventListener));
      }
      if (onResizeEnd) {
        el.addEventListener("x-split-pane-resize-end", onResizeEnd as EventListener);
        cleanup.push(() => el.removeEventListener("x-split-pane-resize-end", onResizeEnd as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onResize, onResizeEnd]);

    return <x-split-pane ref={setRef} {...rest}>{children}</x-split-pane>;
  }
);
