"use client";
// x-splash.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XSplash as XSplashElement } from "@vanelsas/baredom/x-splash";
import { init } from "@vanelsas/baredom/x-splash";

init();

export interface XSplashProps {
  active?: boolean;
  variant?: string;
  progress?: number;
  spinner?: boolean;
  overlay?: string;
  onHidden?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSplash = forwardRef<XSplashElement, XSplashProps>(
  function XSplash(props, forwardedRef) {
    const { onHidden, children, ...rest } = props;
    const innerRef = useRef<XSplashElement>(null);

    const setRef = (el: XSplashElement | null) => {
      (innerRef as React.MutableRefObject<XSplashElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onHidden) {
        el.addEventListener("x-splash-hidden", onHidden as EventListener);
        cleanup.push(() => el.removeEventListener("x-splash-hidden", onHidden as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onHidden]);

    return <x-splash ref={setRef} {...rest}>{children}</x-splash>;
  }
);
