"use client";
// x-switch.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XSwitch as XSwitchElement } from "@vanelsas/baredom/x-switch";
import { init } from "@vanelsas/baredom/x-switch";

init();

export interface XSwitchProps {
  checked?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  name?: string;
  value?: string;
  defaultChecked?: boolean;
  onChangeRequest?: (e: CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>) => void;
  onChange?: (e: CustomEvent<{ value: string; checked: boolean }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XSwitch = forwardRef<XSwitchElement, XSwitchProps>(
  function XSwitch(props, forwardedRef) {
    const { checked, defaultChecked, onChangeRequest, onChange, children, ...rest } = props;
    const innerRef = useRef<XSwitchElement>(null);

    const setRef = (el: XSwitchElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    // Set initial value from defaultChecked (uncontrolled mode)
    useEffect(() => {
      const el = innerRef.current;
      if (!el || checked !== undefined || defaultChecked === undefined) return;
      if (defaultChecked) el.setAttribute("checked", "");
      else el.removeAttribute("checked");
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      {
        const controlled = checked !== undefined;
        const wrappedHandler = (e: Event) => {
          if (controlled) e.preventDefault();
          if (onChangeRequest) (onChangeRequest as EventListener)(e);
        };
        el.addEventListener("x-switch-change-request", wrappedHandler);
        cleanup.push(() => el.removeEventListener("x-switch-change-request", wrappedHandler));
      }
      if (onChange) {
        el.addEventListener("x-switch-change", onChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-switch-change", onChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [checked, onChangeRequest, onChange]);

    return <x-switch ref={setRef} checked={checked} {...rest}>{children}</x-switch>;
  }
);
