"use client";
// x-tabs.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XTabs as XTabsElement } from "@vanelsas/baredom/x-tabs";
import { init } from "@vanelsas/baredom/x-tabs";

init();

export interface XTabsProps {
  value?: string;
  onValueChangeRequest?: (e: CustomEvent<{ value: string; previousValue: string }>) => void;
  onValueChange?: (e: CustomEvent<{ value: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XTabs = forwardRef<XTabsElement, XTabsProps>(
  function XTabs(props, forwardedRef) {
    const { onValueChangeRequest, onValueChange, children, ...rest } = props;
    const innerRef = useRef<XTabsElement>(null);

    const setRef = (el: XTabsElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onValueChangeRequest) {
        el.addEventListener("value-change-request", onValueChangeRequest as EventListener);
        cleanup.push(() => el.removeEventListener("value-change-request", onValueChangeRequest as EventListener));
      }
      if (onValueChange) {
        el.addEventListener("value-change", onValueChange as EventListener);
        cleanup.push(() => el.removeEventListener("value-change", onValueChange as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onValueChangeRequest, onValueChange]);

    return <x-tabs ref={setRef} {...rest}>{children}</x-tabs>;
  }
);
