"use client";
// x-table.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XTable as XTableElement } from "@vanelsas/baredom/x-table";
import { init } from "@vanelsas/baredom/x-table";

init();

export interface XTableProps {
  columns?: string;
  caption?: string;
  selectable?: string;
  striped?: boolean;
  bordered?: boolean;
  fullWidth?: boolean;
  compact?: boolean;
  rowCount?: number;
  onSort?: (e: CustomEvent<{ colIndex: number; direction: string; previousDirection: string }>) => void;
  onRowSelect?: (e: CustomEvent<{ rowIndex: number; selected: boolean; selectionMode: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XTable = forwardRef<XTableElement, XTableProps>(
  function XTable(props, forwardedRef) {
    const { onSort, onRowSelect, children, ...rest } = props;
    const innerRef = useRef<XTableElement>(null);

    const setRef = (el: XTableElement | null) => {
      (innerRef as React.MutableRefObject<XTableElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onSort) {
        el.addEventListener("x-table-sort", onSort as EventListener);
        cleanup.push(() => el.removeEventListener("x-table-sort", onSort as EventListener));
      }
      if (onRowSelect) {
        el.addEventListener("x-table-row-select", onRowSelect as EventListener);
        cleanup.push(() => el.removeEventListener("x-table-row-select", onRowSelect as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onSort, onRowSelect]);

    return <x-table ref={setRef} {...rest}>{children}</x-table>;
  }
);
