"use client";
// x-tab.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XTab as XTabElement } from "@vanelsas/baredom/x-tab";
import { init } from "@vanelsas/baredom/x-tab";

init();

export interface XTabProps {
  selected?: boolean;
  disabled?: boolean;
  value?: string;
  onTabSelect?: (e: CustomEvent<{ value: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XTab = forwardRef<XTabElement, XTabProps>(
  function XTab(props, forwardedRef) {
    const { onTabSelect, children, ...rest } = props;
    const innerRef = useRef<XTabElement>(null);

    const setRef = (el: XTabElement | null) => {
      (innerRef as React.MutableRefObject<XTabElement | null>).current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onTabSelect) {
        el.addEventListener("tab-select", onTabSelect as EventListener);
        cleanup.push(() => el.removeEventListener("tab-select", onTabSelect as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onTabSelect]);

    return <x-tab ref={setRef} {...rest}>{children}</x-tab>;
  }
);
