"use client";
// x-toast.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XToast as XToastElement } from "@vanelsas/baredom/x-toast";
import { init } from "@vanelsas/baredom/x-toast";

init();

export interface XToastProps {
  type?: string;
  heading?: string;
  message?: string;
  icon?: string;
  dismissible?: boolean;
  disabled?: boolean;
  timeoutMs?: number;
  showProgress?: boolean;
  onDismiss?: (e: CustomEvent<{ type: string; reason: string; heading: string; message: string }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XToast = forwardRef<XToastElement, XToastProps>(
  function XToast(props, forwardedRef) {
    const { onDismiss, children, ...rest } = props;
    const innerRef = useRef<XToastElement>(null);

    const setRef = (el: XToastElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onDismiss) {
        el.addEventListener("x-toast-dismiss", onDismiss as EventListener);
        cleanup.push(() => el.removeEventListener("x-toast-dismiss", onDismiss as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onDismiss]);

    return <x-toast ref={setRef} {...rest}>{children}</x-toast>;
  }
);
