"use client";
// x-tooltip.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XTooltip as XTooltipElement } from "@vanelsas/baredom/x-tooltip";
import { init } from "@vanelsas/baredom/x-tooltip";

init();

export interface XTooltipProps {
  text?: string;
  placement?: string;
  delay?: number;
  disabled?: boolean;
  open?: boolean;
  onShow?: (e: CustomEvent<{}>) => void;
  onHide?: (e: CustomEvent<{}>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XTooltip = forwardRef<XTooltipElement, XTooltipProps>(
  function XTooltip(props, forwardedRef) {
    const { onShow, onHide, children, ...rest } = props;
    const innerRef = useRef<XTooltipElement>(null);

    const setRef = (el: XTooltipElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onShow) {
        el.addEventListener("x-tooltip-show", onShow as EventListener);
        cleanup.push(() => el.removeEventListener("x-tooltip-show", onShow as EventListener));
      }
      if (onHide) {
        el.addEventListener("x-tooltip-hide", onHide as EventListener);
        cleanup.push(() => el.removeEventListener("x-tooltip-hide", onHide as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onShow, onHide]);

    return <x-tooltip ref={setRef} {...rest}>{children}</x-tooltip>;
  }
);
