"use client";
// x-typography.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef } from "react";
import type { XTypography as XTypographyElement } from "@vanelsas/baredom/x-typography";
import { init } from "@vanelsas/baredom/x-typography";

init();

export interface XTypographyProps {
  variant?: string;
  align?: string;
  truncate?: boolean;
  lineClamp?: number;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XTypography = forwardRef<XTypographyElement, XTypographyProps>(
  function XTypography(props, forwardedRef) {
    const { children, ...rest } = props;
    const innerRef = useRef<XTypographyElement>(null);

    const setRef = (el: XTypographyElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    return <x-typography ref={setRef} {...rest}>{children}</x-typography>;
  }
);
