"use client";
// x-welcome-tour.tsx — auto-generated by generate_react.bb, do not edit

import React, { forwardRef, useRef, useEffect } from "react";
import type { XWelcomeTour as XWelcomeTourElement } from "@vanelsas/baredom/x-welcome-tour";
import { init } from "@vanelsas/baredom/x-welcome-tour";

init();

export interface XWelcomeTourProps {
  connector?: string;
  open?: boolean;
  prevLabel?: string;
  nextLabel?: string;
  counter?: boolean;
  doneLabel?: string;
  skipLabel?: string;
  dots?: boolean;
  step?: number;
  onStart?: (e: CustomEvent<{}>) => void;
  onStepChange?: (e: CustomEvent<{ step: number; previousStep: number }>) => void;
  onComplete?: (e: CustomEvent<{ stepsCompleted: number }>) => void;
  onSkip?: (e: CustomEvent<{ step: number }>) => void;
  children?: React.ReactNode;
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  slot?: string;
}

export const XWelcomeTour = forwardRef<XWelcomeTourElement, XWelcomeTourProps>(
  function XWelcomeTour(props, forwardedRef) {
    const { onStart, onStepChange, onComplete, onSkip, children, ...rest } = props;
    const innerRef = useRef<XWelcomeTourElement>(null);

    const setRef = (el: XWelcomeTourElement | null) => {
      innerRef.current = el;
      if (typeof forwardedRef === "function") forwardedRef(el);
      else if (forwardedRef) forwardedRef.current = el;
    };

    useEffect(() => {
      const el = innerRef.current;
      if (!el) return;
      const cleanup: Array<() => void> = [];

      if (onStart) {
        el.addEventListener("x-welcome-tour-start", onStart as EventListener);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-start", onStart as EventListener));
      }
      if (onStepChange) {
        el.addEventListener("x-welcome-tour-step-change", onStepChange as EventListener);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-step-change", onStepChange as EventListener));
      }
      if (onComplete) {
        el.addEventListener("x-welcome-tour-complete", onComplete as EventListener);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-complete", onComplete as EventListener));
      }
      if (onSkip) {
        el.addEventListener("x-welcome-tour-skip", onSkip as EventListener);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-skip", onSkip as EventListener));
      }

      return () => cleanup.forEach(fn => fn());
    }, [onStart, onStepChange, onComplete, onSkip]);

    return <x-welcome-tour ref={setRef} {...rest}>{children}</x-welcome-tour>;
  }
);
