// x-checkbox-cva.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, forwardRef, OnInit, OnDestroy, NgZone } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import type { XCheckbox as XCheckboxElement } from '@vanelsas/baredom/x-checkbox';
import { init } from '@vanelsas/baredom/x-checkbox';

init();

@Directive({
  selector: 'x-checkbox[formControlName],x-checkbox[formControl],x-checkbox[ngModel]',
  standalone: true,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => BaredomCheckboxCva),
    multi: true,
  }],
})
export class BaredomCheckboxCva implements ControlValueAccessor, OnInit, OnDestroy {
  private el: XCheckboxElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XCheckboxElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  private onChange: (value: boolean) => void = () => {};
  private onTouched: () => void = () => {};

  ngOnInit(): void {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      this.zone.run(() => this.onChange(detail.checked));
    };
    this.el.addEventListener('x-checkbox-change', handler);
    this.listeners.push(() => this.el.removeEventListener('x-checkbox-change', handler));

    const blur = () => this.zone.run(() => this.onTouched());
    this.el.addEventListener('focusout', blur);
    this.listeners.push(() => this.el.removeEventListener('focusout', blur));
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  writeValue(v: boolean): void {
    if (v) this.el.setAttribute('checked', '');
    else this.el.removeAttribute('checked');
  }

  registerOnChange(fn: (v: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(d: boolean): void {
    if (d) this.el.setAttribute('disabled', '');
    else this.el.removeAttribute('disabled');
  }
}
