// x-pagination-cva.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, forwardRef, OnInit, OnDestroy, NgZone } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import type { XPagination as XPaginationElement } from '@vanelsas/baredom/x-pagination';
import { init } from '@vanelsas/baredom/x-pagination';

init();

@Directive({
  selector: 'x-pagination[formControlName],x-pagination[formControl],x-pagination[ngModel]',
  standalone: true,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => BaredomPaginationCva),
    multi: true,
  }],
})
export class BaredomPaginationCva implements ControlValueAccessor, OnInit, OnDestroy {
  private el: XPaginationElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XPaginationElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  private onChange: (value: number) => void = () => {};
  private onTouched: () => void = () => {};

  ngOnInit(): void {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      this.zone.run(() => this.onChange(detail.page));
    };
    this.el.addEventListener('page-change', handler);
    this.listeners.push(() => this.el.removeEventListener('page-change', handler));

    const blur = () => this.zone.run(() => this.onTouched());
    this.el.addEventListener('focusout', blur);
    this.listeners.push(() => this.el.removeEventListener('focusout', blur));
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  writeValue(v: number): void {
    if (v != null) this.el.setAttribute('page', String(v));
    else this.el.removeAttribute('page');
  }

  registerOnChange(fn: (v: number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(d: boolean): void {
    if (d) this.el.setAttribute('disabled', '');
    else this.el.removeAttribute('disabled');
  }
}
