// x-select-cva.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, forwardRef, OnInit, OnDestroy, NgZone } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import type { XSelect as XSelectElement } from '@vanelsas/baredom/x-select';
import { init } from '@vanelsas/baredom/x-select';

init();

@Directive({
  selector: 'x-select[formControlName],x-select[formControl],x-select[ngModel]',
  standalone: true,
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => BaredomSelectCva),
    multi: true,
  }],
})
export class BaredomSelectCva implements ControlValueAccessor, OnInit, OnDestroy {
  private el: XSelectElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XSelectElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  private onChange: (value: string) => void = () => {};
  private onTouched: () => void = () => {};

  ngOnInit(): void {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail;
      this.zone.run(() => this.onChange(detail.value));
    };
    this.el.addEventListener('x-select-change', handler);
    this.listeners.push(() => this.el.removeEventListener('x-select-change', handler));

    const blur = () => this.zone.run(() => this.onTouched());
    this.el.addEventListener('focusout', blur);
    this.listeners.push(() => this.el.removeEventListener('focusout', blur));
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  writeValue(v: string): void {
    if (v != null) this.el.setAttribute('value', String(v));
    else this.el.removeAttribute('value');
  }

  registerOnChange(fn: (v: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(d: boolean): void {
    if (d) this.el.setAttribute('disabled', '');
    else this.el.removeAttribute('disabled');
  }
}
