(ns baredom.components-table
  "The components of the registry, for a test that covers every one of them."
  (:require
   [baredom.exports.x-alert               :as x-alert]
   [baredom.exports.x-avatar              :as x-avatar]
   [baredom.exports.x-avatar-group        :as x-avatar-group]
   [baredom.exports.x-badge               :as x-badge]
   [baredom.exports.x-bento-grid          :as x-bento-grid]
   [baredom.exports.x-bento-item          :as x-bento-item]
   [baredom.exports.x-breadcrumbs         :as x-breadcrumbs]
   [baredom.exports.x-button              :as x-button]
   [baredom.exports.x-calendar            :as x-calendar]
   [baredom.exports.x-cancel-dialogue     :as x-cancel-dialogue]
   [baredom.exports.x-card                :as x-card]
   [baredom.exports.x-carousel            :as x-carousel]
   [baredom.exports.x-chart               :as x-chart]
   [baredom.exports.x-checkbox            :as x-checkbox]
   [baredom.exports.x-chip                :as x-chip]
   [baredom.exports.x-code                :as x-code]
   [baredom.exports.x-collapse            :as x-collapse]
   [baredom.exports.x-color-picker        :as x-color-picker]
   [baredom.exports.x-combobox            :as x-combobox]
   [baredom.exports.x-command-palette     :as x-command-palette]
   [baredom.exports.x-confetti            :as x-confetti]
   [baredom.exports.x-container           :as x-container]
   [baredom.exports.x-context-menu        :as x-context-menu]
   [baredom.exports.x-copy                :as x-copy]
   [baredom.exports.x-currency-field      :as x-currency-field]
   [baredom.exports.x-date-picker         :as x-date-picker]
   [baredom.exports.x-divider             :as x-divider]
   [baredom.exports.x-drag-panel          :as x-drag-panel]
   [baredom.exports.x-drawer              :as x-drawer]
   [baredom.exports.x-drop-zone           :as x-drop-zone]
   [baredom.exports.x-dropdown            :as x-dropdown]
   [baredom.exports.x-fieldset            :as x-fieldset]
   [baredom.exports.x-file-download       :as x-file-download]
   [baredom.exports.x-file-upload         :as x-file-upload]
   [baredom.exports.x-floating-panel      :as x-floating-panel]
   [baredom.exports.x-form                :as x-form]
   [baredom.exports.x-form-field          :as x-form-field]
   [baredom.exports.x-gaussian-blur       :as x-gaussian-blur]
   [baredom.exports.x-grid                :as x-grid]
   [baredom.exports.x-i18n                :as x-i18n]
   [baredom.exports.x-i18n-provider       :as x-i18n-provider]
   [baredom.exports.x-icon                :as x-icon]
   [baredom.exports.x-image               :as x-image]
   [baredom.exports.x-kbd                 :as x-kbd]
   [baredom.exports.x-kinetic-canvas      :as x-kinetic-canvas]
   [baredom.exports.x-kinetic-font        :as x-kinetic-font]
   [baredom.exports.x-kinetic-typography  :as x-kinetic-typography]
   [baredom.exports.x-liquid-dock         :as x-liquid-dock]
   [baredom.exports.x-liquid-fill         :as x-liquid-fill]
   [baredom.exports.x-liquid-glass        :as x-liquid-glass]
   [baredom.exports.x-menu                :as x-menu]
   [baredom.exports.x-menu-item           :as x-menu-item]
   [baredom.exports.x-metaball-cursor     :as x-metaball-cursor]
   [baredom.exports.x-modal               :as x-modal]
   [baredom.exports.x-morph-stack         :as x-morph-stack]
   [baredom.exports.x-multi-combobox      :as x-multi-combobox]
   [baredom.exports.x-navbar              :as x-navbar]
   [baredom.exports.x-neural-glow         :as x-neural-glow]
   [baredom.exports.x-notification-center :as x-notification-center]
   [baredom.exports.x-organic-divider     :as x-organic-divider]
   [baredom.exports.x-organic-progress    :as x-organic-progress]
   [baredom.exports.x-organic-shape       :as x-organic-shape]
   [baredom.exports.x-otp-input           :as x-otp-input]
   [baredom.exports.x-pagination          :as x-pagination]
   [baredom.exports.x-particle-button     :as x-particle-button]
   [baredom.exports.x-popover             :as x-popover]
   [baredom.exports.x-progress            :as x-progress]
   [baredom.exports.x-progress-circle     :as x-progress-circle]
   [baredom.exports.x-proximity-list      :as x-proximity-list]
   [baredom.exports.x-radio               :as x-radio]
   [baredom.exports.x-rating              :as x-rating]
   [baredom.exports.x-range-slider        :as x-range-slider]
   [baredom.exports.x-ripple-effect       :as x-ripple-effect]
   [baredom.exports.x-scroll              :as x-scroll]
   [baredom.exports.x-scroll-parallax     :as x-scroll-parallax]
   [baredom.exports.x-scroll-stack        :as x-scroll-stack]
   [baredom.exports.x-scroll-story        :as x-scroll-story]
   [baredom.exports.x-scroll-timeline     :as x-scroll-timeline]
   [baredom.exports.x-search-field        :as x-search-field]
   [baredom.exports.x-select              :as x-select]
   [baredom.exports.x-sidebar             :as x-sidebar]
   [baredom.exports.x-skeleton            :as x-skeleton]
   [baredom.exports.x-skeleton-group      :as x-skeleton-group]
   [baredom.exports.x-slider              :as x-slider]
   [baredom.exports.x-soft-body           :as x-soft-body]
   [baredom.exports.x-spacer              :as x-spacer]
   [baredom.exports.x-spinner             :as x-spinner]
   [baredom.exports.x-splash              :as x-splash]
   [baredom.exports.x-split-pane          :as x-split-pane]
   [baredom.exports.x-spotlight-card      :as x-spotlight-card]
   [baredom.exports.x-stat                :as x-stat]
   [baredom.exports.x-stepper             :as x-stepper]
   [baredom.exports.x-switch              :as x-switch]
   [baredom.exports.x-tab                 :as x-tab]
   [baredom.exports.x-table               :as x-table]
   [baredom.exports.x-table-cell          :as x-table-cell]
   [baredom.exports.x-table-row           :as x-table-row]
   [baredom.exports.x-tabs                :as x-tabs]
   [baredom.exports.x-text-area           :as x-text-area]
   [baredom.exports.x-theme               :as x-theme]
   [baredom.exports.x-timeline            :as x-timeline]
   [baredom.exports.x-timeline-item       :as x-timeline-item]
   [baredom.exports.x-toast               :as x-toast]
   [baredom.exports.x-toaster             :as x-toaster]
   [baredom.exports.x-tooltip             :as x-tooltip]
   [baredom.exports.x-typography          :as x-typography]
   [baredom.exports.x-welcome-tour        :as x-welcome-tour]))

(def components
  "One row for each component: how to register it and what its export declares."
  [[x-alert/register!               x-alert/public-api]
   [x-avatar/register!              x-avatar/public-api]
   [x-avatar-group/register!        x-avatar-group/public-api]
   [x-badge/register!               x-badge/public-api]
   [x-bento-grid/register!          x-bento-grid/public-api]
   [x-bento-item/register!          x-bento-item/public-api]
   [x-breadcrumbs/register!         x-breadcrumbs/public-api]
   [x-button/register!              x-button/public-api]
   [x-calendar/register!            x-calendar/public-api]
   [x-cancel-dialogue/register!     x-cancel-dialogue/public-api]
   [x-card/register!                x-card/public-api]
   [x-carousel/register!            x-carousel/public-api]
   [x-chart/register!               x-chart/public-api]
   [x-checkbox/register!            x-checkbox/public-api]
   [x-chip/register!                x-chip/public-api]
   [x-code/register!                x-code/public-api]
   [x-collapse/register!            x-collapse/public-api]
   [x-color-picker/register!        x-color-picker/public-api]
   [x-combobox/register!            x-combobox/public-api]
   [x-command-palette/register!     x-command-palette/public-api]
   [x-confetti/register!            x-confetti/public-api]
   [x-container/register!           x-container/public-api]
   [x-context-menu/register!        x-context-menu/public-api]
   [x-copy/register!                x-copy/public-api]
   [x-currency-field/register!      x-currency-field/public-api]
   [x-date-picker/register!         x-date-picker/public-api]
   [x-divider/register!             x-divider/public-api]
   [x-drag-panel/register!          x-drag-panel/public-api]
   [x-drawer/register!              x-drawer/public-api]
   [x-drop-zone/register!           x-drop-zone/public-api]
   [x-dropdown/register!            x-dropdown/public-api]
   [x-fieldset/register!            x-fieldset/public-api]
   [x-file-download/register!       x-file-download/public-api]
   [x-file-upload/register!         x-file-upload/public-api]
   [x-floating-panel/register!      x-floating-panel/public-api]
   [x-form/register!                x-form/public-api]
   [x-form-field/register!          x-form-field/public-api]
   [x-gaussian-blur/register!       x-gaussian-blur/public-api]
   [x-grid/register!                x-grid/public-api]
   [x-i18n/register!                x-i18n/public-api]
   [x-i18n-provider/register!       x-i18n-provider/public-api]
   [x-icon/register!                x-icon/public-api]
   [x-image/register!               x-image/public-api]
   [x-kbd/register!                 x-kbd/public-api]
   [x-kinetic-canvas/register!      x-kinetic-canvas/public-api]
   [x-kinetic-font/register!        x-kinetic-font/public-api]
   [x-kinetic-typography/register!  x-kinetic-typography/public-api]
   [x-liquid-dock/register!         x-liquid-dock/public-api]
   [x-liquid-fill/register!         x-liquid-fill/public-api]
   [x-liquid-glass/register!        x-liquid-glass/public-api]
   [x-menu/register!                x-menu/public-api]
   [x-menu-item/register!           x-menu-item/public-api]
   [x-metaball-cursor/register!     x-metaball-cursor/public-api]
   [x-modal/register!               x-modal/public-api]
   [x-morph-stack/register!         x-morph-stack/public-api]
   [x-multi-combobox/register!      x-multi-combobox/public-api]
   [x-navbar/register!              x-navbar/public-api]
   [x-neural-glow/register!         x-neural-glow/public-api]
   [x-notification-center/register! x-notification-center/public-api]
   [x-organic-divider/register!     x-organic-divider/public-api]
   [x-organic-progress/register!    x-organic-progress/public-api]
   [x-organic-shape/register!       x-organic-shape/public-api]
   [x-otp-input/register!           x-otp-input/public-api]
   [x-pagination/register!          x-pagination/public-api]
   [x-particle-button/register!     x-particle-button/public-api]
   [x-popover/register!             x-popover/public-api]
   [x-progress/register!            x-progress/public-api]
   [x-progress-circle/register!     x-progress-circle/public-api]
   [x-proximity-list/register!      x-proximity-list/public-api]
   [x-radio/register!               x-radio/public-api]
   [x-rating/register!              x-rating/public-api]
   [x-range-slider/register!        x-range-slider/public-api]
   [x-ripple-effect/register!       x-ripple-effect/public-api]
   [x-scroll/register!              x-scroll/public-api]
   [x-scroll-parallax/register!     x-scroll-parallax/public-api]
   [x-scroll-stack/register!        x-scroll-stack/public-api]
   [x-scroll-story/register!        x-scroll-story/public-api]
   [x-scroll-timeline/register!     x-scroll-timeline/public-api]
   [x-search-field/register!        x-search-field/public-api]
   [x-select/register!              x-select/public-api]
   [x-sidebar/register!             x-sidebar/public-api]
   [x-skeleton/register!            x-skeleton/public-api]
   [x-skeleton-group/register!      x-skeleton-group/public-api]
   [x-slider/register!              x-slider/public-api]
   [x-soft-body/register!           x-soft-body/public-api]
   [x-spacer/register!              x-spacer/public-api]
   [x-spinner/register!             x-spinner/public-api]
   [x-splash/register!              x-splash/public-api]
   [x-split-pane/register!          x-split-pane/public-api]
   [x-spotlight-card/register!      x-spotlight-card/public-api]
   [x-stat/register!                x-stat/public-api]
   [x-stepper/register!             x-stepper/public-api]
   [x-switch/register!              x-switch/public-api]
   [x-tab/register!                 x-tab/public-api]
   [x-table/register!               x-table/public-api]
   [x-table-cell/register!          x-table-cell/public-api]
   [x-table-row/register!           x-table-row/public-api]
   [x-tabs/register!                x-tabs/public-api]
   [x-text-area/register!           x-text-area/public-api]
   [x-theme/register!               x-theme/public-api]
   [x-timeline/register!            x-timeline/public-api]
   [x-timeline-item/register!       x-timeline-item/public-api]
   [x-toast/register!               x-toast/public-api]
   [x-toaster/register!             x-toaster/public-api]
   [x-tooltip/register!             x-tooltip/public-api]
   [x-typography/register!          x-typography/public-api]
   [x-welcome-tour/register!        x-welcome-tour/public-api]])
