// x-avatar-group.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XAvatarGroup as XAvatarGroupElement } from "@vanelsas/baredom/x-avatar-group";
import { init } from "@vanelsas/baredom/x-avatar-group";

init();

export interface XAvatarGroupProps {
  size?: string;
  overlap?: string;
  max?: number;
  direction?: string;
  disabled?: boolean;
  label?: string;
  ref?: XAvatarGroupElement | ((el: XAvatarGroupElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XAvatarGroup(props: XAvatarGroupProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XAvatarGroupElement;

  const setRef = (r: XAvatarGroupElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-avatar-group ref={setRef} {...others}>
      {local.children}
    </x-avatar-group>
  );
}
