// x-avatar.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XAvatar as XAvatarElement } from "@vanelsas/baredom/x-avatar";
import { init } from "@vanelsas/baredom/x-avatar";

init();

export interface XAvatarProps {
  initials?: string;
  disabled?: boolean;
  variant?: string;
  alt?: string;
  name?: string;
  src?: string;
  size?: string;
  status?: string;
  shape?: string;
  ref?: XAvatarElement | ((el: XAvatarElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XAvatar(props: XAvatarProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XAvatarElement;

  const setRef = (r: XAvatarElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-avatar ref={setRef} {...others}>
      {local.children}
    </x-avatar>
  );
}
