// x-badge.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XBadge as XBadgeElement } from "@vanelsas/baredom/x-badge";
import { init } from "@vanelsas/baredom/x-badge";

init();

export interface XBadgeProps {
  variant?: string;
  size?: string;
  pill?: boolean;
  dot?: boolean;
  count?: number;
  max?: number;
  text?: string;
  ref?: XBadgeElement | ((el: XBadgeElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XBadge(props: XBadgeProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XBadgeElement;

  const setRef = (r: XBadgeElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-badge ref={setRef} {...others}>
      {local.children}
    </x-badge>
  );
}
