// x-chart.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XChart as XChartElement } from "@vanelsas/baredom/x-chart";
import { init } from "@vanelsas/baredom/x-chart";

init();

export interface XChartProps {
  selected?: string;
  disabled?: boolean;
  axes?: boolean;
  grid?: boolean;
  cursor?: string;
  type?: string;
  loading?: boolean;
  padding?: number;
  tooltip?: boolean;
  height?: number;
  data?: any;
  onSelect?: (e: CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>) => void;
  onHover?: (e: CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>) => void;
  ref?: XChartElement | ((el: XChartElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XChart(props: XChartProps): JSX.Element {
  const [local, others] = splitProps(props, ["onSelect", "onHover", "ref", "children"]);
  let el!: XChartElement;

  const setRef = (r: XChartElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onSelect?.(e as CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>);
      el.addEventListener("x-chart-select", handler);
      onCleanup(() => el.removeEventListener("x-chart-select", handler));
    }
    {
      const handler = (e: Event) => local.onHover?.(e as CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>);
      el.addEventListener("x-chart-hover", handler);
      onCleanup(() => el.removeEventListener("x-chart-hover", handler));
    }
  });

  return (
    <x-chart ref={setRef} {...others}>
      {local.children}
    </x-chart>
  );
}
