// x-context-menu.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XContextMenu as XContextMenuElement } from "@vanelsas/baredom/x-context-menu";
import { init } from "@vanelsas/baredom/x-context-menu";

init();

export interface XContextMenuProps {
  open?: boolean;
  disabled?: boolean;
  placement?: string;
  offset?: string;
  zIndex?: string;
  onOpenRequest?: (e: CustomEvent<{ reason: string }>) => void;
  onOpen?: (e: CustomEvent<{ reason: string }>) => void;
  onCloseRequest?: (e: CustomEvent<{ reason: string }>) => void;
  onClose?: (e: CustomEvent<{ reason: string }>) => void;
  onSelect?: (e: CustomEvent<{ item: Record<string, any> }>) => void;
  ref?: XContextMenuElement | ((el: XContextMenuElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XContextMenu(props: XContextMenuProps): JSX.Element {
  const [local, others] = splitProps(props, ["onOpenRequest", "onOpen", "onCloseRequest", "onClose", "onSelect", "ref", "children"]);
  let el!: XContextMenuElement;

  const setRef = (r: XContextMenuElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onOpenRequest?.(e as CustomEvent<{ reason: string }>);
      el.addEventListener("x-context-menu-open-request", handler);
      onCleanup(() => el.removeEventListener("x-context-menu-open-request", handler));
    }
    {
      const handler = (e: Event) => local.onOpen?.(e as CustomEvent<{ reason: string }>);
      el.addEventListener("x-context-menu-open", handler);
      onCleanup(() => el.removeEventListener("x-context-menu-open", handler));
    }
    {
      const handler = (e: Event) => local.onCloseRequest?.(e as CustomEvent<{ reason: string }>);
      el.addEventListener("x-context-menu-close-request", handler);
      onCleanup(() => el.removeEventListener("x-context-menu-close-request", handler));
    }
    {
      const handler = (e: Event) => local.onClose?.(e as CustomEvent<{ reason: string }>);
      el.addEventListener("x-context-menu-close", handler);
      onCleanup(() => el.removeEventListener("x-context-menu-close", handler));
    }
    {
      const handler = (e: Event) => local.onSelect?.(e as CustomEvent<{ item: Record<string, any> }>);
      el.addEventListener("x-context-menu-select", handler);
      onCleanup(() => el.removeEventListener("x-context-menu-select", handler));
    }
  });

  return (
    <x-context-menu ref={setRef} {...others}>
      {local.children}
    </x-context-menu>
  );
}
