// x-combobox.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup, createEffect } from "solid-js";
import type { JSX } from "solid-js";
import type { XCombobox as XComboboxElement } from "@vanelsas/baredom/x-combobox";
import { init } from "@vanelsas/baredom/x-combobox";

init();

export interface XComboboxProps {
  value?: string;
  placeholder?: string;
  name?: string;
  disabled?: boolean;
  required?: boolean;
  open?: boolean;
  placement?: string;
  defaultValue?: string;
  onChangeRequest?: (e: CustomEvent<{ value: string; label: string; previousValue: string }>) => void;
  onChange?: (e: CustomEvent<{ value: string; label: string }>) => void;
  onInput?: (e: CustomEvent<{ query: string }>) => void;
  onToggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
  ref?: XComboboxElement | ((el: XComboboxElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XCombobox(props: XComboboxProps): JSX.Element {
  const [local, others] = splitProps(props, ["value", "defaultValue", "onChangeRequest", "onChange", "onInput", "onToggle", "ref", "children"]);
  let el!: XComboboxElement;

  const setRef = (r: XComboboxElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el || local.value !== undefined || local.defaultValue === undefined) return;
    el.setAttribute("value", String(local.defaultValue));
  });

  createEffect(() => {
    if (!el) return;
    const v = local.value;
    if (v === undefined) return;
    el.setAttribute("value", String(v));
  });

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => {
        if (local.value !== undefined) e.preventDefault();
        local.onChangeRequest?.(e as CustomEvent<{ value: string; label: string; previousValue: string }>);
      };
      el.addEventListener("x-combobox-change-request", handler);
      onCleanup(() => el.removeEventListener("x-combobox-change-request", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ value: string; label: string }>);
      el.addEventListener("x-combobox-change", handler);
      onCleanup(() => el.removeEventListener("x-combobox-change", handler));
    }
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ query: string }>);
      el.addEventListener("x-combobox-input", handler);
      onCleanup(() => el.removeEventListener("x-combobox-input", handler));
    }
    {
      const handler = (e: Event) => local.onToggle?.(e as CustomEvent<{ open: boolean; source: string }>);
      el.addEventListener("x-combobox-toggle", handler);
      onCleanup(() => el.removeEventListener("x-combobox-toggle", handler));
    }
  });

  return (
    <x-combobox ref={setRef} {...others}>
      {local.children}
    </x-combobox>
  );
}
