// x-color-picker.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XColorPicker as XColorPickerElement } from "@vanelsas/baredom/x-color-picker";
import { init } from "@vanelsas/baredom/x-color-picker";

init();

export interface XColorPickerProps {
  open?: boolean;
  disabled?: boolean;
  name?: string;
  value?: string;
  mode?: string;
  swatches?: string;
  readOnly?: boolean;
  label?: string;
  alpha?: boolean;
  onInput?: (e: CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>) => void;
  onChange?: (e: CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>) => void;
  ref?: XColorPickerElement | ((el: XColorPickerElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XColorPicker(props: XColorPickerProps): JSX.Element {
  const [local, others] = splitProps(props, ["onInput", "onChange", "ref", "children"]);
  let el!: XColorPickerElement;

  const setRef = (r: XColorPickerElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>);
      el.addEventListener("x-color-picker-input", handler);
      onCleanup(() => el.removeEventListener("x-color-picker-input", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>);
      el.addEventListener("x-color-picker-change", handler);
      onCleanup(() => el.removeEventListener("x-color-picker-change", handler));
    }
  });

  return (
    <x-color-picker ref={setRef} {...others}>
      {local.children}
    </x-color-picker>
  );
}
