// x-code.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XCode as XCodeElement } from "@vanelsas/baredom/x-code";
import { init } from "@vanelsas/baredom/x-code";

init();

export interface XCodeProps {
  language?: string;
  filename?: string;
  showCopy?: boolean;
  lineNumbers?: boolean;
  wrap?: boolean;
  maxLines?: number;
  expanded?: boolean;
  code?: string;
  onCopy?: (e: CustomEvent<{ code: string }>) => void;
  onToggle?: (e: CustomEvent<{ expanded: boolean }>) => void;
  ref?: XCodeElement | ((el: XCodeElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XCode(props: XCodeProps): JSX.Element {
  const [local, others] = splitProps(props, ["onCopy", "onToggle", "ref", "children"]);
  let el!: XCodeElement;

  const setRef = (r: XCodeElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onCopy?.(e as CustomEvent<{ code: string }>);
      el.addEventListener("x-code-copy", handler);
      onCleanup(() => el.removeEventListener("x-code-copy", handler));
    }
    {
      const handler = (e: Event) => local.onToggle?.(e as CustomEvent<{ expanded: boolean }>);
      el.addEventListener("x-code-toggle", handler);
      onCleanup(() => el.removeEventListener("x-code-toggle", handler));
    }
  });

  return (
    <x-code ref={setRef} {...others}>
      {local.children}
    </x-code>
  );
}
