// x-drawer.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XDrawer as XDrawerElement } from "@vanelsas/baredom/x-drawer";
import { init } from "@vanelsas/baredom/x-drawer";

init();

export interface XDrawerProps {
  open?: boolean;
  placement?: string;
  label?: string;
  onToggle?: (e: CustomEvent<{ open: boolean }>) => void;
  onDismiss?: (e: CustomEvent<{ reason: string }>) => void;
  ref?: XDrawerElement | ((el: XDrawerElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XDrawer(props: XDrawerProps): JSX.Element {
  const [local, others] = splitProps(props, ["onToggle", "onDismiss", "ref", "children"]);
  let el!: XDrawerElement;

  const setRef = (r: XDrawerElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onToggle?.(e as CustomEvent<{ open: boolean }>);
      el.addEventListener("x-drawer-toggle", handler);
      onCleanup(() => el.removeEventListener("x-drawer-toggle", handler));
    }
    {
      const handler = (e: Event) => local.onDismiss?.(e as CustomEvent<{ reason: string }>);
      el.addEventListener("x-drawer-dismiss", handler);
      onCleanup(() => el.removeEventListener("x-drawer-dismiss", handler));
    }
  });

  return (
    <x-drawer ref={setRef} {...others}>
      {local.children}
    </x-drawer>
  );
}
