// x-drag-panel.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XDragPanel as XDragPanelElement } from "@vanelsas/baredom/x-drag-panel";
import { init } from "@vanelsas/baredom/x-drag-panel";

init();

export interface XDragPanelProps {
  kind?: string;
  value?: string;
  label?: string;
  grab?: string;
  autoScroll?: string;
  disabled?: boolean;
  pending?: boolean;
  onDragStart?: (e: CustomEvent<{ kind: string; value: string }>) => void;
  onDragCancel?: (e: CustomEvent<{ kind: string; value: string; reason: string }>) => void;
  ref?: XDragPanelElement | ((el: XDragPanelElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XDragPanel(props: XDragPanelProps): JSX.Element {
  const [local, others] = splitProps(props, ["onDragStart", "onDragCancel", "ref", "children"]);
  let el!: XDragPanelElement;

  const setRef = (r: XDragPanelElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onDragStart?.(e as CustomEvent<{ kind: string; value: string }>);
      el.addEventListener("x-drag-panel-drag-start", handler);
      onCleanup(() => el.removeEventListener("x-drag-panel-drag-start", handler));
    }
    {
      const handler = (e: Event) => local.onDragCancel?.(e as CustomEvent<{ kind: string; value: string; reason: string }>);
      el.addEventListener("x-drag-panel-drag-cancel", handler);
      onCleanup(() => el.removeEventListener("x-drag-panel-drag-cancel", handler));
    }
  });

  return (
    <x-drag-panel ref={setRef} {...others}>
      {local.children}
    </x-drag-panel>
  );
}
