// x-fieldset.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XFieldset as XFieldsetElement } from "@vanelsas/baredom/x-fieldset";
import { init } from "@vanelsas/baredom/x-fieldset";

init();

export interface XFieldsetProps {
  legend?: string;
  disabled?: boolean;
  ref?: XFieldsetElement | ((el: XFieldsetElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XFieldset(props: XFieldsetProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XFieldsetElement;

  const setRef = (r: XFieldsetElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-fieldset ref={setRef} {...others}>
      {local.children}
    </x-fieldset>
  );
}
