// x-form-field.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XFormField as XFormFieldElement } from "@vanelsas/baredom/x-form-field";
import { init } from "@vanelsas/baredom/x-form-field";

init();

export interface XFormFieldProps {
  placeholder?: string;
  disabled?: boolean;
  name?: string;
  value?: string;
  readonly?: boolean;
  type?: string;
  label?: string;
  autocomplete?: string;
  required?: boolean;
  onInput?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string }>) => void;
  ref?: XFormFieldElement | ((el: XFormFieldElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XFormField(props: XFormFieldProps): JSX.Element {
  const [local, others] = splitProps(props, ["onInput", "onChange", "ref", "children"]);
  let el!: XFormFieldElement;

  const setRef = (r: XFormFieldElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-form-field-input", handler);
      onCleanup(() => el.removeEventListener("x-form-field-input", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-form-field-change", handler);
      onCleanup(() => el.removeEventListener("x-form-field-change", handler));
    }
  });

  return (
    <x-form-field ref={setRef} {...others}>
      {local.children}
    </x-form-field>
  );
}
