// x-form.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XForm as XFormElement } from "@vanelsas/baredom/x-form";
import { init } from "@vanelsas/baredom/x-form";

init();

export interface XFormProps {
  loading?: boolean;
  novalidate?: boolean;
  autocomplete?: string;
  onSubmit?: (e: CustomEvent<{ values: Record<string, any> }>) => void;
  onReset?: (e: CustomEvent<{}>) => void;
  ref?: XFormElement | ((el: XFormElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XForm(props: XFormProps): JSX.Element {
  const [local, others] = splitProps(props, ["onSubmit", "onReset", "ref", "children"]);
  let el!: XFormElement;

  const setRef = (r: XFormElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onSubmit?.(e as CustomEvent<{ values: Record<string, any> }>);
      el.addEventListener("x-form-submit", handler);
      onCleanup(() => el.removeEventListener("x-form-submit", handler));
    }
    {
      const handler = (e: Event) => local.onReset?.(e as CustomEvent<{}>);
      el.addEventListener("x-form-reset", handler);
      onCleanup(() => el.removeEventListener("x-form-reset", handler));
    }
  });

  return (
    <x-form ref={setRef} {...others}>
      {local.children}
    </x-form>
  );
}
