// x-gaussian-blur.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XGaussianBlur as XGaussianBlurElement } from "@vanelsas/baredom/x-gaussian-blur";
import { init } from "@vanelsas/baredom/x-gaussian-blur";

init();

export interface XGaussianBlurProps {
  paused?: boolean;
  animation?: string;
  speed?: string;
  colors?: string;
  size?: string;
  blur?: string;
  opacity?: string;
  count?: string;
  blend?: string;
  ref?: XGaussianBlurElement | ((el: XGaussianBlurElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XGaussianBlur(props: XGaussianBlurProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XGaussianBlurElement;

  const setRef = (r: XGaussianBlurElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-gaussian-blur ref={setRef} {...others}>
      {local.children}
    </x-gaussian-blur>
  );
}
