// x-grid.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XGrid as XGridElement } from "@vanelsas/baredom/x-grid";
import { init } from "@vanelsas/baredom/x-grid";

init();

export interface XGridProps {
  ref?: XGridElement | ((el: XGridElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XGrid(props: XGridProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XGridElement;

  const setRef = (r: XGridElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-grid ref={setRef} {...others}>
      {local.children}
    </x-grid>
  );
}
