// x-i18n.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XI18n as XI18nElement } from "@vanelsas/baredom/x-i18n";
import { init } from "@vanelsas/baredom/x-i18n";

init();

export interface XI18nProps {
  key?: string;
  params?: string;
  ref?: XI18nElement | ((el: XI18nElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XI18n(props: XI18nProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XI18nElement;

  const setRef = (r: XI18nElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-i18n ref={setRef} {...others}>
      {local.children}
    </x-i18n>
  );
}
