// x-kbd.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XKbd as XKbdElement } from "@vanelsas/baredom/x-kbd";
import { init } from "@vanelsas/baredom/x-kbd";

init();

export interface XKbdProps {
  keys?: string;
  separator?: string;
  size?: string;
  platform?: string;
  label?: string;
  ref?: XKbdElement | ((el: XKbdElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XKbd(props: XKbdProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XKbdElement;

  const setRef = (r: XKbdElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-kbd ref={setRef} {...others}>
      {local.children}
    </x-kbd>
  );
}
