// x-kinetic-font.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XKineticFont as XKineticFontElement } from "@vanelsas/baredom/x-kinetic-font";
import { init } from "@vanelsas/baredom/x-kinetic-font";

init();

export interface XKineticFontProps {
  mass?: number;
  tension?: number;
  mode?: string;
  perChar?: boolean;
  radius?: number;
  intensity?: number;
  fontFamily?: string;
  friction?: number;
  trigger?: string;
  text?: string;
  onSpringActivate?: (e: CustomEvent<{}>) => void;
  onSpringSettle?: (e: CustomEvent<{}>) => void;
  ref?: XKineticFontElement | ((el: XKineticFontElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XKineticFont(props: XKineticFontProps): JSX.Element {
  const [local, others] = splitProps(props, ["onSpringActivate", "onSpringSettle", "ref", "children"]);
  let el!: XKineticFontElement;

  const setRef = (r: XKineticFontElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onSpringActivate?.(e as CustomEvent<{}>);
      el.addEventListener("x-kinetic-font-spring-activate", handler);
      onCleanup(() => el.removeEventListener("x-kinetic-font-spring-activate", handler));
    }
    {
      const handler = (e: Event) => local.onSpringSettle?.(e as CustomEvent<{}>);
      el.addEventListener("x-kinetic-font-spring-settle", handler);
      onCleanup(() => el.removeEventListener("x-kinetic-font-spring-settle", handler));
    }
  });

  return (
    <x-kinetic-font ref={setRef} {...others}>
      {local.children}
    </x-kinetic-font>
  );
}
