// x-kinetic-canvas.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XKineticCanvas as XKineticCanvasElement } from "@vanelsas/baredom/x-kinetic-canvas";
import { init } from "@vanelsas/baredom/x-kinetic-canvas";

init();

export interface XKineticCanvasProps {
  type?: string;
  variant?: string;
  speed?: string;
  density?: string;
  fullscreen?: boolean;
  paused?: boolean;
  ref?: XKineticCanvasElement | ((el: XKineticCanvasElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XKineticCanvas(props: XKineticCanvasProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XKineticCanvasElement;

  const setRef = (r: XKineticCanvasElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-kinetic-canvas ref={setRef} {...others}>
      {local.children}
    </x-kinetic-canvas>
  );
}
