// x-liquid-dock.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XLiquidDock as XLiquidDockElement } from "@vanelsas/baredom/x-liquid-dock";
import { init } from "@vanelsas/baredom/x-liquid-dock";

init();

export interface XLiquidDockProps {
  rippleScale?: number;
  color?: string;
  magnetStrength?: number;
  disabled?: boolean;
  threshold?: string;
  magnetRadius?: number;
  bobIntensity?: number;
  blur?: number;
  rippleSpeed?: number;
  gap?: number;
  position?: string;
  onSelect?: (e: CustomEvent<{ index: number; item: any; source: string }>) => void;
  ref?: XLiquidDockElement | ((el: XLiquidDockElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XLiquidDock(props: XLiquidDockProps): JSX.Element {
  const [local, others] = splitProps(props, ["onSelect", "ref", "children"]);
  let el!: XLiquidDockElement;

  const setRef = (r: XLiquidDockElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onSelect?.(e as CustomEvent<{ index: number; item: any; source: string }>);
      el.addEventListener("x-liquid-dock-select", handler);
      onCleanup(() => el.removeEventListener("x-liquid-dock-select", handler));
    }
  });

  return (
    <x-liquid-dock ref={setRef} {...others}>
      {local.children}
    </x-liquid-dock>
  );
}
