// x-menu-item.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XMenuItem as XMenuItemElement } from "@vanelsas/baredom/x-menu-item";
import { init } from "@vanelsas/baredom/x-menu-item";

init();

export interface XMenuItemProps {
  value?: string;
  disabled?: boolean;
  variant?: string;
  type?: string;
  onSelect?: (e: CustomEvent<{ value: string }>) => void;
  ref?: XMenuItemElement | ((el: XMenuItemElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XMenuItem(props: XMenuItemProps): JSX.Element {
  const [local, others] = splitProps(props, ["onSelect", "ref", "children"]);
  let el!: XMenuItemElement;

  const setRef = (r: XMenuItemElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onSelect?.(e as CustomEvent<{ value: string }>);
      el.addEventListener("x-menu-item-select", handler);
      onCleanup(() => el.removeEventListener("x-menu-item-select", handler));
    }
  });

  return (
    <x-menu-item ref={setRef} {...others}>
      {local.children}
    </x-menu-item>
  );
}
