// x-navbar.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XNavbar as XNavbarElement } from "@vanelsas/baredom/x-navbar";
import { init } from "@vanelsas/baredom/x-navbar";

init();

export interface XNavbarProps {
  sticky?: boolean;
  elevated?: boolean;
  label?: string;
  variant?: string;
  orientation?: string;
  alignment?: string;
  breakpoint?: string;
  onFocusVisible?: (e: CustomEvent<{}>) => void;
  onNavigate?: (e: CustomEvent<{ href: string; source: string }>) => void;
  onBrandActivate?: (e: CustomEvent<{ source: string }>) => void;
  ref?: XNavbarElement | ((el: XNavbarElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XNavbar(props: XNavbarProps): JSX.Element {
  const [local, others] = splitProps(props, ["onFocusVisible", "onNavigate", "onBrandActivate", "ref", "children"]);
  let el!: XNavbarElement;

  const setRef = (r: XNavbarElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onFocusVisible?.(e as CustomEvent<{}>);
      el.addEventListener("focus-visible", handler);
      onCleanup(() => el.removeEventListener("focus-visible", handler));
    }
    {
      const handler = (e: Event) => local.onNavigate?.(e as CustomEvent<{ href: string; source: string }>);
      el.addEventListener("navigate", handler);
      onCleanup(() => el.removeEventListener("navigate", handler));
    }
    {
      const handler = (e: Event) => local.onBrandActivate?.(e as CustomEvent<{ source: string }>);
      el.addEventListener("brand-activate", handler);
      onCleanup(() => el.removeEventListener("brand-activate", handler));
    }
  });

  return (
    <x-navbar ref={setRef} {...others}>
      {local.children}
    </x-navbar>
  );
}
