// x-organic-progress.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XOrganicProgress as XOrganicProgressElement } from "@vanelsas/baredom/x-organic-progress";
import { init } from "@vanelsas/baredom/x-organic-progress";

init();

export interface XOrganicProgressProps {
  progress?: string;
  variant?: string;
  color?: string;
  bloom?: boolean;
  density?: string;
  seed?: number;
  label?: string;
  onComplete?: (e: CustomEvent<{ progress: number }>) => void;
  onBloomEnd?: (e: CustomEvent<{ progress: number }>) => void;
  ref?: XOrganicProgressElement | ((el: XOrganicProgressElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XOrganicProgress(props: XOrganicProgressProps): JSX.Element {
  const [local, others] = splitProps(props, ["onComplete", "onBloomEnd", "ref", "children"]);
  let el!: XOrganicProgressElement;

  const setRef = (r: XOrganicProgressElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onComplete?.(e as CustomEvent<{ progress: number }>);
      el.addEventListener("x-organic-progress-complete", handler);
      onCleanup(() => el.removeEventListener("x-organic-progress-complete", handler));
    }
    {
      const handler = (e: Event) => local.onBloomEnd?.(e as CustomEvent<{ progress: number }>);
      el.addEventListener("x-organic-progress-bloom-end", handler);
      onCleanup(() => el.removeEventListener("x-organic-progress-bloom-end", handler));
    }
  });

  return (
    <x-organic-progress ref={setRef} {...others}>
      {local.children}
    </x-organic-progress>
  );
}
