// x-organic-divider.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XOrganicDivider as XOrganicDividerElement } from "@vanelsas/baredom/x-organic-divider";
import { init } from "@vanelsas/baredom/x-organic-divider";

init();

export interface XOrganicDividerProps {
  shape?: string;
  layers?: string;
  height?: string;
  flip?: boolean;
  mirror?: boolean;
  animation?: string;
  path?: string;
  ref?: XOrganicDividerElement | ((el: XOrganicDividerElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XOrganicDivider(props: XOrganicDividerProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XOrganicDividerElement;

  const setRef = (r: XOrganicDividerElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-organic-divider ref={setRef} {...others}>
      {local.children}
    </x-organic-divider>
  );
}
