// x-otp-input.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XOtpInput as XOtpInputElement } from "@vanelsas/baredom/x-otp-input";
import { init } from "@vanelsas/baredom/x-otp-input";

init();

export interface XOtpInputProps {
  mask?: boolean;
  placeholder?: string;
  disabled?: boolean;
  name?: string;
  value?: string;
  readonly?: boolean;
  type?: string;
  label?: string;
  autofocus?: boolean;
  length?: number;
  error?: string;
  required?: boolean;
  onInput?: (e: CustomEvent<{ name: string; value: string; complete: boolean }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string; complete: boolean }>) => void;
  onComplete?: (e: CustomEvent<{ name: string; value: string }>) => void;
  ref?: XOtpInputElement | ((el: XOtpInputElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XOtpInput(props: XOtpInputProps): JSX.Element {
  const [local, others] = splitProps(props, ["onInput", "onChange", "onComplete", "ref", "children"]);
  let el!: XOtpInputElement;

  const setRef = (r: XOtpInputElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ name: string; value: string; complete: boolean }>);
      el.addEventListener("x-otp-input-input", handler);
      onCleanup(() => el.removeEventListener("x-otp-input-input", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ name: string; value: string; complete: boolean }>);
      el.addEventListener("x-otp-input-change", handler);
      onCleanup(() => el.removeEventListener("x-otp-input-change", handler));
    }
    {
      const handler = (e: Event) => local.onComplete?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-otp-input-complete", handler);
      onCleanup(() => el.removeEventListener("x-otp-input-complete", handler));
    }
  });

  return (
    <x-otp-input ref={setRef} {...others}>
      {local.children}
    </x-otp-input>
  );
}
