// x-progress-circle.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XProgressCircle as XProgressCircleElement } from "@vanelsas/baredom/x-progress-circle";
import { init } from "@vanelsas/baredom/x-progress-circle";

init();

export interface XProgressCircleProps {
  value?: string;
  max?: string;
  variant?: string;
  size?: string;
  label?: string;
  indeterminate?: boolean;
  showValue?: boolean;
  onComplete?: (e: CustomEvent<{ value: number; max: number }>) => void;
  ref?: XProgressCircleElement | ((el: XProgressCircleElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XProgressCircle(props: XProgressCircleProps): JSX.Element {
  const [local, others] = splitProps(props, ["onComplete", "ref", "children"]);
  let el!: XProgressCircleElement;

  const setRef = (r: XProgressCircleElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onComplete?.(e as CustomEvent<{ value: number; max: number }>);
      el.addEventListener("x-progress-circle-complete", handler);
      onCleanup(() => el.removeEventListener("x-progress-circle-complete", handler));
    }
  });

  return (
    <x-progress-circle ref={setRef} {...others}>
      {local.children}
    </x-progress-circle>
  );
}
