// x-scroll-stack.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XScrollStack as XScrollStackElement } from "@vanelsas/baredom/x-scroll-stack";
import { init } from "@vanelsas/baredom/x-scroll-stack";

init();

export interface XScrollStackProps {
  peek?: number;
  rotation?: number;
  scrollDistance?: number;
  align?: string;
  disabled?: boolean;
  onChange?: (e: CustomEvent<{ stackedCount: number; totalCount: number; progress: number }>) => void;
  onProgress?: (e: CustomEvent<{ progress: number; stackedCount: number; totalCount: number }>) => void;
  ref?: XScrollStackElement | ((el: XScrollStackElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XScrollStack(props: XScrollStackProps): JSX.Element {
  const [local, others] = splitProps(props, ["onChange", "onProgress", "ref", "children"]);
  let el!: XScrollStackElement;

  const setRef = (r: XScrollStackElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ stackedCount: number; totalCount: number; progress: number }>);
      el.addEventListener("x-scroll-stack-change", handler);
      onCleanup(() => el.removeEventListener("x-scroll-stack-change", handler));
    }
    {
      const handler = (e: Event) => local.onProgress?.(e as CustomEvent<{ progress: number; stackedCount: number; totalCount: number }>);
      el.addEventListener("x-scroll-stack-progress", handler);
      onCleanup(() => el.removeEventListener("x-scroll-stack-progress", handler));
    }
  });

  return (
    <x-scroll-stack ref={setRef} {...others}>
      {local.children}
    </x-scroll-stack>
  );
}
