// x-scroll.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XScroll as XScrollElement } from "@vanelsas/baredom/x-scroll";
import { init } from "@vanelsas/baredom/x-scroll";

init();

export interface XScrollProps {
  disabled?: boolean;
  showIndicators?: boolean;
  snap?: string;
  activeIndex?: number;
  mode?: string;
  showControls?: boolean;
  loop?: boolean;
  label?: string;
  gap?: number;
  autoPlay?: boolean;
  interval?: number;
  onChange?: (e: CustomEvent<{ activeIndex: number; previousIndex: number }>) => void;
  onStart?: (e: CustomEvent<{ direction: string; activeIndex: number }>) => void;
  onEnd?: (e: CustomEvent<{ activeIndex: number }>) => void;
  onLoop?: (e: CustomEvent<{ direction: string }>) => void;
  ref?: XScrollElement | ((el: XScrollElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XScroll(props: XScrollProps): JSX.Element {
  const [local, others] = splitProps(props, ["onChange", "onStart", "onEnd", "onLoop", "ref", "children"]);
  let el!: XScrollElement;

  const setRef = (r: XScrollElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ activeIndex: number; previousIndex: number }>);
      el.addEventListener("x-scroll-change", handler);
      onCleanup(() => el.removeEventListener("x-scroll-change", handler));
    }
    {
      const handler = (e: Event) => local.onStart?.(e as CustomEvent<{ direction: string; activeIndex: number }>);
      el.addEventListener("x-scroll-start", handler);
      onCleanup(() => el.removeEventListener("x-scroll-start", handler));
    }
    {
      const handler = (e: Event) => local.onEnd?.(e as CustomEvent<{ activeIndex: number }>);
      el.addEventListener("x-scroll-end", handler);
      onCleanup(() => el.removeEventListener("x-scroll-end", handler));
    }
    {
      const handler = (e: Event) => local.onLoop?.(e as CustomEvent<{ direction: string }>);
      el.addEventListener("x-scroll-loop", handler);
      onCleanup(() => el.removeEventListener("x-scroll-loop", handler));
    }
  });

  return (
    <x-scroll ref={setRef} {...others}>
      {local.children}
    </x-scroll>
  );
}
