// x-scroll-timeline.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XScrollTimeline as XScrollTimelineElement } from "@vanelsas/baredom/x-scroll-timeline";
import { init } from "@vanelsas/baredom/x-scroll-timeline";

init();

export interface XScrollTimelineProps {
  autoplayLoop?: boolean;
  autoplaySpeed?: number;
  autoplayIndicator?: boolean;
  disabled?: boolean;
  layout?: string;
  marker?: string;
  threshold?: number;
  label?: string;
  autoplay?: boolean;
  noProgress?: boolean;
  track?: string;
  onEntryChange?: (e: CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>) => void;
  onEntryEnter?: (e: CustomEvent<{ index: number; id: string; progress: number }>) => void;
  onEntryLeave?: (e: CustomEvent<{ index: number; id: string; progress: number }>) => void;
  onProgress?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  onEnter?: (e: CustomEvent<{ progress: number }>) => void;
  onLeave?: (e: CustomEvent<{ progress: number }>) => void;
  onAutoplayPause?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  onAutoplayResume?: (e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => void;
  ref?: XScrollTimelineElement | ((el: XScrollTimelineElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XScrollTimeline(props: XScrollTimelineProps): JSX.Element {
  const [local, others] = splitProps(props, ["onEntryChange", "onEntryEnter", "onEntryLeave", "onProgress", "onEnter", "onLeave", "onAutoplayPause", "onAutoplayResume", "ref", "children"]);
  let el!: XScrollTimelineElement;

  const setRef = (r: XScrollTimelineElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onEntryChange?.(e as CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>);
      el.addEventListener("x-scroll-timeline-entry-change", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-entry-change", handler));
    }
    {
      const handler = (e: Event) => local.onEntryEnter?.(e as CustomEvent<{ index: number; id: string; progress: number }>);
      el.addEventListener("x-scroll-timeline-entry-enter", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-entry-enter", handler));
    }
    {
      const handler = (e: Event) => local.onEntryLeave?.(e as CustomEvent<{ index: number; id: string; progress: number }>);
      el.addEventListener("x-scroll-timeline-entry-leave", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-entry-leave", handler));
    }
    {
      const handler = (e: Event) => local.onProgress?.(e as CustomEvent<{ progress: number; activeIndex: number; activeId: string }>);
      el.addEventListener("x-scroll-timeline-progress", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-progress", handler));
    }
    {
      const handler = (e: Event) => local.onEnter?.(e as CustomEvent<{ progress: number }>);
      el.addEventListener("x-scroll-timeline-enter", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-enter", handler));
    }
    {
      const handler = (e: Event) => local.onLeave?.(e as CustomEvent<{ progress: number }>);
      el.addEventListener("x-scroll-timeline-leave", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-leave", handler));
    }
    {
      const handler = (e: Event) => local.onAutoplayPause?.(e as CustomEvent<{ progress: number; activeIndex: number; activeId: string }>);
      el.addEventListener("x-scroll-timeline-autoplay-pause", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-autoplay-pause", handler));
    }
    {
      const handler = (e: Event) => local.onAutoplayResume?.(e as CustomEvent<{ progress: number; activeIndex: number; activeId: string }>);
      el.addEventListener("x-scroll-timeline-autoplay-resume", handler);
      onCleanup(() => el.removeEventListener("x-scroll-timeline-autoplay-resume", handler));
    }
  });

  return (
    <x-scroll-timeline ref={setRef} {...others}>
      {local.children}
    </x-scroll-timeline>
  );
}
