// x-search-field.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XSearchField as XSearchFieldElement } from "@vanelsas/baredom/x-search-field";
import { init } from "@vanelsas/baredom/x-search-field";

init();

export interface XSearchFieldProps {
  value?: string;
  name?: string;
  placeholder?: string;
  label?: string;
  autocomplete?: string;
  disabled?: boolean;
  required?: boolean;
  debounce?: number;
  onInput?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onSearch?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onClear?: (e: CustomEvent<{ name: string }>) => void;
  ref?: XSearchFieldElement | ((el: XSearchFieldElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XSearchField(props: XSearchFieldProps): JSX.Element {
  const [local, others] = splitProps(props, ["onInput", "onChange", "onSearch", "onClear", "ref", "children"]);
  let el!: XSearchFieldElement;

  const setRef = (r: XSearchFieldElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-search-field-input", handler);
      onCleanup(() => el.removeEventListener("x-search-field-input", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-search-field-change", handler);
      onCleanup(() => el.removeEventListener("x-search-field-change", handler));
    }
    {
      const handler = (e: Event) => local.onSearch?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-search-field-search", handler);
      onCleanup(() => el.removeEventListener("x-search-field-search", handler));
    }
    {
      const handler = (e: Event) => local.onClear?.(e as CustomEvent<{ name: string }>);
      el.addEventListener("x-search-field-clear", handler);
      onCleanup(() => el.removeEventListener("x-search-field-clear", handler));
    }
  });

  return (
    <x-search-field ref={setRef} {...others}>
      {local.children}
    </x-search-field>
  );
}
