// x-skeleton.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XSkeleton as XSkeletonElement } from "@vanelsas/baredom/x-skeleton";
import { init } from "@vanelsas/baredom/x-skeleton";

init();

export interface XSkeletonProps {
  variant?: string;
  animation?: string;
  width?: string;
  height?: string;
  ref?: XSkeletonElement | ((el: XSkeletonElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XSkeleton(props: XSkeletonProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XSkeletonElement;

  const setRef = (r: XSkeletonElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-skeleton ref={setRef} {...others}>
      {local.children}
    </x-skeleton>
  );
}
