// x-spinner.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XSpinner as XSpinnerElement } from "@vanelsas/baredom/x-spinner";
import { init } from "@vanelsas/baredom/x-spinner";

init();

export interface XSpinnerProps {
  size?: string;
  variant?: string;
  label?: string;
  ref?: XSpinnerElement | ((el: XSpinnerElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XSpinner(props: XSpinnerProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XSpinnerElement;

  const setRef = (r: XSpinnerElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-spinner ref={setRef} {...others}>
      {local.children}
    </x-spinner>
  );
}
