// x-text-area.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup, createEffect } from "solid-js";
import type { JSX } from "solid-js";
import type { XTextArea as XTextAreaElement } from "@vanelsas/baredom/x-text-area";
import { init } from "@vanelsas/baredom/x-text-area";

init();

export interface XTextAreaProps {
  disabled?: boolean;
  name?: string;
  value?: string;
  minLength?: number;
  rows?: number;
  readOnly?: boolean;
  maxLength?: number;
  autocomplete?: string;
  required?: boolean;
  defaultValue?: string;
  onChangeRequest?: (e: CustomEvent<{ name: string; value: string; previousValue: string }>) => void;
  onInput?: (e: CustomEvent<{ name: string; value: string }>) => void;
  onChange?: (e: CustomEvent<{ name: string; value: string }>) => void;
  ref?: XTextAreaElement | ((el: XTextAreaElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XTextArea(props: XTextAreaProps): JSX.Element {
  const [local, others] = splitProps(props, ["value", "defaultValue", "onChangeRequest", "onInput", "onChange", "ref", "children"]);
  let el!: XTextAreaElement;

  const setRef = (r: XTextAreaElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el || local.value !== undefined || local.defaultValue === undefined) return;
    el.setAttribute("value", String(local.defaultValue));
  });

  createEffect(() => {
    if (!el) return;
    const v = local.value;
    if (v === undefined) return;
    el.setAttribute("value", String(v));
  });

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => {
        if (local.value !== undefined) e.preventDefault();
        local.onChangeRequest?.(e as CustomEvent<{ name: string; value: string; previousValue: string }>);
      };
      el.addEventListener("x-text-area-change-request", handler);
      onCleanup(() => el.removeEventListener("x-text-area-change-request", handler));
    }
    {
      const handler = (e: Event) => local.onInput?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-text-area-input", handler);
      onCleanup(() => el.removeEventListener("x-text-area-input", handler));
    }
    {
      const handler = (e: Event) => local.onChange?.(e as CustomEvent<{ name: string; value: string }>);
      el.addEventListener("x-text-area-change", handler);
      onCleanup(() => el.removeEventListener("x-text-area-change", handler));
    }
  });

  return (
    <x-text-area ref={setRef} {...others}>
      {local.children}
    </x-text-area>
  );
}
