// x-theme.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps } from "solid-js";
import type { JSX } from "solid-js";
import type { XTheme as XThemeElement } from "@vanelsas/baredom/x-theme";
import { init } from "@vanelsas/baredom/x-theme";

init();

export interface XThemeProps {
  preset?: string;
  ref?: XThemeElement | ((el: XThemeElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XTheme(props: XThemeProps): JSX.Element {
  const [local, others] = splitProps(props, ["ref", "children"]);
  let el!: XThemeElement;

  const setRef = (r: XThemeElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  return (
    <x-theme ref={setRef} {...others}>
      {local.children}
    </x-theme>
  );
}
