// x-toast.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XToast as XToastElement } from "@vanelsas/baredom/x-toast";
import { init } from "@vanelsas/baredom/x-toast";

init();

export interface XToastProps {
  type?: string;
  heading?: string;
  message?: string;
  icon?: string;
  dismissible?: boolean;
  disabled?: boolean;
  timeoutMs?: number;
  showProgress?: boolean;
  onDismiss?: (e: CustomEvent<{ type: string; reason: string; heading: string; message: string }>) => void;
  ref?: XToastElement | ((el: XToastElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XToast(props: XToastProps): JSX.Element {
  const [local, others] = splitProps(props, ["onDismiss", "ref", "children"]);
  let el!: XToastElement;

  const setRef = (r: XToastElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onDismiss?.(e as CustomEvent<{ type: string; reason: string; heading: string; message: string }>);
      el.addEventListener("x-toast-dismiss", handler);
      onCleanup(() => el.removeEventListener("x-toast-dismiss", handler));
    }
  });

  return (
    <x-toast ref={setRef} {...others}>
      {local.children}
    </x-toast>
  );
}
