// x-toaster.tsx — auto-generated by generate_solid.bb, do not edit
import { splitProps, onMount, onCleanup } from "solid-js";
import type { JSX } from "solid-js";
import type { XToaster as XToasterElement } from "@vanelsas/baredom/x-toaster";
import { init } from "@vanelsas/baredom/x-toaster";

init();

export interface XToasterProps {
  position?: string;
  maxToasts?: number;
  label?: string;
  onDismiss?: (e: CustomEvent<{ type: string; reason: string; heading: string; message: string }>) => void;
  ref?: XToasterElement | ((el: XToasterElement) => void);
  children?: JSX.Element;
  class?: string;
  style?: JSX.CSSProperties | string;
  id?: string;
  slot?: string;
}

export function XToaster(props: XToasterProps): JSX.Element {
  const [local, others] = splitProps(props, ["onDismiss", "ref", "children"]);
  let el!: XToasterElement;

  const setRef = (r: XToasterElement) => {
    el = r;
    if (typeof local.ref === "function") local.ref(r);
  };

  onMount(() => {
    if (!el) return;
    {
      const handler = (e: Event) => local.onDismiss?.(e as CustomEvent<{ type: string; reason: string; heading: string; message: string }>);
      el.addEventListener("x-toaster-dismiss", handler);
      onCleanup(() => el.removeEventListener("x-toaster-dismiss", handler));
    }
  });

  return (
    <x-toaster ref={setRef} {...others}>
      {local.children}
    </x-toaster>
  );
}
