// x-avatar-group.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XAvatarGroup as XAvatarGroupElement } from "@vanelsas/baredom/x-avatar-group";
import { init } from "@vanelsas/baredom/x-avatar-group";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XAvatarGroupExposed>(name)`. */
export interface XAvatarGroupExposed {
  readonly el: XAvatarGroupElement | null;
}

export const XAvatarGroup = defineComponent({
  name: "XAvatarGroup",
  inheritAttrs: false,
  props: {
    size: { type: String as PropType<string | undefined>, default: undefined },
    overlap: { type: String as PropType<string | undefined>, default: undefined },
    max: { type: Number as PropType<number | undefined>, default: undefined },
    direction: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XAvatarGroupElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-avatar-group" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XAvatarGroupInstance = InstanceType<typeof XAvatarGroup>;
