// x-avatar.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XAvatar as XAvatarElement } from "@vanelsas/baredom/x-avatar";
import { init } from "@vanelsas/baredom/x-avatar";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XAvatarExposed>(name)`. */
export interface XAvatarExposed {
  readonly el: XAvatarElement | null;
}

export const XAvatar = defineComponent({
  name: "XAvatar",
  inheritAttrs: false,
  props: {
    initials: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    variant: { type: String as PropType<string | undefined>, default: undefined },
    alt: { type: String as PropType<string | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    src: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    status: { type: String as PropType<string | undefined>, default: undefined },
    shape: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XAvatarElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-avatar" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XAvatarInstance = InstanceType<typeof XAvatar>;
