// x-bento-item.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref } from "vue";
import type { XBentoItem as XBentoItemElement } from "@vanelsas/baredom/x-bento-item";
import { init } from "@vanelsas/baredom/x-bento-item";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XBentoItemExposed>(name)`. */
export interface XBentoItemExposed {
  readonly el: XBentoItemElement | null;
}

export const XBentoItem = defineComponent({
  name: "XBentoItem",
  inheritAttrs: false,
  props: {},
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XBentoItemElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-bento-item" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XBentoItemInstance = InstanceType<typeof XBentoItem>;
