// x-bento-grid.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref } from "vue";
import type { XBentoGrid as XBentoGridElement } from "@vanelsas/baredom/x-bento-grid";
import { init } from "@vanelsas/baredom/x-bento-grid";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XBentoGridExposed>(name)`. */
export interface XBentoGridExposed {
  readonly el: XBentoGridElement | null;
}

export const XBentoGrid = defineComponent({
  name: "XBentoGrid",
  inheritAttrs: false,
  props: {},
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XBentoGridElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-bento-grid" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XBentoGridInstance = InstanceType<typeof XBentoGrid>;
