// x-button.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XButton as XButtonElement } from "@vanelsas/baredom/x-button";
import { init } from "@vanelsas/baredom/x-button";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XButtonExposed>(name)`. */
export interface XButtonExposed {
  readonly el: XButtonElement | null;
}

export const XButton = defineComponent({
  name: "XButton",
  inheritAttrs: false,
  props: {
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    loading: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    pressed: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "press": (_e: CustomEvent<{ source: string }>) => true,
    "press-start": (_e: CustomEvent<{ source: string }>) => true,
    "press-end": (_e: CustomEvent<{ source: string }>) => true,
    "hover-start": (_e: CustomEvent<{}>) => true,
    "hover-end": (_e: CustomEvent<{}>) => true,
    "focus-visible": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XButtonElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("press", e as CustomEvent);
        el.addEventListener("press", handler);
        cleanup.push(() => el.removeEventListener("press", handler));
      }
      {
        const handler = (e: Event) => emit("press-start", e as CustomEvent);
        el.addEventListener("press-start", handler);
        cleanup.push(() => el.removeEventListener("press-start", handler));
      }
      {
        const handler = (e: Event) => emit("press-end", e as CustomEvent);
        el.addEventListener("press-end", handler);
        cleanup.push(() => el.removeEventListener("press-end", handler));
      }
      {
        const handler = (e: Event) => emit("hover-start", e as CustomEvent);
        el.addEventListener("hover-start", handler);
        cleanup.push(() => el.removeEventListener("hover-start", handler));
      }
      {
        const handler = (e: Event) => emit("hover-end", e as CustomEvent);
        el.addEventListener("hover-end", handler);
        cleanup.push(() => el.removeEventListener("hover-end", handler));
      }
      {
        const handler = (e: Event) => emit("focus-visible", e as CustomEvent);
        el.addEventListener("focus-visible", handler);
        cleanup.push(() => el.removeEventListener("focus-visible", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-button" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XButtonInstance = InstanceType<typeof XButton>;
