// x-carousel.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XCarousel as XCarouselElement } from "@vanelsas/baredom/x-carousel";
import { init } from "@vanelsas/baredom/x-carousel";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XCarouselExposed>(name)`. */
export interface XCarouselExposed {
  readonly el: XCarouselElement | null;
}

export const XCarousel = defineComponent({
  name: "XCarousel",
  inheritAttrs: false,
  props: {
    arrows: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    transition: { type: String as PropType<string | undefined>, default: undefined },
    loop: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    interval: { type: Number as PropType<number | undefined>, default: undefined },
    autoplay: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    peek: { type: String as PropType<string | undefined>, default: undefined },
    dots: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    currentSlide: { type: Number as PropType<number | undefined>, default: undefined },
    direction: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "change": (_e: CustomEvent<{ index: number; previousIndex: number; reason: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XCarouselElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("change", e as CustomEvent);
        el.addEventListener("x-carousel-change", handler);
        cleanup.push(() => el.removeEventListener("x-carousel-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-carousel" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XCarouselInstance = InstanceType<typeof XCarousel>;
