// x-cancel-dialogue.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XCancelDialogue as XCancelDialogueElement } from "@vanelsas/baredom/x-cancel-dialogue";
import { init } from "@vanelsas/baredom/x-cancel-dialogue";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XCancelDialogueExposed>(name)`. */
export interface XCancelDialogueExposed {
  readonly el: XCancelDialogueElement | null;
}

export const XCancelDialogue = defineComponent({
  name: "XCancelDialogue",
  inheritAttrs: false,
  props: {
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    headline: { type: String as PropType<string | undefined>, default: undefined },
    message: { type: String as PropType<string | undefined>, default: undefined },
    confirmText: { type: String as PropType<string | undefined>, default: undefined },
    cancelText: { type: String as PropType<string | undefined>, default: undefined },
    danger: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "cancel-request": (_e: CustomEvent<{ reason: string }>) => true,
    "cancel": (_e: CustomEvent<{}>) => true,
    "confirm-request": (_e: CustomEvent<{}>) => true,
    "confirm": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XCancelDialogueElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("cancel-request", e as CustomEvent);
        el.addEventListener("x-cancel-dialogue-cancel-request", handler);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-cancel-request", handler));
      }
      {
        const handler = (e: Event) => emit("cancel", e as CustomEvent);
        el.addEventListener("x-cancel-dialogue-cancel", handler);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-cancel", handler));
      }
      {
        const handler = (e: Event) => emit("confirm-request", e as CustomEvent);
        el.addEventListener("x-cancel-dialogue-confirm-request", handler);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-confirm-request", handler));
      }
      {
        const handler = (e: Event) => emit("confirm", e as CustomEvent);
        el.addEventListener("x-cancel-dialogue-confirm", handler);
        cleanup.push(() => el.removeEventListener("x-cancel-dialogue-confirm", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-cancel-dialogue" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XCancelDialogueInstance = InstanceType<typeof XCancelDialogue>;
