// x-chip.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XChip as XChipElement } from "@vanelsas/baredom/x-chip";
import { init } from "@vanelsas/baredom/x-chip";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XChipExposed>(name)`. */
export interface XChipExposed {
  readonly el: XChipElement | null;
}

export const XChip = defineComponent({
  name: "XChip",
  inheritAttrs: false,
  props: {
    label: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    removable: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "remove": (_e: CustomEvent<{ value: string; label: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XChipElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("remove", e as CustomEvent);
        el.addEventListener("x-chip-remove", handler);
        cleanup.push(() => el.removeEventListener("x-chip-remove", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-chip" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XChipInstance = InstanceType<typeof XChip>;
