// x-checkbox.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, watch, type PropType } from "vue";
import type { XCheckbox as XCheckboxElement } from "@vanelsas/baredom/x-checkbox";
import { init } from "@vanelsas/baredom/x-checkbox";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XCheckboxExposed>(name)`. */
export interface XCheckboxExposed {
  readonly el: XCheckboxElement | null;
}

export const XCheckbox = defineComponent({
  name: "XCheckbox",
  inheritAttrs: false,
  props: {
    checked: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    indeterminate: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    readOnly: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    required: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    modelValue: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "update:modelValue": (_v: boolean) => true,
    "change-request": (_e: CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>) => true,
    "change": (_e: CustomEvent<{ value: string; checked: boolean }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XCheckboxElement | null>(null);
    const cleanup: Array<() => void> = [];

    const writeValue = (v: boolean | undefined) => {
      const el = elRef.value;
      if (!el || v === undefined) return;
      if (v) el.setAttribute("checked", "");
      else el.removeAttribute("checked");
    };

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;
      writeValue(props.modelValue);

      {
        const handler = (e: Event) => emit("change-request", e as CustomEvent);
        el.addEventListener("x-checkbox-change-request", handler);
        cleanup.push(() => el.removeEventListener("x-checkbox-change-request", handler));
      }
      {
        const handler = (e: Event) => {
          const detail = (e as CustomEvent).detail;
          emit("update:modelValue", Boolean(detail.checked));
          emit("change", e as CustomEvent);
        };
        el.addEventListener("x-checkbox-change", handler);
        cleanup.push(() => el.removeEventListener("x-checkbox-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    watch(() => props.modelValue, writeValue);

    expose({ el: elRef });

    return () => {
      const { modelValue: _modelValue, ...elProps } = props;
      void _modelValue;
      return h("x-checkbox" as any, { ...attrs, ref: elRef, ...elProps }, slots.default?.());
    };
  },
});

export type XCheckboxInstance = InstanceType<typeof XCheckbox>;
