// x-container.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XContainer as XContainerElement } from "@vanelsas/baredom/x-container";
import { init } from "@vanelsas/baredom/x-container";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XContainerExposed>(name)`. */
export interface XContainerExposed {
  readonly el: XContainerElement | null;
}

export const XContainer = defineComponent({
  name: "XContainer",
  inheritAttrs: false,
  props: {
    center: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    fluid: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XContainerElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-container" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XContainerInstance = InstanceType<typeof XContainer>;
