// x-collapse.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XCollapse as XCollapseElement } from "@vanelsas/baredom/x-collapse";
import { init } from "@vanelsas/baredom/x-collapse";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XCollapseExposed>(name)`. */
export interface XCollapseExposed {
  readonly el: XCollapseElement | null;
}

export const XCollapse = defineComponent({
  name: "XCollapse",
  inheritAttrs: false,
  props: {
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    header: { type: String as PropType<string | undefined>, default: undefined },
    durationMs: { type: Number as PropType<number | undefined>, default: undefined },
  },
  emits: {
    "toggle": (_e: CustomEvent<{ open: boolean; source: string }>) => true,
    "change": (_e: CustomEvent<{ open: boolean }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XCollapseElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("toggle", e as CustomEvent);
        el.addEventListener("x-collapse-toggle", handler);
        cleanup.push(() => el.removeEventListener("x-collapse-toggle", handler));
      }
      {
        const handler = (e: Event) => emit("change", e as CustomEvent);
        el.addEventListener("x-collapse-change", handler);
        cleanup.push(() => el.removeEventListener("x-collapse-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-collapse" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XCollapseInstance = InstanceType<typeof XCollapse>;
