// x-command-palette.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XCommandPalette as XCommandPaletteElement } from "@vanelsas/baredom/x-command-palette";
import { init } from "@vanelsas/baredom/x-command-palette";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XCommandPaletteExposed>(name)`. */
export interface XCommandPaletteExposed {
  readonly el: XCommandPaletteElement | null;
}

export const XCommandPalette = defineComponent({
  name: "XCommandPalette",
  inheritAttrs: false,
  props: {
    items: { type: Object as PropType<any | undefined>, default: undefined },
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "open-request": (_e: CustomEvent<{}>) => true,
    "open": (_e: CustomEvent<{}>) => true,
    "close-request": (_e: CustomEvent<{}>) => true,
    "close": (_e: CustomEvent<{}>) => true,
    "select-request": (_e: CustomEvent<{ item: Record<string, any> }>) => true,
    "select": (_e: CustomEvent<{ item: Record<string, any> }>) => true,
    "query-change": (_e: CustomEvent<{ query: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XCommandPaletteElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("open-request", e as CustomEvent);
        el.addEventListener("x-command-palette-open-request", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-open-request", handler));
      }
      {
        const handler = (e: Event) => emit("open", e as CustomEvent);
        el.addEventListener("x-command-palette-open", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-open", handler));
      }
      {
        const handler = (e: Event) => emit("close-request", e as CustomEvent);
        el.addEventListener("x-command-palette-close-request", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-close-request", handler));
      }
      {
        const handler = (e: Event) => emit("close", e as CustomEvent);
        el.addEventListener("x-command-palette-close", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-close", handler));
      }
      {
        const handler = (e: Event) => emit("select-request", e as CustomEvent);
        el.addEventListener("x-command-palette-select-request", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-select-request", handler));
      }
      {
        const handler = (e: Event) => emit("select", e as CustomEvent);
        el.addEventListener("x-command-palette-select", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-select", handler));
      }
      {
        const handler = (e: Event) => emit("query-change", e as CustomEvent);
        el.addEventListener("x-command-palette-query-change", handler);
        cleanup.push(() => el.removeEventListener("x-command-palette-query-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-command-palette" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XCommandPaletteInstance = InstanceType<typeof XCommandPalette>;
