// x-date-picker.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XDatePicker as XDatePickerElement } from "@vanelsas/baredom/x-date-picker";
import { init } from "@vanelsas/baredom/x-date-picker";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XDatePickerExposed>(name)`. */
export interface XDatePickerExposed {
  readonly el: XDatePickerElement | null;
}

export const XDatePicker = defineComponent({
  name: "XDatePicker",
  inheritAttrs: false,
  props: {
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    mode: { type: String as PropType<string | undefined>, default: undefined },
    start: { type: String as PropType<string | undefined>, default: undefined },
    readOnly: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    end: { type: String as PropType<string | undefined>, default: undefined },
    required: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "input": (_e: CustomEvent<{ value: string; mode: string }>) => true,
    "change-request": (_e: CustomEvent<{ value: string; mode: string; reason: string }>) => true,
    "change": (_e: CustomEvent<{ value: string; mode: string; reason: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XDatePickerElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("input", e as CustomEvent);
        el.addEventListener("x-date-picker-input", handler);
        cleanup.push(() => el.removeEventListener("x-date-picker-input", handler));
      }
      {
        const handler = (e: Event) => emit("change-request", e as CustomEvent);
        el.addEventListener("x-date-picker-change-request", handler);
        cleanup.push(() => el.removeEventListener("x-date-picker-change-request", handler));
      }
      {
        const handler = (e: Event) => emit("change", e as CustomEvent);
        el.addEventListener("x-date-picker-change", handler);
        cleanup.push(() => el.removeEventListener("x-date-picker-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-date-picker" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XDatePickerInstance = InstanceType<typeof XDatePicker>;
