// x-drag-panel.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XDragPanel as XDragPanelElement } from "@vanelsas/baredom/x-drag-panel";
import { init } from "@vanelsas/baredom/x-drag-panel";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XDragPanelExposed>(name)`. */
export interface XDragPanelExposed {
  readonly el: XDragPanelElement | null;
}

export const XDragPanel = defineComponent({
  name: "XDragPanel",
  inheritAttrs: false,
  props: {
    kind: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    grab: { type: String as PropType<string | undefined>, default: undefined },
    autoScroll: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    pending: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "drag-start": (_e: CustomEvent<{ kind: string; value: string }>) => true,
    "drag-cancel": (_e: CustomEvent<{ kind: string; value: string; reason: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XDragPanelElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("drag-start", e as CustomEvent);
        el.addEventListener("x-drag-panel-drag-start", handler);
        cleanup.push(() => el.removeEventListener("x-drag-panel-drag-start", handler));
      }
      {
        const handler = (e: Event) => emit("drag-cancel", e as CustomEvent);
        el.addEventListener("x-drag-panel-drag-cancel", handler);
        cleanup.push(() => el.removeEventListener("x-drag-panel-drag-cancel", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-drag-panel" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XDragPanelInstance = InstanceType<typeof XDragPanel>;
