// x-drop-zone.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XDropZone as XDropZoneElement } from "@vanelsas/baredom/x-drop-zone";
import { init } from "@vanelsas/baredom/x-drop-zone";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XDropZoneExposed>(name)`. */
export interface XDropZoneExposed {
  readonly el: XDropZoneElement | null;
}

export const XDropZone = defineComponent({
  name: "XDropZone",
  inheritAttrs: false,
  props: {
    accepts: { type: String as PropType<string | undefined>, default: undefined },
    max: { type: Number as PropType<number | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    pending: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    pendingIndex: { type: Number as PropType<number | undefined>, default: undefined },
    animateMoves: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "enter": (_e: CustomEvent<{ kind: string; value: string }>) => true,
    "leave": (_e: CustomEvent<{ kind: string; value: string }>) => true,
    "drop": (_e: CustomEvent<{ kind: string; value: string; panel: HTMLElement | null; index: number; fromZone: HTMLElement | null }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XDropZoneElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("enter", e as CustomEvent);
        el.addEventListener("x-drop-zone-enter", handler);
        cleanup.push(() => el.removeEventListener("x-drop-zone-enter", handler));
      }
      {
        const handler = (e: Event) => emit("leave", e as CustomEvent);
        el.addEventListener("x-drop-zone-leave", handler);
        cleanup.push(() => el.removeEventListener("x-drop-zone-leave", handler));
      }
      {
        const handler = (e: Event) => emit("drop", e as CustomEvent);
        el.addEventListener("x-drop-zone-drop", handler);
        cleanup.push(() => el.removeEventListener("x-drop-zone-drop", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-drop-zone" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XDropZoneInstance = InstanceType<typeof XDropZone>;
