// x-file-download.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XFileDownload as XFileDownloadElement } from "@vanelsas/baredom/x-file-download";
import { init } from "@vanelsas/baredom/x-file-download";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XFileDownloadExposed>(name)`. */
export interface XFileDownloadExposed {
  readonly el: XFileDownloadElement | null;
}

export const XFileDownload = defineComponent({
  name: "XFileDownload",
  inheritAttrs: false,
  props: {
    href: { type: String as PropType<string | undefined>, default: undefined },
    filename: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "click": (_e: CustomEvent<{ href: string; filename: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XFileDownloadElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("click", e as CustomEvent);
        el.addEventListener("x-file-download-click", handler);
        cleanup.push(() => el.removeEventListener("x-file-download-click", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-file-download" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XFileDownloadInstance = InstanceType<typeof XFileDownload>;
