// x-file-upload.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XFileUpload as XFileUploadElement } from "@vanelsas/baredom/x-file-upload";
import { init } from "@vanelsas/baredom/x-file-upload";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XFileUploadExposed>(name)`. */
export interface XFileUploadExposed {
  readonly el: XFileUploadElement | null;
}

export const XFileUpload = defineComponent({
  name: "XFileUpload",
  inheritAttrs: false,
  props: {
    accept: { type: String as PropType<string | undefined>, default: undefined },
    multiple: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    maxSize: { type: Number as PropType<number | undefined>, default: undefined },
    maxFiles: { type: Number as PropType<number | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    required: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "select": (_e: CustomEvent<{ files: any; rejected: any }>) => true,
    "remove": (_e: CustomEvent<{ file: Record<string, any>; remaining: any }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XFileUploadElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("select", e as CustomEvent);
        el.addEventListener("x-file-upload-select", handler);
        cleanup.push(() => el.removeEventListener("x-file-upload-select", handler));
      }
      {
        const handler = (e: Event) => emit("remove", e as CustomEvent);
        el.addEventListener("x-file-upload-remove", handler);
        cleanup.push(() => el.removeEventListener("x-file-upload-remove", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-file-upload" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XFileUploadInstance = InstanceType<typeof XFileUpload>;
