// x-fieldset.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XFieldset as XFieldsetElement } from "@vanelsas/baredom/x-fieldset";
import { init } from "@vanelsas/baredom/x-fieldset";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XFieldsetExposed>(name)`. */
export interface XFieldsetExposed {
  readonly el: XFieldsetElement | null;
}

export const XFieldset = defineComponent({
  name: "XFieldset",
  inheritAttrs: false,
  props: {
    legend: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XFieldsetElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-fieldset" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XFieldsetInstance = InstanceType<typeof XFieldset>;
