// x-floating-panel.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XFloatingPanel as XFloatingPanelElement } from "@vanelsas/baredom/x-floating-panel";
import { init } from "@vanelsas/baredom/x-floating-panel";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XFloatingPanelExposed>(name)`. */
export interface XFloatingPanelExposed {
  readonly el: XFloatingPanelElement | null;
}

export const XFloatingPanel = defineComponent({
  name: "XFloatingPanel",
  inheritAttrs: false,
  props: {
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    x: { type: Number as PropType<number | undefined>, default: undefined },
    y: { type: Number as PropType<number | undefined>, default: undefined },
    step: { type: Number as PropType<number | undefined>, default: undefined },
    closable: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    resizable: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    focusOnOpen: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "toggle": (_e: CustomEvent<{ open: boolean }>) => true,
    "dismiss-request": (_e: CustomEvent<{ reason: string }>) => true,
    "move": (_e: CustomEvent<{ x: number; y: number; source: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XFloatingPanelElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("toggle", e as CustomEvent);
        el.addEventListener("x-floating-panel-toggle", handler);
        cleanup.push(() => el.removeEventListener("x-floating-panel-toggle", handler));
      }
      {
        const handler = (e: Event) => emit("dismiss-request", e as CustomEvent);
        el.addEventListener("x-floating-panel-dismiss-request", handler);
        cleanup.push(() => el.removeEventListener("x-floating-panel-dismiss-request", handler));
      }
      {
        const handler = (e: Event) => emit("move", e as CustomEvent);
        el.addEventListener("x-floating-panel-move", handler);
        cleanup.push(() => el.removeEventListener("x-floating-panel-move", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-floating-panel" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XFloatingPanelInstance = InstanceType<typeof XFloatingPanel>;
