// x-form.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XForm as XFormElement } from "@vanelsas/baredom/x-form";
import { init } from "@vanelsas/baredom/x-form";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XFormExposed>(name)`. */
export interface XFormExposed {
  readonly el: XFormElement | null;
}

export const XForm = defineComponent({
  name: "XForm",
  inheritAttrs: false,
  props: {
    loading: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    novalidate: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    autocomplete: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "submit": (_e: CustomEvent<{ values: Record<string, any> }>) => true,
    "reset": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XFormElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("submit", e as CustomEvent);
        el.addEventListener("x-form-submit", handler);
        cleanup.push(() => el.removeEventListener("x-form-submit", handler));
      }
      {
        const handler = (e: Event) => emit("reset", e as CustomEvent);
        el.addEventListener("x-form-reset", handler);
        cleanup.push(() => el.removeEventListener("x-form-reset", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-form" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XFormInstance = InstanceType<typeof XForm>;
