// x-gaussian-blur.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XGaussianBlur as XGaussianBlurElement } from "@vanelsas/baredom/x-gaussian-blur";
import { init } from "@vanelsas/baredom/x-gaussian-blur";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XGaussianBlurExposed>(name)`. */
export interface XGaussianBlurExposed {
  readonly el: XGaussianBlurElement | null;
}

export const XGaussianBlur = defineComponent({
  name: "XGaussianBlur",
  inheritAttrs: false,
  props: {
    paused: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    animation: { type: String as PropType<string | undefined>, default: undefined },
    speed: { type: String as PropType<string | undefined>, default: undefined },
    colors: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    blur: { type: String as PropType<string | undefined>, default: undefined },
    opacity: { type: String as PropType<string | undefined>, default: undefined },
    count: { type: String as PropType<string | undefined>, default: undefined },
    blend: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XGaussianBlurElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-gaussian-blur" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XGaussianBlurInstance = InstanceType<typeof XGaussianBlur>;
