// x-grid.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XGrid as XGridElement } from "@vanelsas/baredom/x-grid";
import { init } from "@vanelsas/baredom/x-grid";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XGridExposed>(name)`. */
export interface XGridExposed {
  readonly el: XGridElement | null;
}

export const XGrid = defineComponent({
  name: "XGrid",
  inheritAttrs: false,
  props: {
    minColumnSize: { type: String as PropType<string | undefined>, default: undefined },
    rowGap: { type: String as PropType<string | undefined>, default: undefined },
    columns: { type: String as PropType<string | undefined>, default: undefined },
    autoFlow: { type: String as PropType<string | undefined>, default: undefined },
    gap: { type: String as PropType<string | undefined>, default: undefined },
    justifyItems: { type: String as PropType<string | undefined>, default: undefined },
    columnGap: { type: String as PropType<string | undefined>, default: undefined },
    inline: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    alignItems: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XGridElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-grid" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XGridInstance = InstanceType<typeof XGrid>;
