// x-i18n-provider.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XI18nProvider as XI18nProviderElement } from "@vanelsas/baredom/x-i18n-provider";
import { init } from "@vanelsas/baredom/x-i18n-provider";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XI18nProviderExposed>(name)`. */
export interface XI18nProviderExposed {
  readonly el: XI18nProviderElement | null;
}

export const XI18nProvider = defineComponent({
  name: "XI18nProvider",
  inheritAttrs: false,
  props: {
    src: { type: String as PropType<string | undefined>, default: undefined },
    locale: { type: String as PropType<string | undefined>, default: undefined },
    fallbackLocale: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "x-i18n-loading": (_e: CustomEvent<{ locale: string }>) => true,
    "x-i18n-change": (_e: CustomEvent<{ locale: string }>) => true,
    "x-i18n-error": (_e: CustomEvent<{ locale: string; message: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XI18nProviderElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("x-i18n-loading", e as CustomEvent);
        el.addEventListener("x-i18n-loading", handler);
        cleanup.push(() => el.removeEventListener("x-i18n-loading", handler));
      }
      {
        const handler = (e: Event) => emit("x-i18n-change", e as CustomEvent);
        el.addEventListener("x-i18n-change", handler);
        cleanup.push(() => el.removeEventListener("x-i18n-change", handler));
      }
      {
        const handler = (e: Event) => emit("x-i18n-error", e as CustomEvent);
        el.addEventListener("x-i18n-error", handler);
        cleanup.push(() => el.removeEventListener("x-i18n-error", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-i18n-provider" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XI18nProviderInstance = InstanceType<typeof XI18nProvider>;
