// x-kinetic-canvas.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XKineticCanvas as XKineticCanvasElement } from "@vanelsas/baredom/x-kinetic-canvas";
import { init } from "@vanelsas/baredom/x-kinetic-canvas";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XKineticCanvasExposed>(name)`. */
export interface XKineticCanvasExposed {
  readonly el: XKineticCanvasElement | null;
}

export const XKineticCanvas = defineComponent({
  name: "XKineticCanvas",
  inheritAttrs: false,
  props: {
    type: { type: String as PropType<string | undefined>, default: undefined },
    variant: { type: String as PropType<string | undefined>, default: undefined },
    speed: { type: String as PropType<string | undefined>, default: undefined },
    density: { type: String as PropType<string | undefined>, default: undefined },
    fullscreen: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    paused: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XKineticCanvasElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-kinetic-canvas" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XKineticCanvasInstance = InstanceType<typeof XKineticCanvas>;
