// x-kinetic-font.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XKineticFont as XKineticFontElement } from "@vanelsas/baredom/x-kinetic-font";
import { init } from "@vanelsas/baredom/x-kinetic-font";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XKineticFontExposed>(name)`. */
export interface XKineticFontExposed {
  readonly el: XKineticFontElement | null;
}

export const XKineticFont = defineComponent({
  name: "XKineticFont",
  inheritAttrs: false,
  props: {
    mass: { type: Number as PropType<number | undefined>, default: undefined },
    tension: { type: Number as PropType<number | undefined>, default: undefined },
    mode: { type: String as PropType<string | undefined>, default: undefined },
    perChar: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    radius: { type: Number as PropType<number | undefined>, default: undefined },
    intensity: { type: Number as PropType<number | undefined>, default: undefined },
    fontFamily: { type: String as PropType<string | undefined>, default: undefined },
    friction: { type: Number as PropType<number | undefined>, default: undefined },
    trigger: { type: String as PropType<string | undefined>, default: undefined },
    text: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "spring-activate": (_e: CustomEvent<{}>) => true,
    "spring-settle": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XKineticFontElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("spring-activate", e as CustomEvent);
        el.addEventListener("x-kinetic-font-spring-activate", handler);
        cleanup.push(() => el.removeEventListener("x-kinetic-font-spring-activate", handler));
      }
      {
        const handler = (e: Event) => emit("spring-settle", e as CustomEvent);
        el.addEventListener("x-kinetic-font-spring-settle", handler);
        cleanup.push(() => el.removeEventListener("x-kinetic-font-spring-settle", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-kinetic-font" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XKineticFontInstance = InstanceType<typeof XKineticFont>;
