// x-liquid-fill.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XLiquidFill as XLiquidFillElement } from "@vanelsas/baredom/x-liquid-fill";
import { init } from "@vanelsas/baredom/x-liquid-fill";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XLiquidFillExposed>(name)`. */
export interface XLiquidFillExposed {
  readonly el: XLiquidFillElement | null;
}

export const XLiquidFill = defineComponent({
  name: "XLiquidFill",
  inheritAttrs: false,
  props: {
    waveIntensity: { type: Number as PropType<number | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    splashIntensity: { type: Number as PropType<number | undefined>, default: undefined },
    mode: { type: String as PropType<string | undefined>, default: undefined },
    orientation: { type: String as PropType<string | undefined>, default: undefined },
    theme: { type: String as PropType<string | undefined>, default: undefined },
    layers: { type: Number as PropType<number | undefined>, default: undefined },
    target: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "progress": (_e: CustomEvent<{ progress: number; velocity: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XLiquidFillElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("progress", e as CustomEvent);
        el.addEventListener("x-liquid-fill-progress", handler);
        cleanup.push(() => el.removeEventListener("x-liquid-fill-progress", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-liquid-fill" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XLiquidFillInstance = InstanceType<typeof XLiquidFill>;
