// x-liquid-dock.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XLiquidDock as XLiquidDockElement } from "@vanelsas/baredom/x-liquid-dock";
import { init } from "@vanelsas/baredom/x-liquid-dock";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XLiquidDockExposed>(name)`. */
export interface XLiquidDockExposed {
  readonly el: XLiquidDockElement | null;
}

export const XLiquidDock = defineComponent({
  name: "XLiquidDock",
  inheritAttrs: false,
  props: {
    rippleScale: { type: Number as PropType<number | undefined>, default: undefined },
    color: { type: String as PropType<string | undefined>, default: undefined },
    magnetStrength: { type: Number as PropType<number | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    threshold: { type: String as PropType<string | undefined>, default: undefined },
    magnetRadius: { type: Number as PropType<number | undefined>, default: undefined },
    bobIntensity: { type: Number as PropType<number | undefined>, default: undefined },
    blur: { type: Number as PropType<number | undefined>, default: undefined },
    rippleSpeed: { type: Number as PropType<number | undefined>, default: undefined },
    gap: { type: Number as PropType<number | undefined>, default: undefined },
    position: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "select": (_e: CustomEvent<{ index: number; item: any; source: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XLiquidDockElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("select", e as CustomEvent);
        el.addEventListener("x-liquid-dock-select", handler);
        cleanup.push(() => el.removeEventListener("x-liquid-dock-select", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-liquid-dock" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XLiquidDockInstance = InstanceType<typeof XLiquidDock>;
