// x-liquid-glass.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XLiquidGlass as XLiquidGlassElement } from "@vanelsas/baredom/x-liquid-glass";
import { init } from "@vanelsas/baredom/x-liquid-glass";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XLiquidGlassExposed>(name)`. */
export interface XLiquidGlassExposed {
  readonly el: XLiquidGlassElement | null;
}

export const XLiquidGlass = defineComponent({
  name: "XLiquidGlass",
  inheritAttrs: false,
  props: {
    frost: { type: Number as PropType<number | undefined>, default: undefined },
    goo: { type: Number as PropType<number | undefined>, default: undefined },
    amplitude: { type: Number as PropType<number | undefined>, default: undefined },
    specularSize: { type: Number as PropType<number | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    speed: { type: Number as PropType<number | undefined>, default: undefined },
    mode: { type: String as PropType<string | undefined>, default: undefined },
    specular: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    tint: { type: String as PropType<string | undefined>, default: undefined },
    color2: { type: String as PropType<string | undefined>, default: undefined },
    blur: { type: Number as PropType<number | undefined>, default: undefined },
    blobs: { type: Number as PropType<number | undefined>, default: undefined },
    color1: { type: String as PropType<string | undefined>, default: undefined },
    specularIntensity: { type: Number as PropType<number | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XLiquidGlassElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-liquid-glass" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XLiquidGlassInstance = InstanceType<typeof XLiquidGlass>;
