// x-menu.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XMenu as XMenuElement } from "@vanelsas/baredom/x-menu";
import { init } from "@vanelsas/baredom/x-menu";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XMenuExposed>(name)`. */
export interface XMenuExposed {
  readonly el: XMenuElement | null;
}

export const XMenu = defineComponent({
  name: "XMenu",
  inheritAttrs: false,
  props: {
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    placement: { type: String as PropType<string | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "open": (_e: CustomEvent<{}>) => true,
    "close": (_e: CustomEvent<{}>) => true,
    "select": (_e: CustomEvent<{ value: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XMenuElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("open", e as CustomEvent);
        el.addEventListener("x-menu-open", handler);
        cleanup.push(() => el.removeEventListener("x-menu-open", handler));
      }
      {
        const handler = (e: Event) => emit("close", e as CustomEvent);
        el.addEventListener("x-menu-close", handler);
        cleanup.push(() => el.removeEventListener("x-menu-close", handler));
      }
      {
        const handler = (e: Event) => emit("select", e as CustomEvent);
        el.addEventListener("x-menu-select", handler);
        cleanup.push(() => el.removeEventListener("x-menu-select", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-menu" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XMenuInstance = InstanceType<typeof XMenu>;
