// x-metaball-cursor.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XMetaballCursor as XMetaballCursorElement } from "@vanelsas/baredom/x-metaball-cursor";
import { init } from "@vanelsas/baredom/x-metaball-cursor";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XMetaballCursorExposed>(name)`. */
export interface XMetaballCursorExposed {
  readonly el: XMetaballCursorElement | null;
}

export const XMetaballCursor = defineComponent({
  name: "XMetaballCursor",
  inheritAttrs: false,
  props: {
    color: { type: String as PropType<string | undefined>, default: undefined },
    blobSize: { type: Number as PropType<number | undefined>, default: undefined },
    noiseIntensity: { type: Number as PropType<number | undefined>, default: undefined },
    palette: { type: String as PropType<string | undefined>, default: undefined },
    noiseScale: { type: Number as PropType<number | undefined>, default: undefined },
    noise: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    threshold: { type: String as PropType<string | undefined>, default: undefined },
    blur: { type: Number as PropType<number | undefined>, default: undefined },
    noiseSpeed: { type: Number as PropType<number | undefined>, default: undefined },
    blobCount: { type: Number as PropType<number | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XMetaballCursorElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-metaball-cursor" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XMetaballCursorInstance = InstanceType<typeof XMetaballCursor>;
