// x-organic-divider.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XOrganicDivider as XOrganicDividerElement } from "@vanelsas/baredom/x-organic-divider";
import { init } from "@vanelsas/baredom/x-organic-divider";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XOrganicDividerExposed>(name)`. */
export interface XOrganicDividerExposed {
  readonly el: XOrganicDividerElement | null;
}

export const XOrganicDivider = defineComponent({
  name: "XOrganicDivider",
  inheritAttrs: false,
  props: {
    shape: { type: String as PropType<string | undefined>, default: undefined },
    layers: { type: String as PropType<string | undefined>, default: undefined },
    height: { type: String as PropType<string | undefined>, default: undefined },
    flip: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    mirror: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    animation: { type: String as PropType<string | undefined>, default: undefined },
    path: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XOrganicDividerElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-organic-divider" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XOrganicDividerInstance = InstanceType<typeof XOrganicDivider>;
