// x-pagination.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, watch, type PropType } from "vue";
import type { XPagination as XPaginationElement } from "@vanelsas/baredom/x-pagination";
import { init } from "@vanelsas/baredom/x-pagination";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XPaginationExposed>(name)`. */
export interface XPaginationExposed {
  readonly el: XPaginationElement | null;
}

export const XPagination = defineComponent({
  name: "XPagination",
  inheritAttrs: false,
  props: {
    page: { type: Number as PropType<number | undefined>, default: undefined },
    totalPages: { type: Number as PropType<number | undefined>, default: undefined },
    siblingCount: { type: Number as PropType<number | undefined>, default: undefined },
    boundaryCount: { type: Number as PropType<number | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    modelValue: { type: Number as PropType<number | undefined>, default: undefined },
  },
  emits: {
    "update:modelValue": (_v: number) => true,
    "page-change-request": (_e: CustomEvent<{ page: number; previousPage: number }>) => true,
    "page-change": (_e: CustomEvent<{ page: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XPaginationElement | null>(null);
    const cleanup: Array<() => void> = [];

    const writeValue = (v: number | undefined) => {
      const el = elRef.value;
      if (!el || v === undefined) return;
      if (v != null) el.setAttribute("page", String(v));
      else el.removeAttribute("page");
    };

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;
      writeValue(props.modelValue);

      {
        const handler = (e: Event) => emit("page-change-request", e as CustomEvent);
        el.addEventListener("page-change-request", handler);
        cleanup.push(() => el.removeEventListener("page-change-request", handler));
      }
      {
        const handler = (e: Event) => {
          const detail = (e as CustomEvent).detail;
          emit("update:modelValue", Number(detail.page));
          emit("page-change", e as CustomEvent);
        };
        el.addEventListener("page-change", handler);
        cleanup.push(() => el.removeEventListener("page-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    watch(() => props.modelValue, writeValue);

    expose({ el: elRef });

    return () => {
      const { modelValue: _modelValue, ...elProps } = props;
      void _modelValue;
      return h("x-pagination" as any, { ...attrs, ref: elRef, ...elProps }, slots.default?.());
    };
  },
});

export type XPaginationInstance = InstanceType<typeof XPagination>;
