// x-rating.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XRating as XRatingElement } from "@vanelsas/baredom/x-rating";
import { init } from "@vanelsas/baredom/x-rating";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XRatingExposed>(name)`. */
export interface XRatingExposed {
  readonly el: XRatingElement | null;
}

export const XRating = defineComponent({
  name: "XRating",
  inheritAttrs: false,
  props: {
    allowClear: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    precision: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    readOnly: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    max: { type: String as PropType<string | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    shape: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "change-request": (_e: CustomEvent<{ value: number; previousValue: number; max: number }>) => true,
    "change": (_e: CustomEvent<{ value: number; max: number }>) => true,
    "hover": (_e: CustomEvent<{ value: number; max: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XRatingElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("change-request", e as CustomEvent);
        el.addEventListener("x-rating-change-request", handler);
        cleanup.push(() => el.removeEventListener("x-rating-change-request", handler));
      }
      {
        const handler = (e: Event) => emit("change", e as CustomEvent);
        el.addEventListener("x-rating-change", handler);
        cleanup.push(() => el.removeEventListener("x-rating-change", handler));
      }
      {
        const handler = (e: Event) => emit("hover", e as CustomEvent);
        el.addEventListener("x-rating-hover", handler);
        cleanup.push(() => el.removeEventListener("x-rating-hover", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-rating" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XRatingInstance = InstanceType<typeof XRating>;
