// x-scroll-parallax.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XScrollParallax as XScrollParallaxElement } from "@vanelsas/baredom/x-scroll-parallax";
import { init } from "@vanelsas/baredom/x-scroll-parallax";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XScrollParallaxExposed>(name)`. */
export interface XScrollParallaxExposed {
  readonly el: XScrollParallaxElement | null;
}

export const XScrollParallax = defineComponent({
  name: "XScrollParallax",
  inheritAttrs: false,
  props: {
    direction: { type: String as PropType<string | undefined>, default: undefined },
    source: { type: String as PropType<string | undefined>, default: undefined },
    easing: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "enter": (_e: CustomEvent<{ progress: number }>) => true,
    "leave": (_e: CustomEvent<{ progress: number }>) => true,
    "progress": (_e: CustomEvent<{ progress: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XScrollParallaxElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("enter", e as CustomEvent);
        el.addEventListener("x-scroll-parallax-enter", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-parallax-enter", handler));
      }
      {
        const handler = (e: Event) => emit("leave", e as CustomEvent);
        el.addEventListener("x-scroll-parallax-leave", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-parallax-leave", handler));
      }
      {
        const handler = (e: Event) => emit("progress", e as CustomEvent);
        el.addEventListener("x-scroll-parallax-progress", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-parallax-progress", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-scroll-parallax" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XScrollParallaxInstance = InstanceType<typeof XScrollParallax>;
