// x-scroll-story.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XScrollStory as XScrollStoryElement } from "@vanelsas/baredom/x-scroll-story";
import { init } from "@vanelsas/baredom/x-scroll-story";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XScrollStoryExposed>(name)`. */
export interface XScrollStoryExposed {
  readonly el: XScrollStoryElement | null;
}

export const XScrollStory = defineComponent({
  name: "XScrollStory",
  inheritAttrs: false,
  props: {
    autoplayLoop: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    autoplaySpeed: { type: Number as PropType<number | undefined>, default: undefined },
    autoplayIndicator: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    layout: { type: String as PropType<string | undefined>, default: undefined },
    threshold: { type: Number as PropType<number | undefined>, default: undefined },
    split: { type: Number as PropType<number | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    autoplay: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "step-change": (_e: CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>) => true,
    "step-enter": (_e: CustomEvent<{ index: number; id: string; progress: number }>) => true,
    "step-leave": (_e: CustomEvent<{ index: number; id: string; progress: number }>) => true,
    "progress": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
    "enter": (_e: CustomEvent<{ progress: number }>) => true,
    "leave": (_e: CustomEvent<{ progress: number }>) => true,
    "autoplay-pause": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
    "autoplay-resume": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XScrollStoryElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("step-change", e as CustomEvent);
        el.addEventListener("x-scroll-story-step-change", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-step-change", handler));
      }
      {
        const handler = (e: Event) => emit("step-enter", e as CustomEvent);
        el.addEventListener("x-scroll-story-step-enter", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-step-enter", handler));
      }
      {
        const handler = (e: Event) => emit("step-leave", e as CustomEvent);
        el.addEventListener("x-scroll-story-step-leave", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-step-leave", handler));
      }
      {
        const handler = (e: Event) => emit("progress", e as CustomEvent);
        el.addEventListener("x-scroll-story-progress", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-progress", handler));
      }
      {
        const handler = (e: Event) => emit("enter", e as CustomEvent);
        el.addEventListener("x-scroll-story-enter", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-enter", handler));
      }
      {
        const handler = (e: Event) => emit("leave", e as CustomEvent);
        el.addEventListener("x-scroll-story-leave", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-leave", handler));
      }
      {
        const handler = (e: Event) => emit("autoplay-pause", e as CustomEvent);
        el.addEventListener("x-scroll-story-autoplay-pause", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-autoplay-pause", handler));
      }
      {
        const handler = (e: Event) => emit("autoplay-resume", e as CustomEvent);
        el.addEventListener("x-scroll-story-autoplay-resume", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-story-autoplay-resume", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-scroll-story" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XScrollStoryInstance = InstanceType<typeof XScrollStory>;
