// x-scroll-timeline.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XScrollTimeline as XScrollTimelineElement } from "@vanelsas/baredom/x-scroll-timeline";
import { init } from "@vanelsas/baredom/x-scroll-timeline";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XScrollTimelineExposed>(name)`. */
export interface XScrollTimelineExposed {
  readonly el: XScrollTimelineElement | null;
}

export const XScrollTimeline = defineComponent({
  name: "XScrollTimeline",
  inheritAttrs: false,
  props: {
    autoplayLoop: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    autoplaySpeed: { type: Number as PropType<number | undefined>, default: undefined },
    autoplayIndicator: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    layout: { type: String as PropType<string | undefined>, default: undefined },
    marker: { type: String as PropType<string | undefined>, default: undefined },
    threshold: { type: Number as PropType<number | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    autoplay: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    noProgress: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    track: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "entry-change": (_e: CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>) => true,
    "entry-enter": (_e: CustomEvent<{ index: number; id: string; progress: number }>) => true,
    "entry-leave": (_e: CustomEvent<{ index: number; id: string; progress: number }>) => true,
    "progress": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
    "enter": (_e: CustomEvent<{ progress: number }>) => true,
    "leave": (_e: CustomEvent<{ progress: number }>) => true,
    "autoplay-pause": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
    "autoplay-resume": (_e: CustomEvent<{ progress: number; activeIndex: number; activeId: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XScrollTimelineElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("entry-change", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-entry-change", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-change", handler));
      }
      {
        const handler = (e: Event) => emit("entry-enter", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-entry-enter", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-enter", handler));
      }
      {
        const handler = (e: Event) => emit("entry-leave", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-entry-leave", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-entry-leave", handler));
      }
      {
        const handler = (e: Event) => emit("progress", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-progress", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-progress", handler));
      }
      {
        const handler = (e: Event) => emit("enter", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-enter", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-enter", handler));
      }
      {
        const handler = (e: Event) => emit("leave", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-leave", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-leave", handler));
      }
      {
        const handler = (e: Event) => emit("autoplay-pause", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-autoplay-pause", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-autoplay-pause", handler));
      }
      {
        const handler = (e: Event) => emit("autoplay-resume", e as CustomEvent);
        el.addEventListener("x-scroll-timeline-autoplay-resume", handler);
        cleanup.push(() => el.removeEventListener("x-scroll-timeline-autoplay-resume", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-scroll-timeline" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XScrollTimelineInstance = InstanceType<typeof XScrollTimeline>;
