// x-select.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, watch, type PropType } from "vue";
import type { XSelect as XSelectElement } from "@vanelsas/baredom/x-select";
import { init } from "@vanelsas/baredom/x-select";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XSelectExposed>(name)`. */
export interface XSelectExposed {
  readonly el: XSelectElement | null;
}

export const XSelect = defineComponent({
  name: "XSelect",
  inheritAttrs: false,
  props: {
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    required: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    modelValue: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "update:modelValue": (_v: string) => true,
    "change-request": (_e: CustomEvent<{ value: string; label: string; previousValue: string }>) => true,
    "select-change": (_e: CustomEvent<{ value: string; label: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XSelectElement | null>(null);
    const cleanup: Array<() => void> = [];

    const writeValue = (v: string | undefined) => {
      const el = elRef.value;
      if (!el || v === undefined) return;
      if (v != null) el.setAttribute("value", String(v));
      else el.removeAttribute("value");
    };

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;
      writeValue(props.modelValue);

      {
        const handler = (e: Event) => emit("change-request", e as CustomEvent);
        el.addEventListener("x-select-change-request", handler);
        cleanup.push(() => el.removeEventListener("x-select-change-request", handler));
      }
      {
        const handler = (e: Event) => {
          const detail = (e as CustomEvent).detail;
          emit("update:modelValue", String(detail.value));
          emit("select-change", e as CustomEvent);
        };
        el.addEventListener("select-change", handler);
        cleanup.push(() => el.removeEventListener("select-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    watch(() => props.modelValue, writeValue);

    expose({ el: elRef });

    return () => {
      const { modelValue: _modelValue, ...elProps } = props;
      void _modelValue;
      return h("x-select" as any, { ...attrs, ref: elRef, ...elProps }, slots.default?.());
    };
  },
});

export type XSelectInstance = InstanceType<typeof XSelect>;
