// x-skeleton-group.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XSkeletonGroup as XSkeletonGroupElement } from "@vanelsas/baredom/x-skeleton-group";
import { init } from "@vanelsas/baredom/x-skeleton-group";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XSkeletonGroupExposed>(name)`. */
export interface XSkeletonGroupExposed {
  readonly el: XSkeletonGroupElement | null;
}

export const XSkeletonGroup = defineComponent({
  name: "XSkeletonGroup",
  inheritAttrs: false,
  props: {
    preset: { type: String as PropType<string | undefined>, default: undefined },
    animation: { type: String as PropType<string | undefined>, default: undefined },
    count: { type: Number as PropType<number | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XSkeletonGroupElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-skeleton-group" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XSkeletonGroupInstance = InstanceType<typeof XSkeletonGroup>;
