// x-slider.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, watch, type PropType } from "vue";
import type { XSlider as XSliderElement } from "@vanelsas/baredom/x-slider";
import { init } from "@vanelsas/baredom/x-slider";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XSliderExposed>(name)`. */
export interface XSliderExposed {
  readonly el: XSliderElement | null;
}

export const XSlider = defineComponent({
  name: "XSlider",
  inheritAttrs: false,
  props: {
    min: { type: String as PropType<string | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    showValue: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    name: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    readOnly: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    max: { type: String as PropType<string | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    step: { type: String as PropType<string | undefined>, default: undefined },
    modelValue: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "update:modelValue": (_v: string) => true,
    "change-request": (_e: CustomEvent<{ value: number; previousValue: number; min: number; max: number }>) => true,
    "input": (_e: CustomEvent<{ value: number; min: number; max: number }>) => true,
    "change": (_e: CustomEvent<{ value: number; min: number; max: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XSliderElement | null>(null);
    const cleanup: Array<() => void> = [];

    const writeValue = (v: string | undefined) => {
      const el = elRef.value;
      if (!el || v === undefined) return;
      if (v != null) el.setAttribute("value", String(v));
      else el.removeAttribute("value");
    };

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;
      writeValue(props.modelValue);

      {
        const handler = (e: Event) => emit("change-request", e as CustomEvent);
        el.addEventListener("x-slider-change-request", handler);
        cleanup.push(() => el.removeEventListener("x-slider-change-request", handler));
      }
      {
        const handler = (e: Event) => emit("input", e as CustomEvent);
        el.addEventListener("x-slider-input", handler);
        cleanup.push(() => el.removeEventListener("x-slider-input", handler));
      }
      {
        const handler = (e: Event) => {
          const detail = (e as CustomEvent).detail;
          emit("update:modelValue", String(detail.value));
          emit("change", e as CustomEvent);
        };
        el.addEventListener("x-slider-change", handler);
        cleanup.push(() => el.removeEventListener("x-slider-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    watch(() => props.modelValue, writeValue);

    expose({ el: elRef });

    return () => {
      const { modelValue: _modelValue, ...elProps } = props;
      void _modelValue;
      return h("x-slider" as any, { ...attrs, ref: elRef, ...elProps }, slots.default?.());
    };
  },
});

export type XSliderInstance = InstanceType<typeof XSlider>;
