// x-spotlight-card.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XSpotlightCard as XSpotlightCardElement } from "@vanelsas/baredom/x-spotlight-card";
import { init } from "@vanelsas/baredom/x-spotlight-card";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XSpotlightCardExposed>(name)`. */
export interface XSpotlightCardExposed {
  readonly el: XSpotlightCardElement | null;
}

export const XSpotlightCard = defineComponent({
  name: "XSpotlightCard",
  inheritAttrs: false,
  props: {
    variant: { type: String as PropType<string | undefined>, default: undefined },
    radius: { type: String as PropType<string | undefined>, default: undefined },
    padding: { type: String as PropType<string | undefined>, default: undefined },
    color: { type: String as PropType<string | undefined>, default: undefined },
    intensity: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    static: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XSpotlightCardElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-spotlight-card" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XSpotlightCardInstance = InstanceType<typeof XSpotlightCard>;
