// x-spinner.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XSpinner as XSpinnerElement } from "@vanelsas/baredom/x-spinner";
import { init } from "@vanelsas/baredom/x-spinner";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XSpinnerExposed>(name)`. */
export interface XSpinnerExposed {
  readonly el: XSpinnerElement | null;
}

export const XSpinner = defineComponent({
  name: "XSpinner",
  inheritAttrs: false,
  props: {
    size: { type: String as PropType<string | undefined>, default: undefined },
    variant: { type: String as PropType<string | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XSpinnerElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-spinner" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XSpinnerInstance = InstanceType<typeof XSpinner>;
