// x-stat.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, type PropType } from "vue";
import type { XStat as XStatElement } from "@vanelsas/baredom/x-stat";
import { init } from "@vanelsas/baredom/x-stat";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XStatExposed>(name)`. */
export interface XStatExposed {
  readonly el: XStatElement | null;
}

export const XStat = defineComponent({
  name: "XStat",
  inheritAttrs: false,
  props: {
    trend: { type: String as PropType<string | undefined>, default: undefined },
    align: { type: String as PropType<string | undefined>, default: undefined },
    variant: { type: String as PropType<string | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
    hint: { type: String as PropType<string | undefined>, default: undefined },
    size: { type: String as PropType<string | undefined>, default: undefined },
    loading: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    label: { type: String as PropType<string | undefined>, default: undefined },
    emphasis: { type: String as PropType<string | undefined>, default: undefined },
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XStatElement | null>(null);

    expose({ el: elRef });

    return () => {
      return h("x-stat" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XStatInstance = InstanceType<typeof XStat>;
