// x-table.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XTable as XTableElement } from "@vanelsas/baredom/x-table";
import { init } from "@vanelsas/baredom/x-table";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XTableExposed>(name)`. */
export interface XTableExposed {
  readonly el: XTableElement | null;
}

export const XTable = defineComponent({
  name: "XTable",
  inheritAttrs: false,
  props: {
    columns: { type: String as PropType<string | undefined>, default: undefined },
    caption: { type: String as PropType<string | undefined>, default: undefined },
    selectable: { type: String as PropType<string | undefined>, default: undefined },
    striped: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    bordered: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    fullWidth: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    compact: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    rowCount: { type: Number as PropType<number | undefined>, default: undefined },
  },
  emits: {
    "sort": (_e: CustomEvent<{ colIndex: number; direction: string; previousDirection: string }>) => true,
    "row-select": (_e: CustomEvent<{ rowIndex: number; selected: boolean; selectionMode: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XTableElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("sort", e as CustomEvent);
        el.addEventListener("x-table-sort", handler);
        cleanup.push(() => el.removeEventListener("x-table-sort", handler));
      }
      {
        const handler = (e: Event) => emit("row-select", e as CustomEvent);
        el.addEventListener("x-table-row-select", handler);
        cleanup.push(() => el.removeEventListener("x-table-row-select", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-table" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XTableInstance = InstanceType<typeof XTable>;
