// x-tab.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XTab as XTabElement } from "@vanelsas/baredom/x-tab";
import { init } from "@vanelsas/baredom/x-tab";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XTabExposed>(name)`. */
export interface XTabExposed {
  readonly el: XTabElement | null;
}

export const XTab = defineComponent({
  name: "XTab",
  inheritAttrs: false,
  props: {
    selected: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    value: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "tab-select": (_e: CustomEvent<{ value: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XTabElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("tab-select", e as CustomEvent);
        el.addEventListener("tab-select", handler);
        cleanup.push(() => el.removeEventListener("tab-select", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-tab" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XTabInstance = InstanceType<typeof XTab>;
