// x-tabs.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, watch, type PropType } from "vue";
import type { XTabs as XTabsElement } from "@vanelsas/baredom/x-tabs";
import { init } from "@vanelsas/baredom/x-tabs";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XTabsExposed>(name)`. */
export interface XTabsExposed {
  readonly el: XTabsElement | null;
}

export const XTabs = defineComponent({
  name: "XTabs",
  inheritAttrs: false,
  props: {
    value: { type: String as PropType<string | undefined>, default: undefined },
    modelValue: { type: String as PropType<string | undefined>, default: undefined },
  },
  emits: {
    "update:modelValue": (_v: string) => true,
    "value-change-request": (_e: CustomEvent<{ value: string; previousValue: string }>) => true,
    "value-change": (_e: CustomEvent<{ value: string }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XTabsElement | null>(null);
    const cleanup: Array<() => void> = [];

    const writeValue = (v: string | undefined) => {
      const el = elRef.value;
      if (!el || v === undefined) return;
      if (v != null) el.setAttribute("value", String(v));
      else el.removeAttribute("value");
    };

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;
      writeValue(props.modelValue);

      {
        const handler = (e: Event) => emit("value-change-request", e as CustomEvent);
        el.addEventListener("value-change-request", handler);
        cleanup.push(() => el.removeEventListener("value-change-request", handler));
      }
      {
        const handler = (e: Event) => {
          const detail = (e as CustomEvent).detail;
          emit("update:modelValue", String(detail.value));
          emit("value-change", e as CustomEvent);
        };
        el.addEventListener("value-change", handler);
        cleanup.push(() => el.removeEventListener("value-change", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    watch(() => props.modelValue, writeValue);

    expose({ el: elRef });

    return () => {
      const { modelValue: _modelValue, ...elProps } = props;
      void _modelValue;
      return h("x-tabs" as any, { ...attrs, ref: elRef, ...elProps }, slots.default?.());
    };
  },
});

export type XTabsInstance = InstanceType<typeof XTabs>;
