// x-table-row.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XTableRow as XTableRowElement } from "@vanelsas/baredom/x-table-row";
import { init } from "@vanelsas/baredom/x-table-row";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XTableRowExposed>(name)`. */
export interface XTableRowExposed {
  readonly el: XTableRowElement | null;
}

export const XTableRow = defineComponent({
  name: "XTableRow",
  inheritAttrs: false,
  props: {
    selected: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    interactive: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    rowIndex: { type: Number as PropType<number | undefined>, default: undefined },
  },
  emits: {
    "click": (_e: CustomEvent<{ rowIndex: number; selected: boolean; disabled: boolean }>) => true,
    "connected": (_e: CustomEvent<{ rowIndex: number; selected: boolean; disabled: boolean; interactive: boolean }>) => true,
    "disconnected": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XTableRowElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("click", e as CustomEvent);
        el.addEventListener("x-table-row-click", handler);
        cleanup.push(() => el.removeEventListener("x-table-row-click", handler));
      }
      {
        const handler = (e: Event) => emit("connected", e as CustomEvent);
        el.addEventListener("x-table-row-connected", handler);
        cleanup.push(() => el.removeEventListener("x-table-row-connected", handler));
      }
      {
        const handler = (e: Event) => emit("disconnected", e as CustomEvent);
        el.addEventListener("x-table-row-disconnected", handler);
        cleanup.push(() => el.removeEventListener("x-table-row-disconnected", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-table-row" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XTableRowInstance = InstanceType<typeof XTableRow>;
