// x-tooltip.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XTooltip as XTooltipElement } from "@vanelsas/baredom/x-tooltip";
import { init } from "@vanelsas/baredom/x-tooltip";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XTooltipExposed>(name)`. */
export interface XTooltipExposed {
  readonly el: XTooltipElement | null;
}

export const XTooltip = defineComponent({
  name: "XTooltip",
  inheritAttrs: false,
  props: {
    text: { type: String as PropType<string | undefined>, default: undefined },
    placement: { type: String as PropType<string | undefined>, default: undefined },
    delay: { type: Number as PropType<number | undefined>, default: undefined },
    disabled: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
  },
  emits: {
    "show": (_e: CustomEvent<{}>) => true,
    "hide": (_e: CustomEvent<{}>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XTooltipElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("show", e as CustomEvent);
        el.addEventListener("x-tooltip-show", handler);
        cleanup.push(() => el.removeEventListener("x-tooltip-show", handler));
      }
      {
        const handler = (e: Event) => emit("hide", e as CustomEvent);
        el.addEventListener("x-tooltip-hide", handler);
        cleanup.push(() => el.removeEventListener("x-tooltip-hide", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-tooltip" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XTooltipInstance = InstanceType<typeof XTooltip>;
