// x-welcome-tour.ts — auto-generated by generate_vue.bb, do not edit

import { defineComponent, h, ref, onMounted, onBeforeUnmount, type PropType } from "vue";
import type { XWelcomeTour as XWelcomeTourElement } from "@vanelsas/baredom/x-welcome-tour";
import { init } from "@vanelsas/baredom/x-welcome-tour";

init();

/** Shape exposed via `expose()` — use with `useTemplateRef<XWelcomeTourExposed>(name)`. */
export interface XWelcomeTourExposed {
  readonly el: XWelcomeTourElement | null;
}

export const XWelcomeTour = defineComponent({
  name: "XWelcomeTour",
  inheritAttrs: false,
  props: {
    connector: { type: String as PropType<string | undefined>, default: undefined },
    open: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    prevLabel: { type: String as PropType<string | undefined>, default: undefined },
    nextLabel: { type: String as PropType<string | undefined>, default: undefined },
    counter: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    doneLabel: { type: String as PropType<string | undefined>, default: undefined },
    skipLabel: { type: String as PropType<string | undefined>, default: undefined },
    dots: { type: Boolean as PropType<boolean | undefined>, default: undefined },
    step: { type: Number as PropType<number | undefined>, default: undefined },
  },
  emits: {
    "start": (_e: CustomEvent<{}>) => true,
    "step-change": (_e: CustomEvent<{ step: number; previousStep: number }>) => true,
    "complete": (_e: CustomEvent<{ stepsCompleted: number }>) => true,
    "skip": (_e: CustomEvent<{ step: number }>) => true,
  },
  setup(props, { emit, attrs, slots, expose }) {
    const elRef = ref<XWelcomeTourElement | null>(null);
    const cleanup: Array<() => void> = [];

    onMounted(() => {
      const el = elRef.value;
      if (!el) return;

      {
        const handler = (e: Event) => emit("start", e as CustomEvent);
        el.addEventListener("x-welcome-tour-start", handler);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-start", handler));
      }
      {
        const handler = (e: Event) => emit("step-change", e as CustomEvent);
        el.addEventListener("x-welcome-tour-step-change", handler);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-step-change", handler));
      }
      {
        const handler = (e: Event) => emit("complete", e as CustomEvent);
        el.addEventListener("x-welcome-tour-complete", handler);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-complete", handler));
      }
      {
        const handler = (e: Event) => emit("skip", e as CustomEvent);
        el.addEventListener("x-welcome-tour-skip", handler);
        cleanup.push(() => el.removeEventListener("x-welcome-tour-skip", handler));
      }
    });

    onBeforeUnmount(() => {
      cleanup.forEach((fn) => fn());
    });

    expose({ el: elRef });

    return () => {
      return h("x-welcome-tour" as any, { ...attrs, ref: elRef, ...props }, slots.default?.());
    };
  },
});

export type XWelcomeTourInstance = InstanceType<typeof XWelcomeTour>;
