// x-badge.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XBadge as XBadgeElement } from '@vanelsas/baredom/x-badge';
import { init } from '@vanelsas/baredom/x-badge';

init();

@Directive({ selector: 'x-badge', standalone: true })
export class BaredomBadge {
  private el: XBadgeElement;

  constructor(elRef: ElementRef<XBadgeElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set variant(v: string) { this.el.variant = v as any; }
  @Input() set size(v: string) { this.el.size = v as any; }
  @Input() set pill(v: boolean) { this.el.pill = v as any; }
  @Input() set dot(v: boolean) { this.el.dot = v as any; }
  @Input() set count(v: number) { this.el.count = v as any; }
  @Input() set max(v: number) { this.el.max = v as any; }
  @Input() set text(v: string) { this.el.text = v as any; }

}
