// x-bento-grid.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef } from '@angular/core';
import type { XBentoGrid as XBentoGridElement } from '@vanelsas/baredom/x-bento-grid';
import { init } from '@vanelsas/baredom/x-bento-grid';

init();

@Directive({ selector: 'x-bento-grid', standalone: true })
export class BaredomBentoGrid {
  private el: XBentoGridElement;

  constructor(elRef: ElementRef<XBentoGridElement>) {
    this.el = elRef.nativeElement;
  }



}
