// x-bento-item.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef } from '@angular/core';
import type { XBentoItem as XBentoItemElement } from '@vanelsas/baredom/x-bento-item';
import { init } from '@vanelsas/baredom/x-bento-item';

init();

@Directive({ selector: 'x-bento-item', standalone: true })
export class BaredomBentoItem {
  private el: XBentoItemElement;

  constructor(elRef: ElementRef<XBentoItemElement>) {
    this.el = elRef.nativeElement;
  }



}
