// x-calendar.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XCalendar as XCalendarElement } from '@vanelsas/baredom/x-calendar';
import { init } from '@vanelsas/baredom/x-calendar';

init();

@Directive({ selector: 'x-calendar', standalone: true })
export class BaredomCalendar implements OnInit, OnDestroy {
  private el: XCalendarElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XCalendarElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set min(v: string) { this.el.min = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set locale(v: string) { this.el.locale = v as any; }
  @Input() set autoSwap(v: boolean) { this.el.autoSwap = v as any; }
  @Input() set value(v: string) { this.el.value = v as any; }
  @Input() set mode(v: string) { this.el.mode = v as any; }
  @Input() set start(v: string) { this.el.start = v as any; }
  @Input() set month(v: string) { this.el.month = v as any; }
  @Input() set showWeekNumbers(v: boolean) { this.el.showWeekNumbers = v as any; }
  @Input() set disabledDates(v: string) { this.el.disabledDates = v as any; }
  @Input() set max(v: string) { this.el.max = v as any; }
  @Input() set firstDayOfWeek(v: string) { this.el.firstDayOfWeek = v as any; }
  @Input() set end(v: string) { this.el.end = v as any; }
  @Input() set rangeAllowSameDay(v: boolean) { this.el.rangeAllowSameDay = v as any; }

  @Output() change = new EventEmitter<CustomEvent<{ value: string; start: string; end: string; mode: string }>>();
  @Output() navigate = new EventEmitter<CustomEvent<{ month: string }>>();

  ngOnInit(): void {
    this.listen('x-calendar-change', this.change);
    this.listen('x-calendar-navigate', this.navigate);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

  focus(): void { return this.el.focus(); }
  goToMonth(month: string): void { return this.el.goToMonth(month); }
  clear(): void { return this.el.clear(); }
}
