// x-chart.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XChart as XChartElement } from '@vanelsas/baredom/x-chart';
import { init } from '@vanelsas/baredom/x-chart';

init();

@Directive({ selector: 'x-chart', standalone: true })
export class BaredomChart implements OnInit, OnDestroy {
  private el: XChartElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XChartElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set selected(v: string) { this.el.selected = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set axes(v: boolean) { this.el.axes = v as any; }
  @Input() set grid(v: boolean) { this.el.grid = v as any; }
  @Input() set cursor(v: string) { this.el.cursor = v as any; }
  @Input() set type(v: string) { this.el.type = v as any; }
  @Input() set loading(v: boolean) { this.el.loading = v as any; }
  @Input() set padding(v: number) { this.el.padding = v as any; }
  @Input() set tooltip(v: boolean) { this.el.tooltip = v as any; }
  @Input() set height(v: number) { this.el.height = v as any; }
  @Input() set data(v: any) { this.el.data = v as any; }

  @Output() select = new EventEmitter<CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>>();
  @Output() hover = new EventEmitter<CustomEvent<{ seriesId: string; index: number; x: number; y: number; value: number }>>();

  ngOnInit(): void {
    this.listen('x-chart-select', this.select);
    this.listen('x-chart-hover', this.hover);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
