// x-checkbox.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XCheckbox as XCheckboxElement } from '@vanelsas/baredom/x-checkbox';
import { init } from '@vanelsas/baredom/x-checkbox';

init();

@Directive({ selector: 'x-checkbox', standalone: true })
export class BaredomCheckbox implements OnInit, OnDestroy {
  private el: XCheckboxElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XCheckboxElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set checked(v: boolean) { this.el.checked = v as any; }
  @Input() set indeterminate(v: boolean) { this.el.indeterminate = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set readOnly(v: boolean) { this.el.readOnly = v as any; }
  @Input() set required(v: boolean) { this.el.required = v as any; }
  @Input() set name(v: string) { this.el.name = v as any; }
  @Input() set value(v: string) { this.el.value = v as any; }

  @Output() changeRequest = new EventEmitter<CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>>();
  @Output() change = new EventEmitter<CustomEvent<{ value: string; checked: boolean }>>();

  ngOnInit(): void {
    this.listen('x-checkbox-change-request', this.changeRequest);
    this.listen('x-checkbox-change', this.change);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
