// x-confetti.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XConfetti as XConfettiElement } from '@vanelsas/baredom/x-confetti';
import { init } from '@vanelsas/baredom/x-confetti';

init();

@Directive({ selector: 'x-confetti', standalone: true })
export class BaredomConfetti implements OnInit, OnDestroy {
  private el: XConfettiElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XConfettiElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set spread(v: number) { this.el.spread = v as any; }
  @Input() set mode(v: string) { this.el.mode = v as any; }
  @Input() set colors(v: string) { this.el.colors = v as any; }
  @Input() set duration(v: number) { this.el.duration = v as any; }
  @Input() set autoFire(v: boolean) { this.el.autoFire = v as any; }
  @Input() set gravity(v: number) { this.el.gravity = v as any; }
  @Input() set count(v: number) { this.el.count = v as any; }
  @Input() set origin(v: string) { this.el.origin = v as any; }
  @Input() set velocity(v: number) { this.el.velocity = v as any; }
  @Input() set shapes(v: string) { this.el.shapes = v as any; }

  @Output() fire = new EventEmitter<CustomEvent<{ count: number; origin: string }>>();
  @Output() end = new EventEmitter<CustomEvent<{ duration: number }>>();

  ngOnInit(): void {
    this.listen('x-confetti-fire', this.fire);
    this.listen('x-confetti-end', this.end);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

  fireMethod(options: Record<string, any>): void { return this.el.fire(options); }
}
