// x-container.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XContainer as XContainerElement } from '@vanelsas/baredom/x-container';
import { init } from '@vanelsas/baredom/x-container';

init();

@Directive({ selector: 'x-container', standalone: true })
export class BaredomContainer {
  private el: XContainerElement;

  constructor(elRef: ElementRef<XContainerElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set center(v: boolean) { this.el.center = v as any; }
  @Input() set fluid(v: boolean) { this.el.fluid = v as any; }
  @Input() set as(v: string) { this.el.as = v as any; }
  @Input() set size(v: string) { this.el.size = v as any; }
  @Input() set padding(v: string) { this.el.padding = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }

}
