// x-color-picker.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XColorPicker as XColorPickerElement } from '@vanelsas/baredom/x-color-picker';
import { init } from '@vanelsas/baredom/x-color-picker';

init();

@Directive({ selector: 'x-color-picker', standalone: true })
export class BaredomColorPicker implements OnInit, OnDestroy {
  private el: XColorPickerElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XColorPickerElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set open(v: boolean) { this.el.open = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set name(v: string) { this.el.name = v as any; }
  @Input() set value(v: string) { this.el.value = v as any; }
  @Input() set mode(v: string) { this.el.mode = v as any; }
  @Input() set swatches(v: string) { this.el.swatches = v as any; }
  @Input() set readOnly(v: boolean) { this.el.readOnly = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }
  @Input() set alpha(v: boolean) { this.el.alpha = v as any; }

  @Output() input = new EventEmitter<CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>>();
  @Output() change = new EventEmitter<CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>>();

  ngOnInit(): void {
    this.listen('x-color-picker-input', this.input);
    this.listen('x-color-picker-change', this.change);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
