// x-combobox.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XCombobox as XComboboxElement } from '@vanelsas/baredom/x-combobox';
import { init } from '@vanelsas/baredom/x-combobox';

init();

@Directive({ selector: 'x-combobox', standalone: true })
export class BaredomCombobox implements OnInit, OnDestroy {
  private el: XComboboxElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XComboboxElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set value(v: string) { this.el.value = v as any; }
  @Input() set placeholder(v: string) { this.el.placeholder = v as any; }
  @Input() set name(v: string) { this.el.name = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set required(v: boolean) { this.el.required = v as any; }
  @Input() set open(v: boolean) { this.el.open = v as any; }
  @Input() set placement(v: string) { this.el.placement = v as any; }

  @Output() changeRequest = new EventEmitter<CustomEvent<{ value: string; label: string; previousValue: string }>>();
  @Output() change = new EventEmitter<CustomEvent<{ value: string; label: string }>>();
  @Output() input = new EventEmitter<CustomEvent<{ query: string }>>();
  @Output() toggle = new EventEmitter<CustomEvent<{ open: boolean; source: string }>>();

  ngOnInit(): void {
    this.listen('x-combobox-change-request', this.changeRequest);
    this.listen('x-combobox-change', this.change);
    this.listen('x-combobox-input', this.input);
    this.listen('x-combobox-toggle', this.toggle);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
