// x-drop-zone.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XDropZone as XDropZoneElement } from '@vanelsas/baredom/x-drop-zone';
import { init } from '@vanelsas/baredom/x-drop-zone';

init();

@Directive({ selector: 'x-drop-zone', standalone: true })
export class BaredomDropZone implements OnInit, OnDestroy {
  private el: XDropZoneElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XDropZoneElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set value(v: string) { this.el.value = v as any; }
  @Input() set accepts(v: string) { this.el.accepts = v as any; }
  @Input() set max(v: number) { this.el.max = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set pending(v: boolean) { this.el.pending = v as any; }
  @Input() set pendingIndex(v: number) { this.el.pendingIndex = v as any; }
  @Input() set animateMoves(v: boolean) { this.el.animateMoves = v as any; }

  @Output() enter = new EventEmitter<CustomEvent<{ kind: string; value: string }>>();
  @Output() leave = new EventEmitter<CustomEvent<{ kind: string; value: string }>>();
  @Output() drop = new EventEmitter<CustomEvent<{ kind: string; value: string; from: string | null; to: string; index: number; panel: HTMLElement }>>();

  ngOnInit(): void {
    this.listen('x-drop-zone-enter', this.enter);
    this.listen('x-drop-zone-leave', this.leave);
    this.listen('x-drop-zone-drop', this.drop);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

  reserve(panel: HTMLElement, index: number): void { return this.el.reserve(panel, index); }
  release(): void { return this.el.release(); }
}
