// x-dropdown.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XDropdown as XDropdownElement } from '@vanelsas/baredom/x-dropdown';
import { init } from '@vanelsas/baredom/x-dropdown';

init();

@Directive({ selector: 'x-dropdown', standalone: true })
export class BaredomDropdown implements OnInit, OnDestroy {
  private el: XDropdownElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XDropdownElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set open(v: boolean) { this.el.open = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }
  @Input() set placement(v: string) { this.el.placement = v as any; }

  @Output() toggle = new EventEmitter<CustomEvent<{ open: boolean; source: string }>>();
  @Output() change = new EventEmitter<CustomEvent<{ open: boolean }>>();

  ngOnInit(): void {
    this.listen('x-dropdown-toggle', this.toggle);
    this.listen('x-dropdown-change', this.change);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
