// x-file-download.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XFileDownload as XFileDownloadElement } from '@vanelsas/baredom/x-file-download';
import { init } from '@vanelsas/baredom/x-file-download';

init();

@Directive({ selector: 'x-file-download', standalone: true })
export class BaredomFileDownload implements OnInit, OnDestroy {
  private el: XFileDownloadElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XFileDownloadElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set href(v: string) { this.el.href = v as any; }
  @Input() set filename(v: string) { this.el.filename = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set picker(v: boolean) { this.el.picker = v as any; }

  @Output() click = new EventEmitter<CustomEvent<{ href: string; filename: string }>>();
  @Output() success = new EventEmitter<CustomEvent<{ filename: string }>>();
  @Output() cancel = new EventEmitter<CustomEvent<{}>>();
  @Output() error = new EventEmitter<CustomEvent<{ error: string; phase: string }>>();

  ngOnInit(): void {
    this.listen('x-file-download-click', this.click);
    this.listen('x-file-download-success', this.success);
    this.listen('x-file-download-cancel', this.cancel);
    this.listen('x-file-download-error', this.error);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
