// x-form.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XForm as XFormElement } from '@vanelsas/baredom/x-form';
import { init } from '@vanelsas/baredom/x-form';

init();

@Directive({ selector: 'x-form', standalone: true })
export class BaredomForm implements OnInit, OnDestroy {
  private el: XFormElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XFormElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set loading(v: boolean) { this.el.loading = v as any; }
  @Input() set novalidate(v: boolean) { this.el.novalidate = v as any; }
  @Input() set autocomplete(v: string) { this.el.autocomplete = v as any; }

  @Output() submit = new EventEmitter<CustomEvent<{ values: Record<string, any> }>>();
  @Output() reset = new EventEmitter<CustomEvent<{}>>();

  ngOnInit(): void {
    this.listen('x-form-submit', this.submit);
    this.listen('x-form-reset', this.reset);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
