// x-grid.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XGrid as XGridElement } from '@vanelsas/baredom/x-grid';
import { init } from '@vanelsas/baredom/x-grid';

init();

@Directive({ selector: 'x-grid', standalone: true })
export class BaredomGrid {
  private el: XGridElement;

  constructor(elRef: ElementRef<XGridElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set minColumnSize(v: string) { this.el.minColumnSize = v as any; }
  @Input() set rowGap(v: string) { this.el.rowGap = v as any; }
  @Input() set columns(v: string) { this.el.columns = v as any; }
  @Input() set autoFlow(v: string) { this.el.autoFlow = v as any; }
  @Input() set gap(v: string) { this.el.gap = v as any; }
  @Input() set justifyItems(v: string) { this.el.justifyItems = v as any; }
  @Input() set columnGap(v: string) { this.el.columnGap = v as any; }
  @Input() set inline(v: boolean) { this.el.inline = v as any; }
  @Input() set alignItems(v: string) { this.el.alignItems = v as any; }

}
