// x-grid.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef } from '@angular/core';
import type { XGrid as XGridElement } from '@vanelsas/baredom/x-grid';
import { init } from '@vanelsas/baredom/x-grid';

init();

@Directive({ selector: 'x-grid', standalone: true })
export class BaredomGrid {
  private el: XGridElement;

  constructor(elRef: ElementRef<XGridElement>) {
    this.el = elRef.nativeElement;
  }



}
