// x-i18n-provider.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XI18nProvider as XI18nProviderElement } from '@vanelsas/baredom/x-i18n-provider';
import { init } from '@vanelsas/baredom/x-i18n-provider';

init();

@Directive({ selector: 'x-i18n-provider', standalone: true })
export class BaredomI18nProvider implements OnInit, OnDestroy {
  private el: XI18nProviderElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XI18nProviderElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set src(v: string) { this.el.src = v as any; }
  @Input() set locale(v: string) { this.el.locale = v as any; }
  @Input() set fallbackLocale(v: string) { this.el.fallbackLocale = v as any; }

  @Output() xI18nLoading = new EventEmitter<CustomEvent<{ locale: string }>>();
  @Output() xI18nChange = new EventEmitter<CustomEvent<{ locale: string }>>();
  @Output() xI18nError = new EventEmitter<CustomEvent<{ locale: string; message: string }>>();

  ngOnInit(): void {
    this.listen('x-i18n-loading', this.xI18nLoading);
    this.listen('x-i18n-change', this.xI18nChange);
    this.listen('x-i18n-error', this.xI18nError);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

  translateSubtree(): void { return this.el.translateSubtree(); }
}
