// x-image.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XImage as XImageElement } from '@vanelsas/baredom/x-image';
import { init } from '@vanelsas/baredom/x-image';

init();

@Directive({ selector: 'x-image', standalone: true })
export class BaredomImage implements OnInit, OnDestroy {
  private el: XImageElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XImageElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set alt(v: string) { this.el.alt = v as any; }
  @Input() set fit(v: string) { this.el.fit = v as any; }
  @Input() set src(v: string) { this.el.src = v as any; }
  @Input() set decorative(v: boolean) { this.el.decorative = v as any; }
  @Input() set loading(v: string) { this.el.loading = v as any; }
  @Input() set ratio(v: string) { this.el.ratio = v as any; }
  @Input() set position(v: string) { this.el.position = v as any; }

  @Output() load = new EventEmitter<CustomEvent<{ src: string; naturalWidth: number; naturalHeight: number }>>();
  @Output() error = new EventEmitter<CustomEvent<{ src: string }>>();

  ngOnInit(): void {
    this.listen('x-image-load', this.load);
    this.listen('x-image-error', this.error);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
