// x-kbd.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XKbd as XKbdElement } from '@vanelsas/baredom/x-kbd';
import { init } from '@vanelsas/baredom/x-kbd';

init();

@Directive({ selector: 'x-kbd', standalone: true })
export class BaredomKbd {
  private el: XKbdElement;

  constructor(elRef: ElementRef<XKbdElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set keys(v: string) { this.el.keys = v as any; }
  @Input() set separator(v: string) { this.el.separator = v as any; }
  @Input() set size(v: string) { this.el.size = v as any; }
  @Input() set platform(v: string) { this.el.platform = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }

}
