// x-kinetic-canvas.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XKineticCanvas as XKineticCanvasElement } from '@vanelsas/baredom/x-kinetic-canvas';
import { init } from '@vanelsas/baredom/x-kinetic-canvas';

init();

@Directive({ selector: 'x-kinetic-canvas', standalone: true })
export class BaredomKineticCanvas {
  private el: XKineticCanvasElement;

  constructor(elRef: ElementRef<XKineticCanvasElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set type(v: string) { this.el.type = v as any; }
  @Input() set variant(v: string) { this.el.variant = v as any; }
  @Input() set speed(v: string) { this.el.speed = v as any; }
  @Input() set density(v: string) { this.el.density = v as any; }
  @Input() set fullscreen(v: boolean) { this.el.fullscreen = v as any; }
  @Input() set paused(v: boolean) { this.el.paused = v as any; }

}
