// x-liquid-dock.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XLiquidDock as XLiquidDockElement } from '@vanelsas/baredom/x-liquid-dock';
import { init } from '@vanelsas/baredom/x-liquid-dock';

init();

@Directive({ selector: 'x-liquid-dock', standalone: true })
export class BaredomLiquidDock implements OnInit, OnDestroy {
  private el: XLiquidDockElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XLiquidDockElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set rippleScale(v: number) { this.el.rippleScale = v as any; }
  @Input() set color(v: string) { this.el.color = v as any; }
  @Input() set magnetStrength(v: number) { this.el.magnetStrength = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set threshold(v: string) { this.el.threshold = v as any; }
  @Input() set magnetRadius(v: number) { this.el.magnetRadius = v as any; }
  @Input() set bobIntensity(v: number) { this.el.bobIntensity = v as any; }
  @Input() set blur(v: number) { this.el.blur = v as any; }
  @Input() set rippleSpeed(v: number) { this.el.rippleSpeed = v as any; }
  @Input() set gap(v: number) { this.el.gap = v as any; }
  @Input() set position(v: string) { this.el.position = v as any; }

  @Output() select = new EventEmitter<CustomEvent<{ index: number; item: any; source: string }>>();

  ngOnInit(): void {
    this.listen('x-liquid-dock-select', this.select);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
