// x-neural-glow.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XNeuralGlow as XNeuralGlowElement } from '@vanelsas/baredom/x-neural-glow';
import { init } from '@vanelsas/baredom/x-neural-glow';

init();

@Directive({ selector: 'x-neural-glow', standalone: true })
export class BaredomNeuralGlow {
  private el: XNeuralGlowElement;

  constructor(elRef: ElementRef<XNeuralGlowElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set colorBackground(v: string) { this.el.colorBackground = v as any; }
  @Input() set interactive(v: boolean) { this.el.interactive = v as any; }
  @Input() set orbCount(v: number) { this.el.orbCount = v as any; }
  @Input() set restRate(v: number) { this.el.restRate = v as any; }
  @Input() set colorPrimary(v: string) { this.el.colorPrimary = v as any; }
  @Input() set orbSize(v: number) { this.el.orbSize = v as any; }
  @Input() set opacity(v: number) { this.el.opacity = v as any; }
  @Input() set colorSecondary(v: string) { this.el.colorSecondary = v as any; }
  @Input() set pulseSpeed(v: number) { this.el.pulseSpeed = v as any; }
  @Input() set connectionDistance(v: number) { this.el.connectionDistance = v as any; }

}
