// x-notification-center.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XNotificationCenter as XNotificationCenterElement } from '@vanelsas/baredom/x-notification-center';
import { init } from '@vanelsas/baredom/x-notification-center';

init();

@Directive({ selector: 'x-notification-center', standalone: true })
export class BaredomNotificationCenter implements OnInit, OnDestroy {
  private el: XNotificationCenterElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XNotificationCenterElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set position(v: string) { this.el.position = v as any; }
  @Input() set max(v: number) { this.el.max = v as any; }

  @Output() push = new EventEmitter<CustomEvent<{ id: string; count: number }>>();
  @Output() dismiss = new EventEmitter<CustomEvent<{ id: string; type: string; reason: string; text: string; count: number }>>();
  @Output() empty = new EventEmitter<CustomEvent<{}>>();

  ngOnInit(): void {
    this.listen('x-notification-center-push', this.push);
    this.listen('x-notification-center-dismiss', this.dismiss);
    this.listen('x-notification-center-empty', this.empty);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
