// x-organic-shape.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XOrganicShape as XOrganicShapeElement } from '@vanelsas/baredom/x-organic-shape';
import { init } from '@vanelsas/baredom/x-organic-shape';

init();

@Directive({ selector: 'x-organic-shape', standalone: true })
export class BaredomOrganicShape {
  private el: XOrganicShapeElement;

  constructor(elRef: ElementRef<XOrganicShapeElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set shape(v: string) { this.el.shape = v as any; }
  @Input() set path(v: string) { this.el.path = v as any; }
  @Input() set animation(v: string) { this.el.animation = v as any; }
  @Input() set ratio(v: string) { this.el.ratio = v as any; }
  @Input() set width(v: string) { this.el.width = v as any; }
  @Input() set height(v: string) { this.el.height = v as any; }

}
