// x-organic-divider.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XOrganicDivider as XOrganicDividerElement } from '@vanelsas/baredom/x-organic-divider';
import { init } from '@vanelsas/baredom/x-organic-divider';

init();

@Directive({ selector: 'x-organic-divider', standalone: true })
export class BaredomOrganicDivider {
  private el: XOrganicDividerElement;

  constructor(elRef: ElementRef<XOrganicDividerElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set shape(v: string) { this.el.shape = v as any; }
  @Input() set layers(v: string) { this.el.layers = v as any; }
  @Input() set height(v: string) { this.el.height = v as any; }
  @Input() set flip(v: boolean) { this.el.flip = v as any; }
  @Input() set mirror(v: boolean) { this.el.mirror = v as any; }
  @Input() set animation(v: string) { this.el.animation = v as any; }
  @Input() set path(v: string) { this.el.path = v as any; }

}
