// x-organic-progress.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XOrganicProgress as XOrganicProgressElement } from '@vanelsas/baredom/x-organic-progress';
import { init } from '@vanelsas/baredom/x-organic-progress';

init();

@Directive({ selector: 'x-organic-progress', standalone: true })
export class BaredomOrganicProgress implements OnInit, OnDestroy {
  private el: XOrganicProgressElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XOrganicProgressElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set progress(v: string) { this.el.progress = v as any; }
  @Input() set variant(v: string) { this.el.variant = v as any; }
  @Input() set color(v: string) { this.el.color = v as any; }
  @Input() set bloom(v: boolean) { this.el.bloom = v as any; }
  @Input() set density(v: string) { this.el.density = v as any; }
  @Input() set seed(v: number) { this.el.seed = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }

  @Output() complete = new EventEmitter<CustomEvent<{ progress: number }>>();
  @Output() bloomEnd = new EventEmitter<CustomEvent<{ progress: number }>>();

  ngOnInit(): void {
    this.listen('x-organic-progress-complete', this.complete);
    this.listen('x-organic-progress-bloom-end', this.bloomEnd);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
