// x-pagination.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XPagination as XPaginationElement } from '@vanelsas/baredom/x-pagination';
import { init } from '@vanelsas/baredom/x-pagination';

init();

@Directive({ selector: 'x-pagination', standalone: true })
export class BaredomPagination implements OnInit, OnDestroy {
  private el: XPaginationElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XPaginationElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set page(v: number) { this.el.page = v as any; }
  @Input() set totalPages(v: number) { this.el.totalPages = v as any; }
  @Input() set siblingCount(v: number) { this.el.siblingCount = v as any; }
  @Input() set boundaryCount(v: number) { this.el.boundaryCount = v as any; }
  @Input() set size(v: string) { this.el.size = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }

  @Output() pageChangeRequest = new EventEmitter<CustomEvent<{ page: number; previousPage: number }>>();
  @Output() pageChange = new EventEmitter<CustomEvent<{ page: number }>>();

  ngOnInit(): void {
    this.listen('page-change-request', this.pageChangeRequest);
    this.listen('page-change', this.pageChange);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
