// x-popover.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XPopover as XPopoverElement } from '@vanelsas/baredom/x-popover';
import { init } from '@vanelsas/baredom/x-popover';

init();

@Directive({ selector: 'x-popover', standalone: true })
export class BaredomPopover implements OnInit, OnDestroy {
  private el: XPopoverElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XPopoverElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set open(v: boolean) { this.el.open = v as any; }
  @Input() set placement(v: string) { this.el.placement = v as any; }
  @Input() set heading(v: string) { this.el.heading = v as any; }
  @Input() set closeLabel(v: string) { this.el.closeLabel = v as any; }
  @Input() set noClose(v: boolean) { this.el.noClose = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set portal(v: boolean) { this.el.portal = v as any; }

  @Output() toggle = new EventEmitter<CustomEvent<{ open: boolean; source: string }>>();
  @Output() change = new EventEmitter<CustomEvent<{ open: boolean }>>();

  ngOnInit(): void {
    this.listen('x-popover-toggle', this.toggle);
    this.listen('x-popover-change', this.change);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
