// x-ripple-effect.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XRippleEffect as XRippleEffectElement } from '@vanelsas/baredom/x-ripple-effect';
import { init } from '@vanelsas/baredom/x-ripple-effect';

init();

@Directive({ selector: 'x-ripple-effect', standalone: true })
export class BaredomRippleEffect implements OnInit, OnDestroy {
  private el: XRippleEffectElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XRippleEffectElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set intensity(v: number) { this.el.intensity = v as any; }
  @Input() set duration(v: number) { this.el.duration = v as any; }
  @Input() set frequency(v: number) { this.el.frequency = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }

  @Output() start = new EventEmitter<CustomEvent<{ x: number; y: number }>>();
  @Output() end = new EventEmitter<CustomEvent<{ x: number; y: number }>>();

  ngOnInit(): void {
    this.listen('x-ripple-effect-start', this.start);
    this.listen('x-ripple-effect-end', this.end);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
