// x-scroll-story.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XScrollStory as XScrollStoryElement } from '@vanelsas/baredom/x-scroll-story';
import { init } from '@vanelsas/baredom/x-scroll-story';

init();

@Directive({ selector: 'x-scroll-story', standalone: true })
export class BaredomScrollStory implements OnInit, OnDestroy {
  private el: XScrollStoryElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XScrollStoryElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set autoplayLoop(v: boolean) { this.el.autoplayLoop = v as any; }
  @Input() set autoplaySpeed(v: number) { this.el.autoplaySpeed = v as any; }
  @Input() set autoplayIndicator(v: boolean) { this.el.autoplayIndicator = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set layout(v: string) { this.el.layout = v as any; }
  @Input() set threshold(v: number) { this.el.threshold = v as any; }
  @Input() set split(v: number) { this.el.split = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }
  @Input() set autoplay(v: boolean) { this.el.autoplay = v as any; }

  @Output() stepChange = new EventEmitter<CustomEvent<{ index: number; id: string; previousIndex: number; previousId: string }>>();
  @Output() stepEnter = new EventEmitter<CustomEvent<{ index: number; id: string; progress: number }>>();
  @Output() stepLeave = new EventEmitter<CustomEvent<{ index: number; id: string; progress: number }>>();
  @Output() progress = new EventEmitter<CustomEvent<{ progress: number; activeIndex: number; activeId: string }>>();
  @Output() enter = new EventEmitter<CustomEvent<{ progress: number }>>();
  @Output() leave = new EventEmitter<CustomEvent<{ progress: number }>>();
  @Output() autoplayPause = new EventEmitter<CustomEvent<{ progress: number; activeIndex: number; activeId: string }>>();
  @Output() autoplayResume = new EventEmitter<CustomEvent<{ progress: number; activeIndex: number; activeId: string }>>();

  ngOnInit(): void {
    this.listen('x-scroll-story-step-change', this.stepChange);
    this.listen('x-scroll-story-step-enter', this.stepEnter);
    this.listen('x-scroll-story-step-leave', this.stepLeave);
    this.listen('x-scroll-story-progress', this.progress);
    this.listen('x-scroll-story-enter', this.enter);
    this.listen('x-scroll-story-leave', this.leave);
    this.listen('x-scroll-story-autoplay-pause', this.autoplayPause);
    this.listen('x-scroll-story-autoplay-resume', this.autoplayResume);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
