// x-scroll-parallax.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XScrollParallax as XScrollParallaxElement } from '@vanelsas/baredom/x-scroll-parallax';
import { init } from '@vanelsas/baredom/x-scroll-parallax';

init();

@Directive({ selector: 'x-scroll-parallax', standalone: true })
export class BaredomScrollParallax implements OnInit, OnDestroy {
  private el: XScrollParallaxElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XScrollParallaxElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set direction(v: string) { this.el.direction = v as any; }
  @Input() set source(v: string) { this.el.source = v as any; }
  @Input() set easing(v: string) { this.el.easing = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set label(v: string) { this.el.label = v as any; }

  @Output() enter = new EventEmitter<CustomEvent<{ progress: number }>>();
  @Output() leave = new EventEmitter<CustomEvent<{ progress: number }>>();
  @Output() progress = new EventEmitter<CustomEvent<{ progress: number }>>();

  ngOnInit(): void {
    this.listen('x-scroll-parallax-enter', this.enter);
    this.listen('x-scroll-parallax-leave', this.leave);
    this.listen('x-scroll-parallax-progress', this.progress);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
