// x-select.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XSelect as XSelectElement } from '@vanelsas/baredom/x-select';
import { init } from '@vanelsas/baredom/x-select';

init();

@Directive({ selector: 'x-select', standalone: true })
export class BaredomSelect implements OnInit, OnDestroy {
  private el: XSelectElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XSelectElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set required(v: boolean) { this.el.required = v as any; }
  @Input() set value(v: string) { this.el.value = v as any; }

  @Output() changeRequest = new EventEmitter<CustomEvent<{ value: string; label: string; previousValue: string }>>();
  @Output() selectChange = new EventEmitter<CustomEvent<{ value: string; label: string }>>();

  ngOnInit(): void {
    this.listen('x-select-change-request', this.changeRequest);
    this.listen('select-change', this.selectChange);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
