// x-skeleton-group.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XSkeletonGroup as XSkeletonGroupElement } from '@vanelsas/baredom/x-skeleton-group';
import { init } from '@vanelsas/baredom/x-skeleton-group';

init();

@Directive({ selector: 'x-skeleton-group', standalone: true })
export class BaredomSkeletonGroup {
  private el: XSkeletonGroupElement;

  constructor(elRef: ElementRef<XSkeletonGroupElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set preset(v: string) { this.el.preset = v as any; }
  @Input() set animation(v: string) { this.el.animation = v as any; }
  @Input() set count(v: number) { this.el.count = v as any; }

}
