// x-soft-body.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XSoftBody as XSoftBodyElement } from '@vanelsas/baredom/x-soft-body';
import { init } from '@vanelsas/baredom/x-soft-body';

init();

@Directive({ selector: 'x-soft-body', standalone: true })
export class BaredomSoftBody implements OnInit, OnDestroy {
  private el: XSoftBodyElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XSoftBodyElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set stiffness(v: number) { this.el.stiffness = v as any; }
  @Input() set damping(v: number) { this.el.damping = v as any; }
  @Input() set radius(v: number) { this.el.radius = v as any; }
  @Input() set intensity(v: number) { this.el.intensity = v as any; }
  @Input() set grabRadius(v: number) { this.el.grabRadius = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }

  @Output() grab = new EventEmitter<CustomEvent<{}>>();
  @Output() release = new EventEmitter<CustomEvent<{}>>();

  ngOnInit(): void {
    this.listen('x-soft-body-grab', this.grab);
    this.listen('x-soft-body-release', this.release);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
