// x-split-pane.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XSplitPane as XSplitPaneElement } from '@vanelsas/baredom/x-split-pane';
import { init } from '@vanelsas/baredom/x-split-pane';

init();

@Directive({ selector: 'x-split-pane', standalone: true })
export class BaredomSplitPane implements OnInit, OnDestroy {
  private el: XSplitPaneElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XSplitPaneElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set orientation(v: string) { this.el.orientation = v as any; }
  @Input() set position(v: number) { this.el.position = v as any; }
  @Input() set minStart(v: number) { this.el.minStart = v as any; }
  @Input() set minEnd(v: number) { this.el.minEnd = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set dividerLabel(v: string) { this.el.dividerLabel = v as any; }

  @Output() resize = new EventEmitter<CustomEvent<{ position: number; orientation: string }>>();
  @Output() resizeEnd = new EventEmitter<CustomEvent<{ position: number; orientation: string }>>();

  ngOnInit(): void {
    this.listen('x-split-pane-resize', this.resize);
    this.listen('x-split-pane-resize-end', this.resizeEnd);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
