// x-tabs.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XTabs as XTabsElement } from '@vanelsas/baredom/x-tabs';
import { init } from '@vanelsas/baredom/x-tabs';

init();

@Directive({ selector: 'x-tabs', standalone: true })
export class BaredomTabs implements OnInit, OnDestroy {
  private el: XTabsElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XTabsElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set value(v: string) { this.el.value = v as any; }

  @Output() valueChangeRequest = new EventEmitter<CustomEvent<{ value: string; previousValue: string }>>();
  @Output() valueChange = new EventEmitter<CustomEvent<{ value: string }>>();

  ngOnInit(): void {
    this.listen('value-change-request', this.valueChangeRequest);
    this.listen('value-change', this.valueChange);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
