// x-theme.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input } from '@angular/core';
import type { XTheme as XThemeElement } from '@vanelsas/baredom/x-theme';
import { init } from '@vanelsas/baredom/x-theme';

init();

@Directive({ selector: 'x-theme', standalone: true })
export class BaredomTheme {
  private el: XThemeElement;

  constructor(elRef: ElementRef<XThemeElement>) {
    this.el = elRef.nativeElement;
  }

  @Input() set preset(v: string) { this.el.preset = v as any; }

}
