// x-timeline-item.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XTimelineItem as XTimelineItemElement } from '@vanelsas/baredom/x-timeline-item';
import { init } from '@vanelsas/baredom/x-timeline-item';

init();

@Directive({ selector: 'x-timeline-item', standalone: true })
export class BaredomTimelineItem implements OnInit, OnDestroy {
  private el: XTimelineItemElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XTimelineItemElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set label(v: string) { this.el.label = v as any; }
  @Input() set title(v: string) { this.el.title = v as any; }
  @Input() set status(v: string) { this.el.status = v as any; }
  @Input() set icon(v: string) { this.el.icon = v as any; }
  @Input() set connector(v: string) { this.el.connector = v as any; }
  @Input() set position(v: string) { this.el.position = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }

  @Output() connected = new EventEmitter<CustomEvent<{ status: string; label: string; position: string; disabled: boolean }>>();
  @Output() disconnected = new EventEmitter<CustomEvent<{ status: string; label: string }>>();
  @Output() click = new EventEmitter<CustomEvent<{ status: string; label: string }>>();

  ngOnInit(): void {
    this.listen('x-timeline-item-connected', this.connected);
    this.listen('x-timeline-item-disconnected', this.disconnected);
    this.listen('x-timeline-item-click', this.click);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
