// x-toast.directive.ts — auto-generated by generate_angular.bb, do not edit

import { Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, NgZone } from '@angular/core';
import type { XToast as XToastElement } from '@vanelsas/baredom/x-toast';
import { init } from '@vanelsas/baredom/x-toast';

init();

@Directive({ selector: 'x-toast', standalone: true })
export class BaredomToast implements OnInit, OnDestroy {
  private el: XToastElement;
  private zone: NgZone;
  private listeners: Array<() => void> = [];

  constructor(elRef: ElementRef<XToastElement>, zone: NgZone) {
    this.el = elRef.nativeElement;
    this.zone = zone;
  }

  @Input() set type(v: string) { this.el.type = v as any; }
  @Input() set heading(v: string) { this.el.heading = v as any; }
  @Input() set message(v: string) { this.el.message = v as any; }
  @Input() set icon(v: string) { this.el.icon = v as any; }
  @Input() set dismissible(v: boolean) { this.el.dismissible = v as any; }
  @Input() set disabled(v: boolean) { this.el.disabled = v as any; }
  @Input() set timeoutMs(v: number) { this.el.timeoutMs = v as any; }
  @Input() set showProgress(v: boolean) { this.el.showProgress = v as any; }

  @Output() dismiss = new EventEmitter<CustomEvent<{ type: string; reason: string; heading: string; message: string }>>();

  ngOnInit(): void {
    this.listen('x-toast-dismiss', this.dismiss);
  }

  ngOnDestroy(): void {
    this.listeners.forEach(fn => fn());
  }

  private listen(event: string, emitter: EventEmitter<any>): void {
    const handler = (e: Event) => this.zone.run(() => emitter.emit(e));
    this.el.addEventListener(event, handler);
    this.listeners.push(() => this.el.removeEventListener(event, handler));
  }

}
