<!-- x-avatar-group.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XAvatarGroup as XAvatarGroupElement } from "@vanelsas/baredom/x-avatar-group";
  import { init } from "@vanelsas/baredom/x-avatar-group";
  init();
  export type { XAvatarGroupElement };
  export interface XAvatarGroupProps {
    size?: string;
    overlap?: string;
    max?: number;
    direction?: string;
    disabled?: boolean;
    label?: string;
    el?: XAvatarGroupElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    size,
    overlap,
    max,
    direction,
    disabled,
    label,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XAvatarGroupProps = $props();
</script>

<x-avatar-group
  bind:this={el}
  {size}
  {overlap}
  {max}
  {direction}
  {disabled}
  {label}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-avatar-group>
