<!-- x-bento-grid.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XBentoGrid as XBentoGridElement } from "@vanelsas/baredom/x-bento-grid";
  import { init } from "@vanelsas/baredom/x-bento-grid";
  init();
  export type { XBentoGridElement };
  export interface XBentoGridProps {
    columns?: number;
    gap?: string;
    rowGap?: string;
    columnGap?: string;
    rowHeight?: string;
    el?: XBentoGridElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    columns,
    gap,
    rowGap,
    columnGap,
    rowHeight,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XBentoGridProps = $props();
</script>

<x-bento-grid
  bind:this={el}
  {columns}
  {gap}
  {rowGap}
  {columnGap}
  {rowHeight}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-bento-grid>
