<!-- x-breadcrumbs.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XBreadcrumbs as XBreadcrumbsElement } from "@vanelsas/baredom/x-breadcrumbs";
  import { init } from "@vanelsas/baredom/x-breadcrumbs";
  init();
  export type { XBreadcrumbsElement };
  export interface XBreadcrumbsProps {
    separator?: string;
    size?: string;
    variant?: string;
    wrap?: boolean;
    maxItems?: number;
    itemsBefore?: number;
    itemsAfter?: number;
    disabled?: boolean;
    el?: XBreadcrumbsElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    separator,
    size,
    variant,
    wrap,
    maxItems,
    itemsBefore,
    itemsAfter,
    disabled,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XBreadcrumbsProps = $props();
</script>

<x-breadcrumbs
  bind:this={el}
  {separator}
  {size}
  {variant}
  {wrap}
  {maxItems}
  {itemsBefore}
  {itemsAfter}
  {disabled}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-breadcrumbs>
