<!-- x-button.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XButton as XButtonElement } from "@vanelsas/baredom/x-button";
  import { init } from "@vanelsas/baredom/x-button";
  init();
  export type { XButtonElement };
  export interface XButtonProps {
    disabled?: boolean;
    loading?: boolean;
    pressed?: boolean;
    onpress?: (e: CustomEvent<{ source: string }>) => void;
    onpressstart?: (e: CustomEvent<{ source: string }>) => void;
    onpressend?: (e: CustomEvent<{ source: string }>) => void;
    onhoverstart?: (e: CustomEvent<{}>) => void;
    onhoverend?: (e: CustomEvent<{}>) => void;
    onfocusvisible?: (e: CustomEvent<{}>) => void;
    el?: XButtonElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    disabled,
    loading,
    pressed,
    onpress,
    onpressstart,
    onpressend,
    onhoverstart,
    onhoverend,
    onfocusvisible,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XButtonProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onpressHandler = (e: Event) => onpress?.(e as CustomEvent<{ source: string }>);
    node.addEventListener("press", onpressHandler);
    cleanups.push(() => node.removeEventListener("press", onpressHandler));
    const onpressstartHandler = (e: Event) => onpressstart?.(e as CustomEvent<{ source: string }>);
    node.addEventListener("press-start", onpressstartHandler);
    cleanups.push(() => node.removeEventListener("press-start", onpressstartHandler));
    const onpressendHandler = (e: Event) => onpressend?.(e as CustomEvent<{ source: string }>);
    node.addEventListener("press-end", onpressendHandler);
    cleanups.push(() => node.removeEventListener("press-end", onpressendHandler));
    const onhoverstartHandler = (e: Event) => onhoverstart?.(e as CustomEvent<{}>);
    node.addEventListener("hover-start", onhoverstartHandler);
    cleanups.push(() => node.removeEventListener("hover-start", onhoverstartHandler));
    const onhoverendHandler = (e: Event) => onhoverend?.(e as CustomEvent<{}>);
    node.addEventListener("hover-end", onhoverendHandler);
    cleanups.push(() => node.removeEventListener("hover-end", onhoverendHandler));
    const onfocusvisibleHandler = (e: Event) => onfocusvisible?.(e as CustomEvent<{}>);
    node.addEventListener("focus-visible", onfocusvisibleHandler);
    cleanups.push(() => node.removeEventListener("focus-visible", onfocusvisibleHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-button
  bind:this={el}
  {disabled}
  {loading}
  {pressed}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-button>
