<!-- x-cancel-dialogue.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XCancelDialogue as XCancelDialogueElement } from "@vanelsas/baredom/x-cancel-dialogue";
  import { init } from "@vanelsas/baredom/x-cancel-dialogue";
  init();
  export type { XCancelDialogueElement };
  export interface XCancelDialogueProps {
    open?: boolean;
    disabled?: boolean;
    headline?: string;
    message?: string;
    confirmText?: string;
    cancelText?: string;
    danger?: boolean;
    oncancelrequest?: (e: CustomEvent<{ reason: string }>) => void;
    oncancel?: (e: CustomEvent<{}>) => void;
    onconfirmrequest?: (e: CustomEvent<{}>) => void;
    onconfirm?: (e: CustomEvent<{}>) => void;
    el?: XCancelDialogueElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    disabled,
    headline,
    message,
    confirmText,
    cancelText,
    danger,
    oncancelrequest,
    oncancel,
    onconfirmrequest,
    onconfirm,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XCancelDialogueProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const oncancelrequestHandler = (e: Event) => oncancelrequest?.(e as CustomEvent<{ reason: string }>);
    node.addEventListener("x-cancel-dialogue-cancel-request", oncancelrequestHandler);
    cleanups.push(() => node.removeEventListener("x-cancel-dialogue-cancel-request", oncancelrequestHandler));
    const oncancelHandler = (e: Event) => oncancel?.(e as CustomEvent<{}>);
    node.addEventListener("x-cancel-dialogue-cancel", oncancelHandler);
    cleanups.push(() => node.removeEventListener("x-cancel-dialogue-cancel", oncancelHandler));
    const onconfirmrequestHandler = (e: Event) => onconfirmrequest?.(e as CustomEvent<{}>);
    node.addEventListener("x-cancel-dialogue-confirm-request", onconfirmrequestHandler);
    cleanups.push(() => node.removeEventListener("x-cancel-dialogue-confirm-request", onconfirmrequestHandler));
    const onconfirmHandler = (e: Event) => onconfirm?.(e as CustomEvent<{}>);
    node.addEventListener("x-cancel-dialogue-confirm", onconfirmHandler);
    cleanups.push(() => node.removeEventListener("x-cancel-dialogue-confirm", onconfirmHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-cancel-dialogue
  bind:this={el}
  {open}
  {disabled}
  {headline}
  {message}
  {confirmText}
  {cancelText}
  {danger}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-cancel-dialogue>
