<!-- x-calendar.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XCalendar as XCalendarElement } from "@vanelsas/baredom/x-calendar";
  import { init } from "@vanelsas/baredom/x-calendar";
  init();
  export type { XCalendarElement };
  export interface XCalendarProps {
    min?: string;
    disabled?: boolean;
    locale?: string;
    autoSwap?: boolean;
    value?: string;
    mode?: string;
    start?: string;
    month?: string;
    showWeekNumbers?: boolean;
    disabledDates?: string;
    max?: string;
    firstDayOfWeek?: string;
    end?: string;
    rangeAllowSameDay?: boolean;
    onchange?: (e: CustomEvent<{ value: string; start: string; end: string; mode: string }>) => void;
    onnavigate?: (e: CustomEvent<{ month: string }>) => void;
    el?: XCalendarElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    min,
    disabled,
    locale,
    autoSwap,
    value,
    mode,
    start,
    month,
    showWeekNumbers,
    disabledDates,
    max,
    firstDayOfWeek,
    end,
    rangeAllowSameDay,
    onchange,
    onnavigate,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XCalendarProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ value: string; start: string; end: string; mode: string }>);
    node.addEventListener("x-calendar-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-calendar-change", onchangeHandler));
    const onnavigateHandler = (e: Event) => onnavigate?.(e as CustomEvent<{ month: string }>);
    node.addEventListener("x-calendar-navigate", onnavigateHandler);
    cleanups.push(() => node.removeEventListener("x-calendar-navigate", onnavigateHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-calendar
  bind:this={el}
  {min}
  {disabled}
  {locale}
  {autoSwap}
  {value}
  {mode}
  {start}
  {month}
  {showWeekNumbers}
  {disabledDates}
  {max}
  {firstDayOfWeek}
  {end}
  {rangeAllowSameDay}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-calendar>
