<!-- x-command-palette.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XCommandPalette as XCommandPaletteElement } from "@vanelsas/baredom/x-command-palette";
  import { init } from "@vanelsas/baredom/x-command-palette";
  init();
  export type { XCommandPaletteElement };
  export interface XCommandPaletteProps {
    items?: any;
    open?: boolean;
    disabled?: boolean;
    onopenrequest?: (e: CustomEvent<{}>) => void;
    onopen?: (e: CustomEvent<{}>) => void;
    oncloserequest?: (e: CustomEvent<{}>) => void;
    onclose?: (e: CustomEvent<{}>) => void;
    onselectrequest?: (e: CustomEvent<{ item: Record<string, any> }>) => void;
    onselect?: (e: CustomEvent<{ item: Record<string, any> }>) => void;
    onquerychange?: (e: CustomEvent<{ query: string }>) => void;
    el?: XCommandPaletteElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    items,
    open,
    disabled,
    onopenrequest,
    onopen,
    oncloserequest,
    onclose,
    onselectrequest,
    onselect,
    onquerychange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XCommandPaletteProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onopenrequestHandler = (e: Event) => onopenrequest?.(e as CustomEvent<{}>);
    node.addEventListener("x-command-palette-open-request", onopenrequestHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-open-request", onopenrequestHandler));
    const onopenHandler = (e: Event) => onopen?.(e as CustomEvent<{}>);
    node.addEventListener("x-command-palette-open", onopenHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-open", onopenHandler));
    const oncloserequestHandler = (e: Event) => oncloserequest?.(e as CustomEvent<{}>);
    node.addEventListener("x-command-palette-close-request", oncloserequestHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-close-request", oncloserequestHandler));
    const oncloseHandler = (e: Event) => onclose?.(e as CustomEvent<{}>);
    node.addEventListener("x-command-palette-close", oncloseHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-close", oncloseHandler));
    const onselectrequestHandler = (e: Event) => onselectrequest?.(e as CustomEvent<{ item: Record<string, any> }>);
    node.addEventListener("x-command-palette-select-request", onselectrequestHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-select-request", onselectrequestHandler));
    const onselectHandler = (e: Event) => onselect?.(e as CustomEvent<{ item: Record<string, any> }>);
    node.addEventListener("x-command-palette-select", onselectHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-select", onselectHandler));
    const onquerychangeHandler = (e: Event) => onquerychange?.(e as CustomEvent<{ query: string }>);
    node.addEventListener("x-command-palette-query-change", onquerychangeHandler);
    cleanups.push(() => node.removeEventListener("x-command-palette-query-change", onquerychangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-command-palette
  bind:this={el}
  {items}
  {open}
  {disabled}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-command-palette>
