<!-- x-container.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XContainer as XContainerElement } from "@vanelsas/baredom/x-container";
  import { init } from "@vanelsas/baredom/x-container";
  init();
  export type { XContainerElement };
  export interface XContainerProps {
    center?: boolean;
    fluid?: boolean;
    el?: XContainerElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    center,
    fluid,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XContainerProps = $props();
</script>

<x-container
  bind:this={el}
  {center}
  {fluid}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-container>
