<!-- x-color-picker.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XColorPicker as XColorPickerElement } from "@vanelsas/baredom/x-color-picker";
  import { init } from "@vanelsas/baredom/x-color-picker";
  init();
  export type { XColorPickerElement };
  export interface XColorPickerProps {
    open?: boolean;
    disabled?: boolean;
    name?: string;
    value?: string;
    mode?: string;
    swatches?: string;
    readOnly?: boolean;
    label?: string;
    alpha?: boolean;
    oninput?: (e: CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>) => void;
    onchange?: (e: CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>) => void;
    el?: XColorPickerElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    disabled,
    name,
    value,
    mode,
    swatches,
    readOnly,
    label,
    alpha,
    oninput,
    onchange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XColorPickerProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const oninputHandler = (e: Event) => oninput?.(e as CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>);
    node.addEventListener("x-color-picker-input", oninputHandler);
    cleanups.push(() => node.removeEventListener("x-color-picker-input", oninputHandler));
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ value: string; h: number; s: number; l: number; a: number }>);
    node.addEventListener("x-color-picker-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-color-picker-change", onchangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-color-picker
  bind:this={el}
  {open}
  {disabled}
  {name}
  {value}
  {mode}
  {swatches}
  {readOnly}
  {label}
  {alpha}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-color-picker>
