<!-- x-collapse.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XCollapse as XCollapseElement } from "@vanelsas/baredom/x-collapse";
  import { init } from "@vanelsas/baredom/x-collapse";
  init();
  export type { XCollapseElement };
  export interface XCollapseProps {
    open?: boolean;
    disabled?: boolean;
    header?: string;
    durationMs?: number;
    ontoggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
    onchange?: (e: CustomEvent<{ open: boolean }>) => void;
    el?: XCollapseElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    disabled,
    header,
    durationMs,
    ontoggle,
    onchange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XCollapseProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean; source: string }>);
    node.addEventListener("x-collapse-toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("x-collapse-toggle", ontoggleHandler));
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ open: boolean }>);
    node.addEventListener("x-collapse-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-collapse-change", onchangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-collapse
  bind:this={el}
  {open}
  {disabled}
  {header}
  {durationMs}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-collapse>
