<!-- x-confetti.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XConfetti as XConfettiElement } from "@vanelsas/baredom/x-confetti";
  import { init } from "@vanelsas/baredom/x-confetti";
  init();
  export type { XConfettiElement };
  export interface XConfettiProps {
    disabled?: boolean;
    spread?: number;
    mode?: string;
    colors?: string;
    duration?: number;
    autoFire?: boolean;
    gravity?: number;
    count?: number;
    origin?: string;
    velocity?: number;
    shapes?: string;
    onfire?: (e: CustomEvent<{ count: number; origin: string }>) => void;
    onend?: (e: CustomEvent<{ duration: number }>) => void;
    el?: XConfettiElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    disabled,
    spread,
    mode,
    colors,
    duration,
    autoFire,
    gravity,
    count,
    origin,
    velocity,
    shapes,
    onfire,
    onend,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XConfettiProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onfireHandler = (e: Event) => onfire?.(e as CustomEvent<{ count: number; origin: string }>);
    node.addEventListener("x-confetti-fire", onfireHandler);
    cleanups.push(() => node.removeEventListener("x-confetti-fire", onfireHandler));
    const onendHandler = (e: Event) => onend?.(e as CustomEvent<{ duration: number }>);
    node.addEventListener("x-confetti-end", onendHandler);
    cleanups.push(() => node.removeEventListener("x-confetti-end", onendHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-confetti
  bind:this={el}
  {disabled}
  {spread}
  {mode}
  {colors}
  {duration}
  {autoFire}
  {gravity}
  {count}
  {origin}
  {velocity}
  {shapes}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-confetti>
