<!-- x-date-picker.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XDatePicker as XDatePickerElement } from "@vanelsas/baredom/x-date-picker";
  import { init } from "@vanelsas/baredom/x-date-picker";
  init();
  export type { XDatePickerElement };
  export interface XDatePickerProps {
    open?: boolean;
    disabled?: boolean;
    name?: string;
    value?: string;
    mode?: string;
    start?: string;
    readOnly?: boolean;
    end?: string;
    required?: boolean;
    oninput?: (e: CustomEvent<{ value: string; mode: string }>) => void;
    onchangerequest?: (e: CustomEvent<{ value: string; mode: string; reason: string }>) => void;
    onchange?: (e: CustomEvent<{ value: string; mode: string; reason: string }>) => void;
    el?: XDatePickerElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    disabled,
    name,
    value,
    mode,
    start,
    readOnly,
    end,
    required,
    oninput,
    onchangerequest,
    onchange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XDatePickerProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const oninputHandler = (e: Event) => oninput?.(e as CustomEvent<{ value: string; mode: string }>);
    node.addEventListener("x-date-picker-input", oninputHandler);
    cleanups.push(() => node.removeEventListener("x-date-picker-input", oninputHandler));
    const onchangerequestHandler = (e: Event) => onchangerequest?.(e as CustomEvent<{ value: string; mode: string; reason: string }>);
    node.addEventListener("x-date-picker-change-request", onchangerequestHandler);
    cleanups.push(() => node.removeEventListener("x-date-picker-change-request", onchangerequestHandler));
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ value: string; mode: string; reason: string }>);
    node.addEventListener("x-date-picker-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-date-picker-change", onchangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-date-picker
  bind:this={el}
  {open}
  {disabled}
  {name}
  {value}
  {mode}
  {start}
  {readOnly}
  {end}
  {required}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-date-picker>
