<!-- x-dropdown.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XDropdown as XDropdownElement } from "@vanelsas/baredom/x-dropdown";
  import { init } from "@vanelsas/baredom/x-dropdown";
  init();
  export type { XDropdownElement };
  export interface XDropdownProps {
    open?: boolean;
    disabled?: boolean;
    label?: string;
    placement?: string;
    ontoggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
    onchange?: (e: CustomEvent<{ open: boolean }>) => void;
    el?: XDropdownElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    disabled,
    label,
    placement,
    ontoggle,
    onchange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XDropdownProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean; source: string }>);
    node.addEventListener("x-dropdown-toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("x-dropdown-toggle", ontoggleHandler));
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ open: boolean }>);
    node.addEventListener("x-dropdown-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-dropdown-change", onchangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-dropdown
  bind:this={el}
  {open}
  {disabled}
  {label}
  {placement}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-dropdown>
