<!-- x-fieldset.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XFieldset as XFieldsetElement } from "@vanelsas/baredom/x-fieldset";
  import { init } from "@vanelsas/baredom/x-fieldset";
  init();
  export type { XFieldsetElement };
  export interface XFieldsetProps {
    legend?: string;
    disabled?: boolean;
    el?: XFieldsetElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    legend,
    disabled,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XFieldsetProps = $props();
</script>

<x-fieldset
  bind:this={el}
  {legend}
  {disabled}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-fieldset>
