<!-- x-file-upload.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XFileUpload as XFileUploadElement } from "@vanelsas/baredom/x-file-upload";
  import { init } from "@vanelsas/baredom/x-file-upload";
  init();
  export type { XFileUploadElement };
  export interface XFileUploadProps {
    accept?: string;
    multiple?: boolean;
    maxSize?: number;
    maxFiles?: number;
    disabled?: boolean;
    required?: boolean;
    name?: string;
    onselect?: (e: CustomEvent<{ files: any; rejected: any }>) => void;
    onremove?: (e: CustomEvent<{ file: Record<string, any>; remaining: any }>) => void;
    el?: XFileUploadElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    accept,
    multiple,
    maxSize,
    maxFiles,
    disabled,
    required,
    name,
    onselect,
    onremove,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XFileUploadProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onselectHandler = (e: Event) => onselect?.(e as CustomEvent<{ files: any; rejected: any }>);
    node.addEventListener("x-file-upload-select", onselectHandler);
    cleanups.push(() => node.removeEventListener("x-file-upload-select", onselectHandler));
    const onremoveHandler = (e: Event) => onremove?.(e as CustomEvent<{ file: Record<string, any>; remaining: any }>);
    node.addEventListener("x-file-upload-remove", onremoveHandler);
    cleanups.push(() => node.removeEventListener("x-file-upload-remove", onremoveHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-file-upload
  bind:this={el}
  {accept}
  {multiple}
  {maxSize}
  {maxFiles}
  {disabled}
  {required}
  {name}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-file-upload>
