<!-- x-floating-panel.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XFloatingPanel as XFloatingPanelElement } from "@vanelsas/baredom/x-floating-panel";
  import { init } from "@vanelsas/baredom/x-floating-panel";
  init();
  export type { XFloatingPanelElement };
  export interface XFloatingPanelProps {
    open?: boolean;
    x?: number;
    y?: number;
    step?: number;
    closable?: boolean;
    resizable?: boolean;
    label?: string;
    focusOnOpen?: boolean;
    ontoggle?: (e: CustomEvent<{ open: boolean }>) => void;
    ondismissrequest?: (e: CustomEvent<{ reason: string }>) => void;
    onmove?: (e: CustomEvent<{ x: number; y: number; source: string }>) => void;
    el?: XFloatingPanelElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    x,
    y,
    step,
    closable,
    resizable,
    label,
    focusOnOpen,
    ontoggle,
    ondismissrequest,
    onmove,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XFloatingPanelProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean }>);
    node.addEventListener("x-floating-panel-toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("x-floating-panel-toggle", ontoggleHandler));
    const ondismissrequestHandler = (e: Event) => ondismissrequest?.(e as CustomEvent<{ reason: string }>);
    node.addEventListener("x-floating-panel-dismiss-request", ondismissrequestHandler);
    cleanups.push(() => node.removeEventListener("x-floating-panel-dismiss-request", ondismissrequestHandler));
    const onmoveHandler = (e: Event) => onmove?.(e as CustomEvent<{ x: number; y: number; source: string }>);
    node.addEventListener("x-floating-panel-move", onmoveHandler);
    cleanups.push(() => node.removeEventListener("x-floating-panel-move", onmoveHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-floating-panel
  bind:this={el}
  {open}
  {x}
  {y}
  {step}
  {closable}
  {resizable}
  {label}
  {focusOnOpen}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-floating-panel>
