<!-- x-i18n.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XI18n as XI18nElement } from "@vanelsas/baredom/x-i18n";
  import { init } from "@vanelsas/baredom/x-i18n";
  init();
  export type { XI18nElement };
  export interface XI18nProps {
    key?: string;
    params?: string;
    el?: XI18nElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    key,
    params,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XI18nProps = $props();
</script>

<x-i18n
  bind:this={el}
  {key}
  {params}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-i18n>
