<!-- x-liquid-glass.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XLiquidGlass as XLiquidGlassElement } from "@vanelsas/baredom/x-liquid-glass";
  import { init } from "@vanelsas/baredom/x-liquid-glass";
  init();
  export type { XLiquidGlassElement };
  export interface XLiquidGlassProps {
    frost?: number;
    goo?: number;
    amplitude?: number;
    specularSize?: number;
    disabled?: boolean;
    speed?: number;
    mode?: string;
    specular?: boolean;
    tint?: string;
    color2?: string;
    blur?: number;
    blobs?: number;
    color1?: string;
    specularIntensity?: number;
    el?: XLiquidGlassElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    frost,
    goo,
    amplitude,
    specularSize,
    disabled,
    speed,
    mode,
    specular,
    tint,
    color2,
    blur,
    blobs,
    color1,
    specularIntensity,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XLiquidGlassProps = $props();
</script>

<x-liquid-glass
  bind:this={el}
  {frost}
  {goo}
  {amplitude}
  {specularSize}
  {disabled}
  {speed}
  {mode}
  {specular}
  {tint}
  {color2}
  {blur}
  {blobs}
  {color1}
  {specularIntensity}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-liquid-glass>
