<!-- x-liquid-fill.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XLiquidFill as XLiquidFillElement } from "@vanelsas/baredom/x-liquid-fill";
  import { init } from "@vanelsas/baredom/x-liquid-fill";
  init();
  export type { XLiquidFillElement };
  export interface XLiquidFillProps {
    waveIntensity?: number;
    disabled?: boolean;
    splashIntensity?: number;
    mode?: string;
    orientation?: string;
    theme?: string;
    layers?: number;
    target?: string;
    onprogress?: (e: CustomEvent<{ progress: number; velocity: number }>) => void;
    el?: XLiquidFillElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    waveIntensity,
    disabled,
    splashIntensity,
    mode,
    orientation,
    theme,
    layers,
    target,
    onprogress,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XLiquidFillProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onprogressHandler = (e: Event) => onprogress?.(e as CustomEvent<{ progress: number; velocity: number }>);
    node.addEventListener("x-liquid-fill-progress", onprogressHandler);
    cleanups.push(() => node.removeEventListener("x-liquid-fill-progress", onprogressHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-liquid-fill
  bind:this={el}
  {waveIntensity}
  {disabled}
  {splashIntensity}
  {mode}
  {orientation}
  {theme}
  {layers}
  {target}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-liquid-fill>
