<!-- x-menu-item.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XMenuItem as XMenuItemElement } from "@vanelsas/baredom/x-menu-item";
  import { init } from "@vanelsas/baredom/x-menu-item";
  init();
  export type { XMenuItemElement };
  export interface XMenuItemProps {
    value?: string;
    disabled?: boolean;
    variant?: string;
    type?: string;
    onselect?: (e: CustomEvent<{ value: string }>) => void;
    el?: XMenuItemElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    value,
    disabled,
    variant,
    type,
    onselect,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XMenuItemProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onselectHandler = (e: Event) => onselect?.(e as CustomEvent<{ value: string }>);
    node.addEventListener("x-menu-item-select", onselectHandler);
    cleanups.push(() => node.removeEventListener("x-menu-item-select", onselectHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-menu-item
  bind:this={el}
  {value}
  {disabled}
  {variant}
  {type}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-menu-item>
