<!-- x-modal.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XModal as XModalElement } from "@vanelsas/baredom/x-modal";
  import { init } from "@vanelsas/baredom/x-modal";
  init();
  export type { XModalElement };
  export interface XModalProps {
    open?: boolean;
    size?: string;
    label?: string;
    ontoggle?: (e: CustomEvent<{ open: boolean }>) => void;
    ondismiss?: (e: CustomEvent<{ reason: string }>) => void;
    el?: XModalElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    size,
    label,
    ontoggle,
    ondismiss,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XModalProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean }>);
    node.addEventListener("x-modal-toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("x-modal-toggle", ontoggleHandler));
    const ondismissHandler = (e: Event) => ondismiss?.(e as CustomEvent<{ reason: string }>);
    node.addEventListener("x-modal-dismiss", ondismissHandler);
    cleanups.push(() => node.removeEventListener("x-modal-dismiss", ondismissHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-modal
  bind:this={el}
  {open}
  {size}
  {label}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-modal>
