<!-- x-multi-combobox.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XMultiCombobox as XMultiComboboxElement } from "@vanelsas/baredom/x-multi-combobox";
  import { init } from "@vanelsas/baredom/x-multi-combobox";
  init();
  export type { XMultiComboboxElement };
  export interface XMultiComboboxProps {
    open?: boolean;
    placeholder?: string;
    disabled?: boolean;
    name?: string;
    max?: number;
    error?: string;
    placement?: string;
    required?: boolean;
    /** Two-way bindable form value — `bind:value={...}`. */
    value?: string[];
    onchangerequest?: (e: CustomEvent<{ value: any; action: string; item: string }>) => void;
    onchange?: (e: CustomEvent<{ value: any }>) => void;
    oninput?: (e: CustomEvent<{ query: string }>) => void;
    ontoggle?: (e: CustomEvent<{ open: boolean; source: string }>) => void;
    el?: XMultiComboboxElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    placeholder,
    disabled,
    name,
    max,
    error,
    placement,
    required,
    value = $bindable(undefined),
    onchangerequest,
    onchange,
    oninput,
    ontoggle,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XMultiComboboxProps = $props();

  $effect(() => {
    const node = el;
    if (!node || value === undefined) return;
    if (value != null) node.setAttribute("value", String(value));
    else node.removeAttribute("value");
  });

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onchangerequestHandler = (e: Event) => onchangerequest?.(e as CustomEvent<{ value: any; action: string; item: string }>);
    node.addEventListener("x-multi-combobox-change-request", onchangerequestHandler);
    cleanups.push(() => node.removeEventListener("x-multi-combobox-change-request", onchangerequestHandler));
    const onchangeHandler = (e: Event) => {
      const detail = (e as CustomEvent<{ value: any }>).detail;
      value = (detail.value);
      onchange?.(e as CustomEvent<{ value: any }>);
    };
    node.addEventListener("x-multi-combobox-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-multi-combobox-change", onchangeHandler));
    const oninputHandler = (e: Event) => oninput?.(e as CustomEvent<{ query: string }>);
    node.addEventListener("x-multi-combobox-input", oninputHandler);
    cleanups.push(() => node.removeEventListener("x-multi-combobox-input", oninputHandler));
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean; source: string }>);
    node.addEventListener("x-multi-combobox-toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("x-multi-combobox-toggle", ontoggleHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-multi-combobox
  bind:this={el}
  {open}
  {placeholder}
  {disabled}
  {name}
  {max}
  {error}
  {placement}
  {required}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-multi-combobox>
