// x-multi-combobox.ts — auto-generated by generate_svelte.bb, do not edit
export { default as XMultiCombobox, type XMultiComboboxProps, type XMultiComboboxElement } from "./x-multi-combobox.svelte";
