// x-notification-center.ts — auto-generated by generate_svelte.bb, do not edit
export { default as XNotificationCenter, type XNotificationCenterProps, type XNotificationCenterElement } from "./x-notification-center.svelte";
