<!-- x-notification-center.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XNotificationCenter as XNotificationCenterElement } from "@vanelsas/baredom/x-notification-center";
  import { init } from "@vanelsas/baredom/x-notification-center";
  init();
  export type { XNotificationCenterElement };
  export interface XNotificationCenterProps {
    position?: string;
    max?: number;
    onpush?: (e: CustomEvent<{ id: string; count: number }>) => void;
    ondismiss?: (e: CustomEvent<{ id: string; type: string; reason: string; text: string; count: number }>) => void;
    onempty?: (e: CustomEvent<{}>) => void;
    el?: XNotificationCenterElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    position,
    max,
    onpush,
    ondismiss,
    onempty,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XNotificationCenterProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onpushHandler = (e: Event) => onpush?.(e as CustomEvent<{ id: string; count: number }>);
    node.addEventListener("x-notification-center-push", onpushHandler);
    cleanups.push(() => node.removeEventListener("x-notification-center-push", onpushHandler));
    const ondismissHandler = (e: Event) => ondismiss?.(e as CustomEvent<{ id: string; type: string; reason: string; text: string; count: number }>);
    node.addEventListener("x-notification-center-dismiss", ondismissHandler);
    cleanups.push(() => node.removeEventListener("x-notification-center-dismiss", ondismissHandler));
    const onemptyHandler = (e: Event) => onempty?.(e as CustomEvent<{}>);
    node.addEventListener("x-notification-center-empty", onemptyHandler);
    cleanups.push(() => node.removeEventListener("x-notification-center-empty", onemptyHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-notification-center
  bind:this={el}
  {position}
  {max}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-notification-center>
