<!-- x-pagination.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XPagination as XPaginationElement } from "@vanelsas/baredom/x-pagination";
  import { init } from "@vanelsas/baredom/x-pagination";
  init();
  export type { XPaginationElement };
  export interface XPaginationProps {
    totalPages?: number;
    siblingCount?: number;
    boundaryCount?: number;
    size?: string;
    disabled?: boolean;
    label?: string;
    /** Two-way bindable form value — `bind:page={...}`. */
    page?: number;
    onpagechangerequest?: (e: CustomEvent<{ page: number; previousPage: number }>) => void;
    onpagechange?: (e: CustomEvent<{ page: number }>) => void;
    el?: XPaginationElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    totalPages,
    siblingCount,
    boundaryCount,
    size,
    disabled,
    label,
    page = $bindable(undefined),
    onpagechangerequest,
    onpagechange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XPaginationProps = $props();

  $effect(() => {
    const node = el;
    if (!node || page === undefined) return;
    if (page != null) node.setAttribute("page", String(page));
    else node.removeAttribute("page");
  });

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onpagechangerequestHandler = (e: Event) => onpagechangerequest?.(e as CustomEvent<{ page: number; previousPage: number }>);
    node.addEventListener("page-change-request", onpagechangerequestHandler);
    cleanups.push(() => node.removeEventListener("page-change-request", onpagechangerequestHandler));
    const onpagechangeHandler = (e: Event) => {
      const detail = (e as CustomEvent<{ page: number }>).detail;
      page = Number(detail.page);
      onpagechange?.(e as CustomEvent<{ page: number }>);
    };
    node.addEventListener("page-change", onpagechangeHandler);
    cleanups.push(() => node.removeEventListener("page-change", onpagechangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-pagination
  bind:this={el}
  {totalPages}
  {siblingCount}
  {boundaryCount}
  {size}
  {disabled}
  {label}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-pagination>
