<!-- x-progress-circle.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XProgressCircle as XProgressCircleElement } from "@vanelsas/baredom/x-progress-circle";
  import { init } from "@vanelsas/baredom/x-progress-circle";
  init();
  export type { XProgressCircleElement };
  export interface XProgressCircleProps {
    value?: string;
    max?: string;
    variant?: string;
    size?: string;
    label?: string;
    indeterminate?: boolean;
    showValue?: boolean;
    oncomplete?: (e: CustomEvent<{ value: number; max: number }>) => void;
    el?: XProgressCircleElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    value,
    max,
    variant,
    size,
    label,
    indeterminate,
    showValue,
    oncomplete,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XProgressCircleProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const oncompleteHandler = (e: Event) => oncomplete?.(e as CustomEvent<{ value: number; max: number }>);
    node.addEventListener("x-progress-circle-complete", oncompleteHandler);
    cleanups.push(() => node.removeEventListener("x-progress-circle-complete", oncompleteHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-progress-circle
  bind:this={el}
  {value}
  {max}
  {variant}
  {size}
  {label}
  {indeterminate}
  {showValue}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-progress-circle>
