<!-- x-ripple-effect.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XRippleEffect as XRippleEffectElement } from "@vanelsas/baredom/x-ripple-effect";
  import { init } from "@vanelsas/baredom/x-ripple-effect";
  init();
  export type { XRippleEffectElement };
  export interface XRippleEffectProps {
    intensity?: number;
    duration?: number;
    frequency?: number;
    disabled?: boolean;
    onstart?: (e: CustomEvent<{ x: number; y: number }>) => void;
    onend?: (e: CustomEvent<{ x: number; y: number }>) => void;
    el?: XRippleEffectElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    intensity,
    duration,
    frequency,
    disabled,
    onstart,
    onend,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XRippleEffectProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onstartHandler = (e: Event) => onstart?.(e as CustomEvent<{ x: number; y: number }>);
    node.addEventListener("x-ripple-effect-start", onstartHandler);
    cleanups.push(() => node.removeEventListener("x-ripple-effect-start", onstartHandler));
    const onendHandler = (e: Event) => onend?.(e as CustomEvent<{ x: number; y: number }>);
    node.addEventListener("x-ripple-effect-end", onendHandler);
    cleanups.push(() => node.removeEventListener("x-ripple-effect-end", onendHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-ripple-effect
  bind:this={el}
  {intensity}
  {duration}
  {frequency}
  {disabled}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-ripple-effect>
