// x-scroll-parallax.ts — auto-generated by generate_svelte.bb, do not edit
export { default as XScrollParallax, type XScrollParallaxProps, type XScrollParallaxElement } from "./x-scroll-parallax.svelte";
