<!-- x-search-field.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XSearchField as XSearchFieldElement } from "@vanelsas/baredom/x-search-field";
  import { init } from "@vanelsas/baredom/x-search-field";
  init();
  export type { XSearchFieldElement };
  export interface XSearchFieldProps {
    value?: string;
    name?: string;
    placeholder?: string;
    label?: string;
    autocomplete?: string;
    disabled?: boolean;
    required?: boolean;
    debounce?: number;
    oninput?: (e: CustomEvent<{ name: string; value: string }>) => void;
    onchange?: (e: CustomEvent<{ name: string; value: string }>) => void;
    onsearch?: (e: CustomEvent<{ name: string; value: string }>) => void;
    onclear?: (e: CustomEvent<{ name: string }>) => void;
    el?: XSearchFieldElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    value,
    name,
    placeholder,
    label,
    autocomplete,
    disabled,
    required,
    debounce,
    oninput,
    onchange,
    onsearch,
    onclear,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XSearchFieldProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const oninputHandler = (e: Event) => oninput?.(e as CustomEvent<{ name: string; value: string }>);
    node.addEventListener("x-search-field-input", oninputHandler);
    cleanups.push(() => node.removeEventListener("x-search-field-input", oninputHandler));
    const onchangeHandler = (e: Event) => onchange?.(e as CustomEvent<{ name: string; value: string }>);
    node.addEventListener("x-search-field-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-search-field-change", onchangeHandler));
    const onsearchHandler = (e: Event) => onsearch?.(e as CustomEvent<{ name: string; value: string }>);
    node.addEventListener("x-search-field-search", onsearchHandler);
    cleanups.push(() => node.removeEventListener("x-search-field-search", onsearchHandler));
    const onclearHandler = (e: Event) => onclear?.(e as CustomEvent<{ name: string }>);
    node.addEventListener("x-search-field-clear", onclearHandler);
    cleanups.push(() => node.removeEventListener("x-search-field-clear", onclearHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-search-field
  bind:this={el}
  {value}
  {name}
  {placeholder}
  {label}
  {autocomplete}
  {disabled}
  {required}
  {debounce}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-search-field>
