<!-- x-sidebar.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XSidebar as XSidebarElement } from "@vanelsas/baredom/x-sidebar";
  import { init } from "@vanelsas/baredom/x-sidebar";
  init();
  export type { XSidebarElement };
  export interface XSidebarProps {
    open?: boolean;
    collapsed?: boolean;
    ontoggle?: (e: CustomEvent<{ open: boolean }>) => void;
    ondismiss?: (e: CustomEvent<{ reason: string }>) => void;
    el?: XSidebarElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    open,
    collapsed,
    ontoggle,
    ondismiss,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XSidebarProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontoggleHandler = (e: Event) => ontoggle?.(e as CustomEvent<{ open: boolean }>);
    node.addEventListener("toggle", ontoggleHandler);
    cleanups.push(() => node.removeEventListener("toggle", ontoggleHandler));
    const ondismissHandler = (e: Event) => ondismiss?.(e as CustomEvent<{ reason: string }>);
    node.addEventListener("dismiss", ondismissHandler);
    cleanups.push(() => node.removeEventListener("dismiss", ondismissHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-sidebar
  bind:this={el}
  {open}
  {collapsed}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-sidebar>
