<!-- x-skeleton-group.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XSkeletonGroup as XSkeletonGroupElement } from "@vanelsas/baredom/x-skeleton-group";
  import { init } from "@vanelsas/baredom/x-skeleton-group";
  init();
  export type { XSkeletonGroupElement };
  export interface XSkeletonGroupProps {
    preset?: string;
    animation?: string;
    count?: number;
    el?: XSkeletonGroupElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    preset,
    animation,
    count,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XSkeletonGroupProps = $props();
</script>

<x-skeleton-group
  bind:this={el}
  {preset}
  {animation}
  {count}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-skeleton-group>
