// x-skeleton-group.ts — auto-generated by generate_svelte.bb, do not edit
export { default as XSkeletonGroup, type XSkeletonGroupProps, type XSkeletonGroupElement } from "./x-skeleton-group.svelte";
