<!-- x-switch.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XSwitch as XSwitchElement } from "@vanelsas/baredom/x-switch";
  import { init } from "@vanelsas/baredom/x-switch";
  init();
  export type { XSwitchElement };
  export interface XSwitchProps {
    disabled?: boolean;
    readOnly?: boolean;
    required?: boolean;
    name?: string;
    value?: string;
    /** Two-way bindable form value — `bind:checked={...}`. */
    checked?: boolean;
    onchangerequest?: (e: CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>) => void;
    onchange?: (e: CustomEvent<{ value: string; checked: boolean }>) => void;
    el?: XSwitchElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    disabled,
    readOnly,
    required,
    name,
    value,
    checked = $bindable(undefined),
    onchangerequest,
    onchange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XSwitchProps = $props();

  $effect(() => {
    const node = el;
    if (!node || checked === undefined) return;
    if (checked) node.setAttribute("checked", "");
    else node.removeAttribute("checked");
  });

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onchangerequestHandler = (e: Event) => onchangerequest?.(e as CustomEvent<{ value: string; previousChecked: boolean; nextChecked: boolean }>);
    node.addEventListener("x-switch-change-request", onchangerequestHandler);
    cleanups.push(() => node.removeEventListener("x-switch-change-request", onchangerequestHandler));
    const onchangeHandler = (e: Event) => {
      const detail = (e as CustomEvent<{ value: string; checked: boolean }>).detail;
      checked = Boolean(detail.checked);
      onchange?.(e as CustomEvent<{ value: string; checked: boolean }>);
    };
    node.addEventListener("x-switch-change", onchangeHandler);
    cleanups.push(() => node.removeEventListener("x-switch-change", onchangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-switch
  bind:this={el}
  {disabled}
  {readOnly}
  {required}
  {name}
  {value}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-switch>
