<!-- x-tab.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XTab as XTabElement } from "@vanelsas/baredom/x-tab";
  import { init } from "@vanelsas/baredom/x-tab";
  init();
  export type { XTabElement };
  export interface XTabProps {
    selected?: boolean;
    disabled?: boolean;
    value?: string;
    ontabselect?: (e: CustomEvent<{ value: string }>) => void;
    el?: XTabElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    selected,
    disabled,
    value,
    ontabselect,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XTabProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const ontabselectHandler = (e: Event) => ontabselect?.(e as CustomEvent<{ value: string }>);
    node.addEventListener("tab-select", ontabselectHandler);
    cleanups.push(() => node.removeEventListener("tab-select", ontabselectHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-tab
  bind:this={el}
  {selected}
  {disabled}
  {value}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-tab>
