<!-- x-table.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XTable as XTableElement } from "@vanelsas/baredom/x-table";
  import { init } from "@vanelsas/baredom/x-table";
  init();
  export type { XTableElement };
  export interface XTableProps {
    columns?: string;
    caption?: string;
    selectable?: string;
    striped?: boolean;
    bordered?: boolean;
    fullWidth?: boolean;
    compact?: boolean;
    rowCount?: number;
    onsort?: (e: CustomEvent<{ colIndex: number; direction: string; previousDirection: string }>) => void;
    onrowselect?: (e: CustomEvent<{ rowIndex: number; selected: boolean; selectionMode: string }>) => void;
    el?: XTableElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    columns,
    caption,
    selectable,
    striped,
    bordered,
    fullWidth,
    compact,
    rowCount,
    onsort,
    onrowselect,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XTableProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onsortHandler = (e: Event) => onsort?.(e as CustomEvent<{ colIndex: number; direction: string; previousDirection: string }>);
    node.addEventListener("x-table-sort", onsortHandler);
    cleanups.push(() => node.removeEventListener("x-table-sort", onsortHandler));
    const onrowselectHandler = (e: Event) => onrowselect?.(e as CustomEvent<{ rowIndex: number; selected: boolean; selectionMode: string }>);
    node.addEventListener("x-table-row-select", onrowselectHandler);
    cleanups.push(() => node.removeEventListener("x-table-row-select", onrowselectHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-table
  bind:this={el}
  {columns}
  {caption}
  {selectable}
  {striped}
  {bordered}
  {fullWidth}
  {compact}
  {rowCount}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-table>
