<!-- x-tabs.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XTabs as XTabsElement } from "@vanelsas/baredom/x-tabs";
  import { init } from "@vanelsas/baredom/x-tabs";
  init();
  export type { XTabsElement };
  export interface XTabsProps {
    /** Two-way bindable form value — `bind:value={...}`. */
    value?: string;
    onvaluechangerequest?: (e: CustomEvent<{ value: string; previousValue: string }>) => void;
    onvaluechange?: (e: CustomEvent<{ value: string }>) => void;
    el?: XTabsElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    value = $bindable(undefined),
    onvaluechangerequest,
    onvaluechange,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XTabsProps = $props();

  $effect(() => {
    const node = el;
    if (!node || value === undefined) return;
    if (value != null) node.setAttribute("value", String(value));
    else node.removeAttribute("value");
  });

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onvaluechangerequestHandler = (e: Event) => onvaluechangerequest?.(e as CustomEvent<{ value: string; previousValue: string }>);
    node.addEventListener("value-change-request", onvaluechangerequestHandler);
    cleanups.push(() => node.removeEventListener("value-change-request", onvaluechangerequestHandler));
    const onvaluechangeHandler = (e: Event) => {
      const detail = (e as CustomEvent<{ value: string }>).detail;
      value = String(detail.value);
      onvaluechange?.(e as CustomEvent<{ value: string }>);
    };
    node.addEventListener("value-change", onvaluechangeHandler);
    cleanups.push(() => node.removeEventListener("value-change", onvaluechangeHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-tabs
  bind:this={el}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-tabs>
