<!-- x-timeline.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XTimeline as XTimelineElement } from "@vanelsas/baredom/x-timeline";
  import { init } from "@vanelsas/baredom/x-timeline";
  init();
  export type { XTimelineElement };
  export interface XTimelineProps {
    label?: string;
    position?: string;
    striped?: boolean;
    onselect?: (e: CustomEvent<{ index: number; status: string; label: string }>) => void;
    el?: XTimelineElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    label,
    position,
    striped,
    onselect,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XTimelineProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onselectHandler = (e: Event) => onselect?.(e as CustomEvent<{ index: number; status: string; label: string }>);
    node.addEventListener("x-timeline-select", onselectHandler);
    cleanups.push(() => node.removeEventListener("x-timeline-select", onselectHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-timeline
  bind:this={el}
  {label}
  {position}
  {striped}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-timeline>
