<!-- x-timeline-item.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XTimelineItem as XTimelineItemElement } from "@vanelsas/baredom/x-timeline-item";
  import { init } from "@vanelsas/baredom/x-timeline-item";
  init();
  export type { XTimelineItemElement };
  export interface XTimelineItemProps {
    label?: string;
    title?: string;
    status?: string;
    icon?: string;
    connector?: string;
    position?: string;
    disabled?: boolean;
    onconnected?: (e: CustomEvent<{ status: string; label: string; position: string; disabled: boolean }>) => void;
    ondisconnected?: (e: CustomEvent<{ status: string; label: string }>) => void;
    onclick?: (e: CustomEvent<{ status: string; label: string }>) => void;
    el?: XTimelineItemElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    label,
    title,
    status,
    icon,
    connector,
    position,
    disabled,
    onconnected,
    ondisconnected,
    onclick,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XTimelineItemProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onconnectedHandler = (e: Event) => onconnected?.(e as CustomEvent<{ status: string; label: string; position: string; disabled: boolean }>);
    node.addEventListener("x-timeline-item-connected", onconnectedHandler);
    cleanups.push(() => node.removeEventListener("x-timeline-item-connected", onconnectedHandler));
    const ondisconnectedHandler = (e: Event) => ondisconnected?.(e as CustomEvent<{ status: string; label: string }>);
    node.addEventListener("x-timeline-item-disconnected", ondisconnectedHandler);
    cleanups.push(() => node.removeEventListener("x-timeline-item-disconnected", ondisconnectedHandler));
    const onclickHandler = (e: Event) => onclick?.(e as CustomEvent<{ status: string; label: string }>);
    node.addEventListener("x-timeline-item-click", onclickHandler);
    cleanups.push(() => node.removeEventListener("x-timeline-item-click", onclickHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-timeline-item
  bind:this={el}
  {label}
  {title}
  {status}
  {icon}
  {connector}
  {position}
  {disabled}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-timeline-item>
