<!-- x-welcome-tour.svelte — auto-generated by generate_svelte.bb, do not edit -->
<script lang="ts" module>
  import type { XWelcomeTour as XWelcomeTourElement } from "@vanelsas/baredom/x-welcome-tour";
  import { init } from "@vanelsas/baredom/x-welcome-tour";
  init();
  export type { XWelcomeTourElement };
  export interface XWelcomeTourProps {
    connector?: string;
    open?: boolean;
    prevLabel?: string;
    nextLabel?: string;
    counter?: boolean;
    doneLabel?: string;
    skipLabel?: string;
    dots?: boolean;
    step?: number;
    onstart?: (e: CustomEvent<{}>) => void;
    onstepchange?: (e: CustomEvent<{ step: number; previousStep: number }>) => void;
    oncomplete?: (e: CustomEvent<{ stepsCompleted: number }>) => void;
    onskip?: (e: CustomEvent<{ step: number }>) => void;
    el?: XWelcomeTourElement | null;
    children?: import("svelte").Snippet;
    class?: string;
    id?: string;
    slot?: string;
  }
</script>

<script lang="ts">
  let {
    connector,
    open,
    prevLabel,
    nextLabel,
    counter,
    doneLabel,
    skipLabel,
    dots,
    step,
    onstart,
    onstepchange,
    oncomplete,
    onskip,
    el = $bindable(null),
    children,
    class: className,
    id,
    ...rest
  }: XWelcomeTourProps = $props();

  $effect(() => {
    const node = el;
    if (!node) return;
    const cleanups: Array<() => void> = [];
    const onstartHandler = (e: Event) => onstart?.(e as CustomEvent<{}>);
    node.addEventListener("x-welcome-tour-start", onstartHandler);
    cleanups.push(() => node.removeEventListener("x-welcome-tour-start", onstartHandler));
    const onstepchangeHandler = (e: Event) => onstepchange?.(e as CustomEvent<{ step: number; previousStep: number }>);
    node.addEventListener("x-welcome-tour-step-change", onstepchangeHandler);
    cleanups.push(() => node.removeEventListener("x-welcome-tour-step-change", onstepchangeHandler));
    const oncompleteHandler = (e: Event) => oncomplete?.(e as CustomEvent<{ stepsCompleted: number }>);
    node.addEventListener("x-welcome-tour-complete", oncompleteHandler);
    cleanups.push(() => node.removeEventListener("x-welcome-tour-complete", oncompleteHandler));
    const onskipHandler = (e: Event) => onskip?.(e as CustomEvent<{ step: number }>);
    node.addEventListener("x-welcome-tour-skip", onskipHandler);
    cleanups.push(() => node.removeEventListener("x-welcome-tour-skip", onskipHandler));
    return () => cleanups.forEach((fn) => fn());
  });
</script>

<x-welcome-tour
  bind:this={el}
  {connector}
  {open}
  {prevLabel}
  {nextLabel}
  {counter}
  {doneLabel}
  {skipLabel}
  {dots}
  {step}
  class={className}
  {id}
  {...rest}
>
  {@render children?.()}
</x-welcome-tour>
